### ISSUE TITLE
Is it possible to allow anyone view public posts without logging in?

### ISSUE THREAD

**Issue by tansinan** [diaspora/diaspora#7368] opened 2017-03-16 11:04 UTC
Hi, I wonder if it is possible, to allow anyone to read public posts, without logging in or registration?

**Comment by Flaburgan** [comment] 2017-03-16 11:12
The posts of a user are already accessible on his profile page, see mine at https://diaspora-fr.org/u/fla for example. Or are you talking about every public post of a pod, so the https://diaspora-fr.org/public stream, to be accessible without logging in?

**Comment by SuperTux88** [comment] 2017-03-16 11:59
If public posts of a user, that's already possible, if you mean /public, then it's a duplicate of #6564.

**Closed by SuperTux88** 2017-03-16 11:59 UTC
