### ISSUE TITLE
retroactively federate post details

### ISSUE THREAD

**Issue by 6543** [diaspora/diaspora#7635] opened 2017-10-09 12:30 UTC
You can see comments on public posts at that time when you reshare, commet or like.
But not backwards!

example:
origin: https://sechat.org/posts/e8cbca70897d013564520242ac110005
other pod: https://diaspora.altinsystems.de/posts/e8cbca70897d013564520242ac110005

**Comment by SuperTux88** [comment] 2017-10-09 16:43
Duplicate of #3350

**Closed by SuperTux88** 2017-10-09 16:43 UTC
