### ISSUE TITLE
Sometimes timestamp is not shown on posts

### ISSUE THREAD

**Issue by MasterOfTheTiger** [diaspora/diaspora#8046] opened 2019-07-15 10:41 UTC
Sometimes I notice that diaspora* does not load the timestamps for posts when loading a page. 

Here is an example:
![diaspora-bug-1](https://user-images.githubusercontent.com/16640496/61210454-dbbbd400-a6fc-11e9-834a-1017d5b7f541.png)

After reloading:
![diaspora-bug-2](https://user-images.githubusercontent.com/16640496/61210473-e70eff80-a6fc-11e9-8cd4-b5d42a406f33.png)

I have noticed this both on profiles and in the stream. 

The code for the timestamp appears, but misses a the text in the `<time>` tag.
```
<span class="details gray post-timestamp">
          -
          <a href="/posts/44664">
            <time class="timeago" data-original-title="7/15/2019, 6:00:14 AM" datetime="2019-07-15T04:00:14.000Z"></time>
          </a>

          <a href="/posts/f98a977088e2013743b8005056009f8c" class="permalink" title="" data-original-title="Permalink">
            <i class="entypo-link"></i>
          </a>
        </span>
```

After reloading:
```
<span class="details gray post-timestamp">
          -
          <a href="/posts/44664">
            <time class="timeago" data-original-title="7/15/2019, 6:00:14 AM" datetime="2019-07-15T04:00:14.000Z">about 7 hours ago</time>
          </a>

          <a href="/posts/f98a977088e2013743b8005056009f8c" class="permalink" title="" data-original-title="Permalink">
            <i class="entypo-link"></i>
          </a>
        </span>
```

Steps to reproduce:
1. Load a few different users' profiles from your stream (or anywhere else) in different browser tabs
2. Close tabs which it does not happen
3. Repeat until bug is reproduced

**Comment by SuperTux88** [comment] 2019-07-15 10:43
Duplicate of #7762

**Closed by SuperTux88** 2019-07-15 10:43 UTC

**Comment by MasterOfTheTiger** [comment] 2019-07-15 10:47
Sorry about that. I did a few queries through the issues to try and find another issue. I guess I used the wrong words. I will do better next time.

**Comment by SuperTux88** [comment] 2019-07-15 10:50
No problem, I sometimes have the same problem (where I know the bug already exists, and even then can't find them).
