### ISSUE TITLE
Scroll to the first unread comment in the post page coming from notifications

### ISSUE THREAD

**Issue by Hypolite** [diaspora/diaspora#7099] opened 2016-09-13 05:15 UTC
This is a feature request I'm unfortunately unable to submit as a pull request, not having the required Ruby and Rails experience..

**Current situation**:

Comment notifications links lead to the post page, at the top of it, showing the oldest post. When the comment thread is only one screen high, it's not an issue, but if a dialogue drags on, then it becomes fastidious to scroll through already read comments to find the new one(s).

**Wished situation**:

Comment notifications links lead to the post page and scroll to the first unread comment by a # anchor in the URL of the link. The anchor can by the id of the first unread comment and all comments can have an anchor with their id.

**Database/Model changes**:

Comment notifications are stored with the parent post id as the `target_id`  field, but not the comment id itself. As such, it's impossible as of now to implement this feature without touching the model in some manner. I see two ways of doing it:
- Adding a nullable field `subtarget_id` that could hold the id of the first unread comment. Easily set, easily read, but it's a schema change;
- Change the `target_type` of comment notifications to `Comment`, but that requires an additionnal DB fetch/join to retrieve the parent post id to construct the notification link;

As far I understand the way the app is structured, it doesn't look like a heavy change, and I would have been happy to make it myself if I was more versed in Ruby and Rails. Let me know if I'm terribly wrong.

Thanks for reading!

**Comment by SuperTux88** [comment] 2016-09-13 08:01
This is a duplicate of #5203.

**Closed by SuperTux88** 2016-09-13 08:01 UTC

**Comment by Hypolite** [comment] 2016-09-13 14:41
Sorry for the duplicate, moving the technical suggestion in #5203.
