### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by xSquid** [diaspora/diaspora#7824] opened 2018-06-08 13:50 UTC
Hi,

The Hubzilla permalinks generate an 404 error

Example:
-> this post: https://framasphere.org/posts/5144456
-> its permalink: https://framasphere.org/posts/2a08e5fae4e40c65f6155e57b12e7a06845bb368b5dfeb8a1853761f59d9bdc8@gerzilla.de

I tried posts from several hubs using my framasphere account

I'm also opening a ticket to hubzilla's.

**Comment by Flaburgan** [comment] 2018-06-08 13:56
Duplicate of https://github.com/diaspora/diaspora/issues/7812 but thanks for reporting anyway!

**Closed by Flaburgan** 2018-06-08 13:56 UTC

**Comment by xSquid** [comment] 2018-06-08 14:05
Ooops, I didn't see!
