### ISSUE TITLE
account deletion broken

### ISSUE THREAD

**Issue by indyfractal** [diaspora/diaspora#7851] opened 2018-09-03 21:00 UTC
When deleting an account not all data is deleted

version 0.7.6.0

steps to replicate

1. create an account ( here user3@127.0.0.2  )
2. add some comments on the user's own posts
3. add some comments on another user's posts
4. like some posts from other users.
5. delete the account 

result : 

1. the account is still present in the people's table and marked closed with the closed_account attribute set to 1 : 

```
mysql> select * from people where closed_account='1';

|  5 | 16e15d50917301364f2d08002714e924 | user3@127.0.0.2    | -----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
 |        5 | 2018-09-03 06:47:05 | 2018-09-03 16:26:13 |              1 |            0 |   NULL |
 ```
 
2. the account is still present in the profiles's table ( even if emptied from user's info ):

```
mysql> select * from profiles where person_id=5;
+----+-----------------+------------+-----------+-----------+-----------------+------------------+----------+--------+------+------------+-----------+---------------------+---------------------+----------+-----------+------+----------------+
| id | diaspora_handle | first_name | last_name | image_url | image_url_small | image_url_medium | birthday | gender | bio  | searchable | person_id | created_at          | updated_at          | location | full_name | nsfw | public_details |
+----+-----------------+------------+-----------+-----------+-----------------+------------------+----------+--------+------+------------+-----------+---------------------+---------------------+----------+-----------+------+----------------+
|  5 | NULL            | NULL       | NULL      | NULL      | NULL            | NULL             | NULL     | NULL   | NULL |          0 |         5 | 2018-09-03 06:47:05 | 2018-09-03 16:26:14 | NULL     |           | NULL |           NULL |
+----+-----------------+------------+-----------+-----------+-----------------+------------------+----------+--------+------+------------+-----------+---------------------+---------------------+----------+-----------+------+----------------+
1 row in set (0.00 sec)
```

3. comments made on others' posts remain ( bug 1 ) : 
 
 ```
mysql> select * from comments where author_id='5';
+----+---------------------------+----------------+-----------+----------------------------------+---------------------+---------------------+-------------+------------------+
| id | text                      | commentable_id | author_id | guid                             | created_at          | updated_at          | likes_count | commentable_type |
+----+---------------------------+----------------+-----------+----------------------------------+---------------------+---------------------+-------------+------------------+
| 23 | public comment from user3 |              4 |         5 | e04158e091c301364f2d08002714e924 | 2018-09-03 16:25:20 | 2018-09-03 16:25:20 |           0 | Post             |
+----+---------------------------+----------------+-----------+----------------------------------+---------------------+---------------------+-------------+------------------+
1 row in set (0.00 sec)
```

4. likes on on others' posts  remain ( bug 2 ): 

```
mysql> select * from likes where author_id=5;
+----+----------+-----------+-----------+----------------------------------+---------------------+---------------------+-------------+
| id | positive | target_id | author_id | guid                             | created_at          | updated_at          | target_type |
+----+----------+-----------+-----------+----------------------------------+---------------------+---------------------+-------------+
|  6 |        1 |         4 |         5 | e23dfe6091c301364f2d08002714e924 | 2018-09-03 16:25:24 | 2018-09-03 16:25:24 | Post        |
+----+----------+-----------+-----------+----------------------------------+---------------------+---------------------+-------------+
1 row in set (0.01 sec)
```

**Comment by indyfractal** [comment] 2018-09-03 21:07
remediation : delete all comments from deleted accounts like so 

1. retrieve comments: check number

```
mysql> select count(*) from comments where author_id in ( select id from people where closed_account='1' ) ;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

2. delete comments : 

```
mysql> delete from comments where author_id in ( select id from people where closed_account='1' ) ;  
Query OK, 1 row affected (0.01 sec)
```
3. check again and confirm all comments have been deleted.

4. repeat for likes table : 

```
mysql> select count(*) from likes where author_id in ( select id from people where closed_account='1' ) ;   
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

mysql> 

```

5. delete all likes from deleted accounts : 

```
mysql> delete from likes where author_id in ( select id from people where closed_account='1' ) ;            
Query OK, 1 row affected (0.00 sec)

mysql> 
```

**Comment by denschub** [comment] 2018-09-04 03:01
Nothing is broken, it works as it is designed. The fact that comments and likes are not deleted is a design choice, and although this may not be ideal, there are bugs #6221 and #7848 for that. This makes this issue a duplicate of aforementioned issues.

**Closed by denschub** 2018-09-04 03:01 UTC
