### ISSUE TITLE
Camo breaks links

### ISSUE THREAD

**Issue by basxto** [diaspora/diaspora#7248] opened 2016-12-11 08:35 UTC
Camo does not detect all images and replace links instead, when you use exotic image syntax.

https://pod.geraspora.de/posts/a2b77820a1aa013422cb4860008dbc6c

**Comment by SansPseudoFix** [comment] 2016-12-11 09:01
Duplicate of #5608

**Comment by basxto** [comment] 2016-12-11 11:27
@SansPseudoFix: No, it’s not about the code block.
I just added it to show what I wrote.
The image on top isn’t camo’d.
Camo should not replace any links.

**Comment by basxto** [comment] 2016-12-11 11:29
I intended to link to https://openclipart.org/user-detail/Schade, which got replaced by camo

**Comment by SansPseudoFix** [comment] 2016-12-11 12:48
Oh, you're right, my bad (lack of coffee).
I tried ``#cc0 by [Schade](https://openclipart.org/user-detail/Schade)`` and no issue for me, on diaspora-fr.org.

**Comment by basxto** [comment] 2016-12-11 14:34
No, it’s because of the weird image syntax. I’m sorry, that I did not make that clear enough.

Minimal code to provoke that malbehavior would be:

    ![][1]
    
    [1]: https://openclipart.org/download/222469/1436605098.svg
    
    ](https://searx.me)

This variation for including images does not use round brackets. The camo-replacer probably sees it as a very long image tag.

---

Try the “Schade”-Link on my post https://diaspora-fr.org/posts/a2b77820a1aa013422cb4860008dbc6c

**Comment by basxto** [comment] 2016-12-11 14:59
https://github.com/diaspora/diaspora/blob/1fdc17d96cf5190a9e9ac069510c1985608a7a58/lib/diaspora/camo.rb#L6

This regex accepts images with multiline alternative text, also space between ] and (, which both does not get accepted by the markdown parser. `\s?` and `\m` are causing this afaik

It can’t detect `![][123abc]`/`[123abc]: url`-syntax for images, which I don’t think you can do with sole regex.

**Comment by Flaburgan** [comment] 2016-12-11 15:23
Why don't you write your example as `[![](https://openclipart.org/download/222469/1436605098.svg)](https://searx.me)`?

**Comment by basxto** [comment] 2016-12-11 15:49
@Flaburgan That is a) correct markdown and b) gets detected by camo

---

Camo can’t detect images of this format, which is valid markdown (for diaspora and github):

    ![][1]
    
    [1]: https://openclipart.org/download/222469/1436605098.svg

---

Camo detects this format, which is no valid markdown:

    ![
    
    ](https://openclipart.org/download/222469/1436605098.svg)

---

This results in replacing the link instead of the image in:

    ![][1]
    
    [1]: https://openclipart.org/download/222469/1436605098.svg
    
    [source](https://openclipart.org/detail/222469/rainbow-caticorn)

Which allows any user to bypass camo at will.

**Comment by denschub** [comment] 2016-12-11 16:33
Fallout and dupe of #6124.

**Closed by denschub** 2016-12-11 16:33 UTC
Labels: bug, post parsing
