### ISSUE TITLE
jump to comment position if you click on a notification-link (... also commented on...)

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6186] opened 2015-07-11 19:51 UTC
this is a feature-request.
could be done like on loom.io.

**Comment by Flaburgan** [comment] 2015-07-13 22:28
I mentioned this idea on https://github.com/diaspora/diaspora/issues/4425

**Comment by jaywink** [comment] 2015-07-15 20:56
Any object to closing #4425 in favour of leaving this specific issue open?

**Comment by jhass** [comment] 2015-07-15 20:58
#4425 still has an open point, the comments are pretty much irrelevant to its scope.

**Comment by svbergerem** [comment] 2015-07-20 00:26
This is a duplicate of #5203.

**Closed by svbergerem** 2015-07-20 00:26 UTC
Labels: feature
