### ISSUE TITLE
link to post from the photo view

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#6657] opened 2016-01-27 17:24 UTC
We have this "photos" tab, where we can see only photos user uploaded. when looking the exact photo, it's often good to have a link to the post, in order to know in which post that photo was used, to understand context better or read comments.

**Comment by svbergerem** [comment] 2016-01-27 17:26
Duplicate of #6236 which is an issue that you opened. :-P

**Closed by svbergerem** 2016-01-27 17:26 UTC
