### ISSUE TITLE
Sidekiq worker is leaking memory

### ISSUE THREAD

**Issue by diasp** [diaspora/diaspora#4599] opened 2013-11-21 22:43 UTC
I see that sidekiq memory is getting larger over the time until I restart the workers. Now 3 workers with 15 threads using approx. 15GB memory. Any ideas?

![sidekiq](https://f.cloud.github.com/assets/787572/1596586/2f0d8ae8-52ff-11e3-8441-6fb62a87b52e.png)

**Comment by heaven** [comment] 2015-11-17 06:55
I have just one process running with concurrency set to 5, 2 days and process growth from 200 to 425 MB, no jobs were running on this worker. Ruby 2.2.1.

**Comment by hendricius** [comment] 2015-11-18 08:58
Yeah. It's memory bloat. Not really memory leaks. Is there a way to tune this in the MRI GC?

**Comment by heaven** [comment] 2015-11-18 09:49
I haven't debugged it yet to see the number of allocated objects, could be caused by heap fragmentation. But the worker does not perform anything, no reason for such a heavy fragmentation. And it seems worse on ruby 2.2.1 than on 2.1.2 (default GC settings).

**Comment by hendricius** [comment] 2015-11-18 10:13
I would really like an expert to review this and give some suggestions. In 10 projects we have this issue. Our solution is to restart the processes once they reserve too much memory. Not the fault of sidekiq, nor any other library. Happens for us with puma/sidekiq and so on.

**Comment by heaven** [comment] 2015-11-19 03:23
Our production workers stopped growing after reaching 440MB.

@hendricius do you scrape web/download something? My guess is heap fragmentation, if you frequently allocate/deallocate big objects (e.g. long strings) you can suffer from the fragmentation a lot. After some time the memory heap looks like this: `||00||0||||00|||0||0|0||00|0||000|0|000|||00|00||||000`, where zeroes do mean free memory. So if you, for example, need to allocate this `|||||` amount of memory for a new object there's not a single contiguous chunk of this size available.

Java in this case can compact the heap by defragmenting it, but ruby only can perform GC to try to free the required block of memory and extend the heap allocating more memory if impossible.

Then, after you deallocated those big object, ruby can return memory back to the system, but only that free space at the end of the heap (the last `000` in the example above). Ideally ruby needs heap defragmentation, like Java has, but I don't believe we'll see something like that in the near future, unfortunately.

**Comment by denschub** [comment] 2016-03-31 12:42
Closing in favor of #6763.

**Closed by denschub** 2016-03-31 12:42 UTC
Labels: bug, needs more info
