### ISSUE TITLE
[Feature] Missing Group Feature

### ISSUE THREAD

**Issue by rusty-genius** [diaspora/diaspora#7786] opened 2018-04-13 12:49 UTC
After leaving Facebook I am really missing a group feature where I can connect with people on a certain topic and where I am completely private with them. I am not a programmer but I'd really like to see that feature.

Any chance for that?

**Comment by SuperTux88** [comment] 2018-04-13 12:59
Duplicate of #6278

**Closed by SuperTux88** 2018-04-13 12:59 UTC
