### ISSUE TITLE
Private message: Autocomplete doesn't work in catalan language

### ISSUE THREAD

**Issue by wiegelmann** [diaspora/diaspora#4760] opened 2014-02-02 07:41 UTC
I've got an issue report: When I what to send a private message I start to type the name of a contact and it doesn't autocomplete, so I can't select the contact. When I change the language to English and Spanish it works fine. But in Catalan language it doesn't. I've tried it in chrome and firefox (for linux).

![ejcfejcc](https://f.cloud.github.com/assets/6149471/2059848/cde68f46-8bdc-11e3-9f5f-b611835da62c.png)

**Comment by svbergerem** [comment] 2015-02-18 03:08
I tried this on the develop and master branch and wasn't able to reproduce the bug. @wiegelmann are you still able to reproduce this?

**Comment by svbergerem** [comment] 2015-05-03 14:43
No reaction for more than 2 months and I am still not able to reproduce this issue. I'll close this. Feel free to reopen whenever you are able to reproduce the bug.

**Closed by svbergerem** 2015-05-03 14:43 UTC
Labels: bug, i18n
