### ISSUE TITLE
Categorize posts by language

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#7667] opened 2017-11-21 12:03 UTC
How about making a tab with a list of languages u want to filter (aspect??) on your timeline. I am from Moldova and all I see is french and german posts. It's a big issues for Diaspora to get more popular.

**Comment by Globulle** [comment] 2017-11-21 13:11
I think this is a duplicate of #3513.

**Comment by Flaburgan** [comment] 2017-11-21 13:14
Agree.

**Closed by Flaburgan** 2017-11-21 13:14 UTC
