### ISSUE TITLE
Location preview shows wrong location in some situations

### ISSUE THREAD

**Issue by jaywink** [diaspora/diaspora#6442] opened 2015-09-30 20:12 UTC
Posted a message via DHQ, edited location to the Mozilla office in Paris and posted away. On my own pod, I see the preview as my home location.

Does the post get saved with coordinates that don't get overridden by the user edited location?

![selection_153](https://cloud.githubusercontent.com/assets/1174866/10205229/af2c11ba-67c8-11e5-95d3-87a48dda9018.png)

**Comment by svbergerem** [comment] 2015-09-30 20:23
Duplicate of #6440.

**Closed by svbergerem** 2015-09-30 20:23 UTC
