### ISSUE TITLE
user/edit not sending activation link when changing email

### ISSUE THREAD

**Issue by webbj74** [diaspora/diaspora#5577] opened 2015-01-18 23:19 UTC
I am experiencing this problem on https://joindiaspora.com/user/edit

On clicking "change email" after updating my email, I got an error page (don't recall exactly which). 

Presently the user/edit page has my new email address and the notice:

> We have sent you an activation link to newemail@example.com. Until you follow this link and activate the new address, we will continue to use your original address oldemail@example.com

However I have not received an activation email to either email address (checked spam folders).

If I re-click "change email" (expecting the link to be re-sent), I get an HTTP 500 error immediately.

I'm not sure if this is specific to joindiaspora.com...
##

**Comment by Flaburgan** [comment] 2015-01-24 10:01
Hey, it looks like we also have this problem on framasphere.org but it depends of the email provider: some works without any trouble, but for some other, mails are simply not sent. I'll ask the podmins to provide more information.

**Comment by jaywink** [comment] 2015-01-24 11:03
Doesn't sound like a problem in code - sounds like a problem in the way email sending is configured for the pod. The SMTP server (if such) could be rejecting the email, which is not the problem of diaspora. But good to investigate of course.

**Comment by svbergerem** [comment] 2015-05-03 14:53
> If I re-click "change email" (expecting the link to be re-sent), I get an HTTP 500 error immediately.

I'm not able to reproduce that. @Flaburgan Do you have any examples that could trigger this issue?

**Comment by Flaburgan** [comment] 2015-05-03 18:47
I'm not able to reproduce that too, no 500 running 0.4.1.3 on framasphere. But the validation e-mail isn't arrived.

**Comment by svbergerem** [comment] 2015-05-03 19:46
On my production pod I received a validation email. Are you able to find anything in the logfiles?

**Comment by Flaburgan** [comment] 2015-05-03 21:37
Yeah everything works fine on diaspora-fr too, this is probably related to the setup of framasphere.org. I'll have a look.

**Comment by polsVoice** [comment] 2015-07-29 18:06
I received the activation email, but when I copy and paste the URI into a browser, I get this error:
`Email could not be activated. Wrong link?`

**Comment by svbergerem** [comment] 2016-08-31 00:17
@Flaburgan Do you have any additional info? Has anyone else been able to reproduce this?

**Comment by Flaburgan** [comment] 2016-08-31 08:02
@SansPseudoFix did you recently have anything in Framasphere support related to e-mail activation link?

**Comment by SansPseudoFix** [comment] 2016-08-31 08:21
Seems not (since November though).

**Comment by svbergerem** [comment] 2016-12-05 01:02
Let's close this. We can reopen this issue if anyone is able to reproduce it.

**Closed by svbergerem** 2016-12-05 01:02 UTC
Labels: needs more info
