### ISSUE TITLE
Only load the gif images in the stream when the user wants to

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6251] opened 2015-07-26 09:16 UTC
This is for at least the mobile version, but I think the behavior would be nice on desktop too.
Gif images are really heavy, I think that we should preserve user bandwith by only loading the first image of the gif and then load the full gif if the user tap on it on the mobile version, or hover it on the desktop version.

**Comment by svbergerem** [comment] 2015-07-26 09:20
Duplicate of #5242.

**Closed by svbergerem** 2015-07-26 09:20 UTC
