### ISSUE TITLE
UI corrects birthday

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#7426] opened 2017-04-17 17:10 UTC
I think I didn't report this several times, but it's getting on my nerves XD

When I setup an non-human-account (like a bot or a shared account or an account for an organisation or something…) I'd like to setup the birthdate with the date the *whatever* was founded. Often that means "today" or "last year" or something like that.

Well, the UI usually does not allow this but the backend does!  When I cheat and I manipulate the request (or the formular befor I send the request) and set the year to 2017 for example, the server totally accepts this. And I would be fine with this, if not… well when I edit my profile later again this saved year is not represented in the form and if I change something and save the profile the information about the year just gets lost.

Sad! 👎 

I think there are several ways to fix this problem, the easiest would be to allow years from 1900 until today or even into the future (for fictional accounts). Another option would be to check what year is saved and if it's not in the dropdown-list add it or fill the list to this date. Or diaspora uses a date-picker and a checkbox "don't save the year" instead of three select elements. Or just a free text-input (or date-input with a text-fallback) that is parsed and "guessed" what date might be meant. Or a combination of these or something I didn't think about.

I just think the information I once saved serverside into the pod should not be overwritten just because I change my screenname.

**Comment by spixi** [comment] 2017-05-02 21:30
It is a very bad practise to do mandantory client-side validation of data which is not validated a second time in the backend, because you can and sometimes have to avoid such mechanisms with form or request manipulation to insert legit data.

In my opinion, it would be fine to show a warning instead of an error when a user inputs a valid, but suspicious date. I know that there are issues with the American children privacy protection laws, but those laws are in fact not applicable to all users. A warning would be a fine solution. If the community finds out that a user is not allowed to use d* w/o their parent's allowance, a podmin may be contacted to solve this issue. There are also no other protection mechanims so far (a 11 year old user, e. g. may insert a earlier date to pretend being over 13).

**Comment by denschub** [comment] 2017-05-03 20:20
Please check [this discussion](https://discourse.diasporafoundation.org/t/extension-of-year-of-birth-in-profile-from-2004-to-current-year/704?u=denschub), @DeusFigendi. Your podmin is able to raise the limit (or remote it entirely), that would also increase the amount of years available in the form. This renders the first part of your issue a dupe. Ask your podmin if they are willing to disable the limit.

Tracking for Org-profiles/fanpages is more or less done in #6447, so that part is a dupe as well.

And the "don't save the year" option feels like UI overhead. After all, the birth year is optional so you can decide if you don't want to provide that information. Since you worked around our UI, your "changes" are not intended so... bad for you, I guess. As it is possible to disable/lower the limit via an application config, this feels like a wontfix to me.

I feel adventurous today, so I'll just close this as a dupe of the aforementioned issues and discussions. If you feel strong about anything that's not considered by issues and tasks that already exist, we can reopen. However, in any case, this feels like somthing that should get a dedicated discussion on Discourse before.

**Closed by denschub** 2017-05-03 20:20 UTC
