### ISSUE TITLE
Mentions aren't visible in notification title

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#5641] opened 2015-02-09 12:22 UTC
The notifications have the first line of the connected post as a title. If a mention is in the first line of the connected post, the mention won't get shown in the title.

![bildschirmfoto vom 2015-02-09 13 16 11](https://cloud.githubusercontent.com/assets/828436/6106058/5a7b7344-b05e-11e4-8d48-e1eb90cec077.png)

**Comment by svbergerem** [comment] 2015-04-04 00:57
I'm not able to reproduce this anymore:

![post content](https://cloud.githubusercontent.com/assets/3798614/6990827/c340221c-da75-11e4-8025-3787f8da080c.png)

![notification](https://cloud.githubusercontent.com/assets/3798614/6990830/fcc9f3f0-da75-11e4-9d3c-8b05065c38f9.png)

I think #5730 or #5707 fixed this. I will close this issue. Feel free to reopen if you are able to reproduce this with 0.5.0.0.

**Closed by svbergerem** 2015-04-04 00:57 UTC
Labels: bug
