### ISSUE TITLE
Twitter post length/character limit doesn't account for URL shortening.

### ISSUE THREAD

**Issue by naught101** [diaspora/diaspora#6421] opened 2015-09-24 01:07 UTC
Twitter has a 140 character post limit, but all URLs are shortened to 15 characters, so the actual post length with a URL is much longer. Currently, if you write a ~120 character post with a long URL that takes it over 140 characters, the Diaspora post-length/character count underneath the post composition text area shows a negative number (indicating that twitter won't accept the post), but if you submit anyway, the post does get correctly submitted to Twitter. So the current behaviour is fine, just the "characters remaining" counter is incorrect.

**Comment by svbergerem** [comment] 2015-09-24 01:34
Duplicate of #5701.

**Closed by svbergerem** 2015-09-24 01:34 UTC
Labels: bug, ui

**Comment by naught101** [comment] 2015-09-24 01:39
Yeah, thanks. Missed that one because I used twitter in my search :( Ah well, at least this might be a useful signpost for others
