### ISSUE TITLE
Search bar triggeres a a request to load all contacts

### ISSUE THREAD

**Issue by denschub** [diaspora/diaspora#6787] opened 2016-04-07 05:37 UTC
Regression of #6293.

Due to [app/assets/javascripts/app/views/search_base_view.js:26](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/views/search_base_view.js#L26), a request to `/contacts.json` is made every time the search view gets initialized. Since this json contains literally all the users contacts, users with a large contact base can cause quite a huge amount of traffic and database load...

@svbergerem why is the prefetching needed here?

**Comment by denschub** [comment] 2016-04-07 05:47
I guess the request is made to fix #4789, but uh... This is really a bummer. :/

**Comment by Flaburgan** [comment] 2016-04-07 07:55
@denschub I guess as for https://github.com/diaspora/diaspora/issues/6107 we should first get only the user id, name and handle to be able to make the search, and then get all the info we need for the few contacts displayed.

**Comment by svbergerem** [comment] 2016-04-07 07:58
AFAIR we already fetched this before for mentions in the publisher and now we definitely fetch it for both mentions and the search bar. We could create a server side contacts search and use that for mentions. For the search bar we could improve the current search by also searching for contacts. Then we would also get rid of contacts.json there and we would really fix #4789. I already tried to implement the second fix but found out that one would need some experience with our database to fix that.

**Comment by AugierLe42e** [comment] 2016-08-09 19:14
As discussed on IRC, I don't think #6951 is a nice fix to this. Triggering a new query to the searver each time the user wants to mention someone has at least two flaws:

1. the mentionning system is going to get much slower than before #6951 and probably _really_ slow on pod with high traffics (JD, d-fr or Framasphere),
2. the mentionning system will fail if the server or client temporarily goes offline while the user is typing a message.

I really don't think the gain is worth it. The search bar and the mentionning dropdown should, at the very least, be fed with the contacts the user is sharing with (the mentionning dropdown actually doesn't need more). Gon, could be used to feed Bloodhound with the these contacts once and for all when the page is loaded.

**Comment by Flaburgan** [comment] 2016-08-09 22:24
I'm not sure about the perf here. I know my use case is not everybody's one, but I have thousands of contacts and each call to contacts.json take 6 seconds before the server's answer. So if we want to do the search client side, we need to keep the contact list in a cache, but we cannot continue to make a that intensive call to the server each time we refresh the page.

**Comment by denschub** [comment] 2016-08-10 02:53
I'm reopening this so we have something open as a reminder to think about this.

**Comment by AugierLe42e** [comment] 2016-08-10 06:31
> So if we want to do the search client side, we need to keep the contact list in a cache, but we cannot continue to make a that intensive call to the server each time we refresh the page.

Could we consider something like persisting the contacts list in a cookie?

**Comment by Flaburgan** [comment] 2016-08-10 10:02
>Could we consider something like persisting the contacts list in a cookie?

No need to put it in a cookie, we can activate the cache on `/contacts.json`. We would then answer with a 304 and the browser will use the cached version. If a modification to the contacts is done by the user we then invalid the cache.

>I'm reopening this so we have something open as a reminder to think about this.

I'm fine with keeping this issue open but the 0.6 milestone can be removed: I don't have calls to contacts.json anymore when I load /stream.

**Comment by SuperTux88** [comment] 2016-08-10 11:08
> the mentionning system is going to get much slower than before #6951 and probably really slow on pods with high traffics (JD, d-fr or Framasphere)

@AugierLe42e have you tested it already? On my dev-pod it works really fast, so I have no idea why you think its slow? Also, on already slow pods, it is better to only be slower when you try to mention someone, instead of being slow every time you load /stream...

I think we should close the issue again, because this is fixed. And we can open a new one, if we see that the new search request is slow or has other issues.

**Comment by AugierLe42e** [comment] 2016-08-10 11:31
> @AugierLe42e have you tested it already? On my dev-pod it works really fast

Nope. But no need to test to know that triggering an HTTP request is slower than searching locally ;)

> And we can open a new one, if we see that the new search request is slow or has other issues.

It's not only a question of speed:

> the mentionning system will fail if the server or client temporarily goes offline while the user is typing a message.
>
> Allowing the mentionning system to fail even if the page is fully loaded is a bad UX, IMHO

**Comment by SuperTux88** [comment] 2016-08-10 12:24
> Nope. But no need to test to know that triggering an HTTP request is slower than searching locally ;)

slower yes, but you sounded like "OMG, it is unusable slow now!" ... before this, the whole stream was "unusable" slow for people with many contacts, so it is definitively a improvement compared to before. Maybe it can be improved more, but for now I see this issue done. And if it really is too slow, we should create a new issue for this.

> the mentionning system will fail if the server or client temporarily goes offline while the user is typing a message.

the load of the stream will also fail, if the pod is offline, and sending the post will also fail, if the pod is offline ... many things fail if the pod is offline, so what is the advantage of mentioning a user if everything else breaks? And how often do you have the case, that the pod (or you) are only offline for 10 seconds exactly while you press `@`, and everything is online before and after this (to load the page and send the post)?

**Comment by AugierLe42e** [comment] 2016-08-10 12:29
> many things fail if the pod is offline, so what is the advantage of mentioning a user if everything else breaks?

The user can continue to write posts if the pod is offline. That should be the expected behaviour. That the user cannot interact with the pod when he goes offline is an expected behaviour. The he can't even properly write a post is not.

> And how often do you have the case, that the pod (or you) are only offline for 10 seconds exactly while you press @, and everything is online before and after this (to load the page and send the post)?

It's not only the post. The user hislef can also go offline. Actually, it happens to me regularly. And I don't expect the mentionning system to fail when my computer temporarily goes offline. If I don't, I suppose that lots of user less aware of how diaspora works won't expect either.

**Comment by AugierLe42e** [comment] 2016-08-10 12:37
I just open a specific issue for this discussion so that this one can be closed.

**Closed** 2016-08-10 12:52 UTC
Labels: regression
