### ISSUE TITLE
[Mobile] Clicking on right side of the screen activates a menu item

### ISSUE THREAD

**Issue by PolynomialDivision** [diaspora/diaspora#5696] opened 2015-02-21 09:01 UTC
Hi,

when I'm using Diaspora on my mobile (LG P880) with Fierfox for Android and I'm clicking somewhere on the right side of the screen I'm clicking on a menu item but the menu isn't open.
So when I'm clicking on the right side I go to settings or my activitys ...

**Comment by Flaburgan** [comment] 2015-02-21 09:29
Could you please tell me which version of Firefox for Android you are using?

**Comment by SansPseudoFix** [comment] 2015-02-21 09:39
Oh, indeed oO
Tried with Android 4.4.4 and Firefox 35.0 (with your web app @Flaburgan )

**Comment by Flaburgan** [comment] 2015-02-21 09:41
We have to review and merge https://github.com/diaspora/diaspora/pull/5556 I'm sure it can improve the situation.

**Comment by Polynomdivison** [comment] 2015-02-21 10:23
I'm using Firefox for Android 35.0.1

**Comment by AugierLe42e** [comment] 2015-08-11 08:53
I confirm this on Fennec F-droid (Firefox) 39.0.2 and not on [diaspora native webapp](https://github.com/martinchodev/Diaspora-Native-WebApp) (webkit-based).

**Comment by Flaburgan** [comment] 2015-08-11 10:51
I can't reproduce this with Firefox OS nor Galaxy S5 Android 4.4 Google Chrome. So this is Firefox for Android specific.

**Comment by jaywink** [comment] 2015-08-12 06:54
Can't reproduce Firefox for Android (on Jolla) 40.0. Tried:

iliketoast.net (0.5.99)
joindiaspora.com (0.5.2)

**Comment by svbergerem** [comment] 2016-06-29 18:35
@AugierLe42e, @SansPseudoFix Are you still able to reproduce this?

**Comment by AugierLe42e** [comment] 2016-06-30 13:35
Yes, I confirm I can reproduce on FF mobile 47.

**Comment by SansPseudoFix** [comment] 2016-06-30 13:57
Seems fixed for me. Tried with android 4.4.4 and FF 47, on diaspora-fr.org. I tried to click everywhere, and nothing.

**Comment by Flaburgan** [comment] 2016-10-12 11:08
@AugierLe42e can you still reproduce this? @SansPseudoFix says it's fixed for him. I guess you tried on diaspote.org so with https://github.com/diaspora/diaspora/pull/6233 already merged in but I want to confirm.

**Comment by AugierLe42e** [comment] 2016-10-13 17:30
Seems fixed.

**Comment by Flaburgan** [comment] 2016-10-13 21:49
Closing so.

**Closed by Flaburgan** 2016-10-13 21:49 UTC
Labels: bug, mobile
