### ISSUE TITLE
More-button of mobile views' public activities stream points to my activities stream

### ISSUE THREAD

**Issue by vanitasvitae** [diaspora/diaspora#6999] opened 2016-08-17 20:50 UTC
When I'm on mobile view at /public, scroll to the bottom of the stream and click the "more"-button, I end up at /activity?max_time=XXXXXXXX instead of /public?max_time=XXXXXXXX

Is this intended?

**Comment by vanitasvitae** [comment] 2016-08-17 20:52
PS: My pod is geraspora.de

**Comment by svbergerem** [comment] 2016-08-17 22:22
This might be a duplicate of #5037.

**Comment by denschub** [comment] 2016-08-25 04:23
Yeah, dope of #5037.

**Comment by denschub** [comment] 2016-08-25 04:23
Erm, dupe.

**Closed by denschub** 2016-08-25 04:23 UTC

**Comment by AugierLe42e** [comment] 2016-08-25 06:55
Dope is nice too :p

**Comment by vanitasvitae** [comment] 2016-08-25 09:58
Is this bug fixed in 0.6.0.0?

**Comment by svbergerem** [comment] 2016-08-25 15:24
@vanitasvitae No, this hasn't been fixed yet, but #5037 describes the same issue so there is no need to have a second open issue for the same bug.

**Comment by vanitasvitae** [comment] 2016-08-25 15:27
Okay, I just wanted to know. Thanks.
