### ISSUE TITLE
always show notifications dropdown on non-touch devices.

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7077] opened 2016-09-09 09:04 UTC
since 0.6, the layout changes when i split (aqua snap) my browser window to eighter right or left. Most of what changes is really good, the anoying thing to me is, that one no longer gets a dropdown menu when clicking on the notifications icon.
This is especially anoying because i used to do it that way so i can watch a video or listen to music in my stream, checking if there is a new notification and in case open it in a new window which i placed on the other side of the screen.
but now clicking on notifications will leave the stream and load a new page which causees all ongoing media playing as well as my "position" in the stream to break. and also i have the feeling that it takes a lot longer to load...
I see that this behauvior is resonable on a smartphone and maybe also on a tablet ( alltough i find that one arguable) - so my idea is to detect touchdevices and always use the dropdown notifications on non-touch devices.

**Comment by AugierLe42e** [comment] 2016-09-09 15:39
Are you using a tablet in landscape mode?

**Comment by paskalito** [comment] 2016-09-13 08:31
no i'm not using a tablet at all why?

**Comment by AugierLe42e** [comment] 2016-09-13 09:05
Because the way it is set up, the notification dropdown stops to be displayed at 992px width. So you must have a very tiny screen, or your pod's notification dropdown is broken :/

**Comment by paskalito** [comment] 2016-09-13 09:28
did you get the point that this is soley a problems when i split the browser window to hald screen ? or was that unclear?
![splitscreen](https://cloud.githubusercontent.com/assets/8012793/18468589/e7266400-79a4-11e6-839e-a1810891c7d6.png)

and my screensizes are 1600px widh and 1920px with and on my netbook which i not typically use 1360px.

but every half of these sizes is < 992px - so i loos the dropdown menu

**Comment by AugierLe42e** [comment] 2016-09-13 14:03
> did you get the point that this is soley a problems when i split the browser window to hald screen ? or was that unclear?

It was unclear ;)

**Comment by denschub** [comment] 2016-09-20 02:20
This is not a bug, but a design decision that was made. Dropdowns on touch screen enabled devices are a pain, which is why they get removed on the tablet version. Not sure if this is something we should change...

**Comment by jaywink** [comment] 2016-10-24 18:20
I was about to log this bug, or at least I think we're talking about the same thing. Since 0.6 I don't see if I have notifications on my phone any more which I'd say is a very serious regression. And yes, I want to use the full responsive view which works really well on a powerful phone, instead of the old mobile view which is missing lots of functionality.

When I took these screenshots I have two unread notifications.

Any chance of seeing notification counts again? Is this the right place or shall I log another issue?

![](http://storage7.static.itmages.com/i/16/1024/h_1477333007_6524660_e8576b5a43.png)
![](http://storage5.static.itmages.com/i/16/1024/h_1477332984_3080196_d0802a185e.png)

**Comment by denschub** [comment] 2016-10-24 18:35
> [...] I'd say is a very serious regression. And yes, I want to use the full responsive view which works really well on a powerful phone, instead of the old mobile view which is missing lots of functionality.

The mobile reason is there for a reason. We did not remove it because the full responsive is not ready yet. Use the old version or deal with the limitations the full responsive mode has, until it is finished. Using a feature that's not finished yet and ignoring a stable alternative that has been there for ages is your choice, that's not a regression.

**Comment by jaywink** [comment] 2016-10-24 18:44
Of course it is my choice. But it is a regression since 0.5 had the notification counts, whether you like it or not :)

Thanks for the friendly answer as always.

**Comment by denschub** [comment] 2016-10-24 18:48
> But it is a regression since 0.5 had the notification counts, whether you like it or not :)

0.5 did not provide a responsive design, you were presented with the desktop version. You can always do that nowadays, most browsers provide an option to virtually increase their viewport width.

> Thanks for the friendly answer as always.

You're welcome!

**Comment by paskalito** [comment] 2016-10-24 20:03
@jaywink 
hey no it's not the same thing. what i'm talking about affects useres only on desktop computers.

**Comment by denschub** [comment] 2016-10-24 20:05
It IS the same thing, since @jaywink decided to use the desktop version on his mobile device.

**Comment by jaywink** [comment] 2016-10-24 20:19
When you phone has more power than an average laptop, it just makes sense. Oh and the mobile view is missing half of the features.

**Comment by denschub** [comment] 2016-10-24 20:26
Which is exactly why there are [13 open feature requests](https://github.com/diaspora/diaspora/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Amobile%20label%3Afeature) tagged with mobile. However, this issue is titled "always show notifications dropdown on non-touch devices", not "people complain about how bad diasporas mobile experience is" (which it is). You already got your new post for that, and I don't see the point in having that discussed here.

**Comment by jaywink** [comment] 2016-10-24 20:39
I wasn't expressing an opinion of the mobile view but the full view that I can use by clicking "toggle mobile", on a mobile device. Which is exactly what this issue is about = screen size and how the full desktop view handles responsive layout. Just to clarify this in case you missed it.

Anyway, expressing opinions is forbidden I know. 😒

**Comment by Flaburgan** [comment] 2018-03-25 21:31
https://github.com/diaspora/diaspora/pull/7509 released with diaspora* 0.7.0.0 solved this problem: the notification icon and dropdown is always available in the responsive desktop version even with a 320px screen. Closing.

**Closed by Flaburgan** 2018-03-25 21:31 UTC
Labels: ui, undecided
