### ISSUE TITLE
[Mobile] Reshare count broken on streams

### ISSUE THREAD

**Issue by Makailija** [diaspora/diaspora#5693] opened 2015-02-20 11:12 UTC
On the mobile interface, the reshare count never shows the amount of reshares on streams. In the mobile "single post view", i.e. after clicking the timeago link, the amount of reshares is shown.

The same post on a stream:
![reshares-stream3](https://cloud.githubusercontent.com/assets/2229403/6285138/e267652e-b900-11e4-94ef-72d1890d3c33.png)
And in the single post view:
![reshares-spv](https://cloud.githubusercontent.com/assets/2229403/6285137/e265fb8a-b900-11e4-90a5-14458cb3aea6.png)

**Comment by visualsayed** [comment] 2015-03-13 16:49
It just work fine and I can't reproduce this issue!

**Comment by Makailija** [comment] 2015-03-14 10:03
Well, that's very strange... For me the problem appears both on Firefox and Chrome on Android and on Firefox and Chromium on Ubuntu. Neither 0.4.1.2 or develop is working for me. Can someone else confirm this?

**Comment by visualsayed** [comment] 2015-03-15 14:29
@Makailija 
Could you please send the steps you used to reporduce this issue?

**Comment by Makailija** [comment] 2015-03-15 15:10
1. Log in.
2. Change to the mobile interface, you are if not already in it.
3. On your stream (or on any stream, for that matter) scroll to any public post except your own that has likes or comments. (Only public posts can be reshared.)
4. Click on the "N reactions" link below the post. (If the post does not have likes or comments, you can't click on that link.) You will see that there the amount of reshares is not under the reshare icon, there is not even a zero. This is the incorrect behaviour, as shown on the first picture above.
5. Now, click on the timeago link of that same post. A "single post view" opens and below the post, you are able to see the amount of reshares under the reshare icon. If there are no reshares, a zero is shown. This is the correct behaviour, as shown on the second picture above.

**Comment by visualsayed** [comment] 2015-03-15 15:58
@Makailija, Thanks
Now, I'm able to reproduce this issue and I'll debug it soon.

**Comment by visualsayed** [comment] 2015-03-16 20:11
@Makailija  
It's now fixed.
@jhass 
Please check if it is ok. I think post_stats is duplicated in index.mobile.haml and _sream_elemnt.mobile.hamle.

**Comment by Makailija** [comment] 2015-03-17 08:16
@visualsayed Thank you very much!

**Closed** 2015-03-17 20:28 UTC
Labels: bug, mobile
