### ISSUE TITLE
What algorythm and salt is used for the user?

### ISSUE THREAD

**Issue by hersche** [diaspora/diaspora#7836] opened 2018-07-17 02:44 UTC
Hello,

i would like to be able to reproduce the hashes for a php-script, for make it using the same login.

sadly, i didn't found the way you generate the password nor the salt or nr of rounds in the config..

i checked the wiki, rudimentary the src and google..

it would may be nice to have a description about this in the wiki, under developer documentation.

thanks in advance for a answer and for create that project at all! :+1:

**Comment by Flaburgan** [comment] 2018-07-17 07:12
Hi @hersche and thanks for your interest for diaspora! I don't know how this part of diaspora works but I can tell you that the gem (a ruby library) "devise" is used to handle user log in and registration. Maybe have a look at their documentation.

Also for questions like this please use our forum at https://discourse.diasporafoundation.org 
Closing as this is not a diaspora bug.

**Closed by Flaburgan** 2018-07-17 07:12 UTC

**Comment by hersche** [comment] 2018-07-17 13:05
mh, the issue would be that it can be better documented, so it's simply clear.

thanks anyway for the answer, i will ask directly in diaspora.

**Comment by piraz** [comment] 2018-07-17 13:14
@hersche I was able to do that on python but it was necessary to change the session to json because rails use a serialization that is difficult to reproduce in another language.

Here is what I'm doing to share/create sessions in my python application:

https://github.com/candango/ddosso/blob/develop/ddosso/ruby_utils.py

**Comment by hersche** [comment] 2018-07-17 13:41
:+1: thank you both very much!

**Comment by jhass** [comment] 2018-07-17 14:10
User login has no interaction with federation at all.

Having it public is not super nice, yeah, but the risk is also not super huge. It basically brings us back to salted only level of security. The idea of the pepper is so that if an attacker gains DB access but not filesystem access, they still couldn't try a dictionary attack against a specific password. A rainbow table attack across multiple installations is still prevented by the salts.

Switching the pepper to a per installation based one would need a quite rock solid implementation for new installs vs. old installs and then still also create a moving part for admins that want to make a new setup with an existing database. Currently we have no generated secrets in our main config file and loosing the generated secret used for encrypting cookies just logs out all users, so minor damage. One obvious idea for using the same secret as pepper then would make loosing this fatal and I'm not sure it's really worth the aforementioned increase in security vs. the increased maintenance complexity given our goal of as many installations as possible.

**Comment by hersche** [comment] 2018-07-17 17:43
> Having it public is not super nice, yeah, but the risk is also not super huge.

i agree, it's a detail

> The idea of the pepper is so that if an attacker gains DB access but not filesystem access, they still couldn't try a dictionary attack against a specific password. A rainbow table attack across multiple installations is still prevented by the salts.

but i think this doesn't work, when the pepper is public. dictionary-attacks are possible this way, since you can simply attach the pepper.

> Switching the pepper to a per installation based one would need a quite rock solid implementation for new installs vs. old installs and then still also create a moving part for admins that want to make a new setup with an existing database. 

you are right there and i not plan to break anything :)

we had a similiar situation in youphptube. my ideas of how it can be solved:

- add only a commented line with a example-pepper and a small explain it should be changed from the start. if none is set in config, use the existing one like usual
- downwards-compatibility: good, that the pepper here is static for that case. in login-check, try to solve the the hash with the pepper in configuration. if it succed, simple login. if it fails, take the static pepper and compare. if the static succed, log in and show a message, the user should update it's password. 

i don't know the code yet, nor ruby really. so maybe this is difficult..
also, it may can be, that it open security-flaws, also when i don't see them. correct me if i am wrong

**Comment by jhass** [comment] 2018-07-17 18:33
> but i think this doesn't work, when the pepper is public. dictionary-attacks are possible this way, since you can simply attach the pepper.

Yeah, exactly my point. I was talking about the concept of a pepper in general :)

I'm really not sure it's worth the extra complexity, and my concern of having a secret that when lost, and tbh. probably is easily lost, requires at least all the users to reset their password if not locks them out completely, for little added benefit, stands.

**Comment by hersche** [comment] 2018-07-17 22:32
> I'm really not sure it's worth the extra complexity

i think longterm, it would be, since it realy increase of the security.

anyway, i can change it in my installation via source, and it's fine to me.. good to know it will not conflict with the federation.

thanks for your informations! :)
