### ISSUE TITLE
add new languages

### ISSUE THREAD

**Issue by norayr** [diaspora/diaspora#7810] opened 2018-05-14 15:28 UTC
Hello, firstly I would like to ask to add a new "language", because it looks like at webtranslateit this feature doesn't work, at least does not work for diaspora.

"language", because the language is actually the same - Armenian(Eastern), but significant number of our pod users use classical orthography, and I have a number of suggestions to add it. Also this orthography is used by Eastern Armenian speakers outside of Armenia, in particularly in Iran.

Secondly, we would also like to have Western Armenian language as well (ISO code 'hyw').

I suggest the  language options be marked in the language list for now just as Armenian(Eastern, Reformed orthography), Armenian(Eastern, Classical orthography), and Armenian(Western).

**Comment by goobertron** [comment] 2018-05-15 11:59
Hi @norayr, and thanks for suggesting this. I have asked the person who set up the translation system for Diaspora what will be the best way to do this.

Is there a more concise description for the two forms of Eastern Armenian? 'Armenian (Eastern, Reformed orthography)', 'Armenian (Eastern, Classical orthography)' are rather long, and might cause issues with the UI.

We will also have to find an ISO code for Eastern reformed orthography. I couldn't find one, and I don't know whether it's possible to invent a 'fake ISO code'. I will find this out.

It would be great if you and your fellow Armenian speakers would be willing also to translate [the project website](https://diasporafoundation.org/). Armenian doesn't seem to be included there at all at the moment. We handle issues about the website [in this separate repo](https://github.com/diaspora/diaspora-project-site/issues). If there is willingness to translate the site, I will also set up the three forms of Armenian on the [WebTranlateIt interface for the website](https://webtranslateit.com/en/projects/7017-website/) when I know how to do it.

**Comment by goobertron** [comment] 2018-05-16 13:45
Hi again @norayr, 

I now know how to create new languages for translation on Diaspora. Before proceeding further, I'd like to check something with you. We have identified three ISO codes for Armenian: `hy` (unspecified), `hye` (Eastern) and `hyw` (Western). It would be helpful from a practical point of view if we can use those three established codes, rather than having to 'invent' another for the third form you are requesting. As `hyw` is assigned to Western Armenian, `hy` would be assigned to one of the orthographies of Eastern Armenian, and `hye` to the other.

But `hy` will in some way be the 'parent' of the other two. This does not imply any greater importance of the form assigned to `hy`; it is purely a pragmatic, technical decision about which form would be the 'default' and 'fall-back'.

Which form is currently assigned `hy` (the form that is currently available in Diaspora's UI; see also [Armenian on WTI](https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..hy/strings))? Is there likely to be any controversy among Armenian speakers about continuing to use form as `hy`? If that is likely to be problematic, it should be possibly to reassign it without too much trouble.

It would not be evident to end-users in Diaspora's UI that any particular form has any heirarchy over the others; only to translators, as `hy` would be the fall-back used when `hye` or `hyw` have not specified a translation for a particular string. For that reason, it probably makes sense to assign `hy` to the form most commonly used by Diaspora's community.

If you could let me know which of the orthographies of Eastern Armenian would be most appropriate to be assigned `hy`, I will start to set things up in WTI.

In the Diaspora UI, we use 'native' names for languages (like հայերեն). If you would therefore supply these at some point. And if it's possible to make them shorter than Armenian (Eastern, Classical orthography)', I think it would fit better into We won't need them for WTI, so that can be done later, when they are ready to be added to Diaspora's UI.

**Comment by norayr** [comment] 2018-05-16 15:45
>Which form is currently assigned hy (the form that is currently available in Diaspora's UI;

this is Eastern Armenian with reformed orthography, the one which is by default used in the Republic of Armenia, and most of translations.

So I guess we can do this:

* leave hy version as is - it corresponds to հայերեն, as you mentioned.
* set up hye as հայերէն (one letter differs) - this means Armenian in classical orthography.
* set up hyw as հայերէն - looks the same in Western Armenian, as in Eastern with classical orthography, because Western Armenian only uses classical orthography.

oh, minute, then we won't be able to distinguish between Western Armenian and Eastern with classical.

So here I see two options, whether we should not use Western so far, it's not actually used on Diaspora yet, or:

* hy again stays as is, and looks like արեւելահայերեն (means Eastern Armenian)
* hye looks like արեւելահայերէն and from the word it's obvious it is written in classical orthography (one letter differs)
* hyw looks like արեւմտահայերէն (means Western Armenian, written in classical orthography)

I suggest we do like this.

P. S. when we were adding Armenian to Diaspora, it was necessary to set up some rules, I don't know how is it called, let's say how plurals are handled. These rules were extracted for most of the languages by using some site, automatically. I have added a request to add Armenian plural rules to that site, but there was no responce for years. And the developer told me that next time, if they try to extract those rules automatically, there will be no rules for Armenian. So, anyway, the same rules that are now coded in diaspora for plurals are legit for other two (hye and hyw) locales. Btw, I found the rules also here: https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html

**Comment by goobertron** [comment] 2018-05-16 18:34
Thank you! What you say makes complete sense. I will attempt to get this set up in the next 48 hours. Forgive me if it takes longer; it will be the first time I have done this, and I want to ensure I do everything correctly.

**Comment by norayr** [comment] 2018-05-16 19:58
we have nowhere to hurry, thank you for your efforts!

**Comment by ciubotaru** [comment] 2018-05-17 10:48
My five cents.

First of all, I don't speak Armenian and all my knowledge about it is based on a quick internet search. Armenian appears to be a pluricentric language, with two distinct literary forms. This makes it similar to  the Bosnian-Croatian-Montenegrin-Serbian language (ISO code 'hbs'), which has 4 (or maybe even more) distinct forms.

Currently diaspora treats 'hbs' as completely separate Bosnian ('bs') and Serbian ('sr') languages, none of which serves as a fallback for the other one. I suppose the same approach should be used for the Armenian language: treat Eastern ('hye') and Western Armenian ('hyw') as separate languages, without falling back to each other.

Orthography should be treated separately from language standard. If a literary form (in our case, Eastern Armenian) has two alternative and perfectly interchangeable ways of writing, it would make sense to use the more widespread (I guess, the current translation set) one as a fallback for the less spread.

**Comment by goobertron** [comment] 2018-05-17 15:39
> I suppose the same approach should be used for the Armenian language: treat Eastern ('hye') and Western Armenian ('hyw') as separate languages, without falling back to each other.

It's really a pragmatic decision; if (almost) all strings will be different between Western and Eastern Armenian, or if phrases in one of them will be not particularly comprehensible to a speaker of the other form, it would not make much sense to use one as a fall-back for the other. If, on the other hand, many strings would be the same in both forms, or if a fall-back would be very easily understood, it makes sense to use one as a fall-back for the other. It would certainly make more sense than using English as a fall-back.

**Comment by goobertron** [comment] 2018-05-17 20:04
Right, things are almost set up.

The only issue we have on WebTranslateIt is that it is not possible to edit the names of languages. To save any possible confusion by having one language called 'Armenian' for Eastern, reformed orthography and another called 'Armenian (Eastern)' for Eastern, classical orthgraphy, I suggest the following:

We change `hy` to `hye` with the name 'Armenian (Eastern)' and create a sub-language with the code `hye-classical` and the name 'Armenian (Eastern), classical orthography'.

@norayr will this work for you and other Armenian translators?

@jhass has agreed that this is probably the best solution. However, it will mean that, once there has been a locale pull from WTI, the next software update would have to include a migration to `hye` of all users with language set to `hy`. I therefore want to check with @SuperTux88, @Flaburgan and @denschub (if he's available) that there are no objections to doing this, and that no one foresees problems in doing it.

Once I've heard from you all (and anyone else with a view), I'll set up the languages in WTI as appropriate, and let @norayr know when it's safe to proceed with adding translations to the new locales.

The names of the languages in Diaspora itself are not affected by this limitation, and will be արեւելահայերեն, արեւելահայերէն and արեւմտահայերէն as suggested above.

**Comment by norayr** [comment] 2018-05-17 22:47
i don't understand how the fallback works.
when does the fallback happen?
if I set to one language, and diaspora source is problematic, so it does not work, and exception is thrown, then the fallback languase is used?

>if (almost) all strings will be different between Western and Eastern Armenian, 
it is hard to say what amount of strings will differ. may be most one word strings will be the same, i guess most of the strings with more than one word will differ.
one of the differences between western and eastern is in pronunciation(same letters are pronounced differently), which is not reflected in text(in case of classical orthography).

>or if phrases in one of them will be not particularly comprehensible to a speaker of the other form

we understand each other intuitively, even without knowing how the morphological rules differ.
there are very rare occasions, when we need to clarify what the other wanted to say.
kids in schools have to read literature written both in western and eastern languages, though the de facto language in armenia is eastern. it is, by the way not fixed by the law, the law says that the official language is 'armenian', without any details.

so yes, if i understand what is fallback correctly, if for some reason eastern armenian translation does not work, suggesting a western armenian translation instead will be better than suggesting english translation, and vice versa.

in eastern, reformed orthography is de facto standard within armenia (but significant number of local diaspora pod users use classical), and de facto standard outside of armenia is classical.
so classical can be fallback for reformed, and vice versa.
and western can be fallback for eastern and vice versa.
still better than falling to english.

**Comment by norayr** [comment] 2018-05-17 22:55
>We change hy to hye with the name 'Armenian (Eastern)' and create a sub-language with the code hye-classical and the name 'Armenian (Eastern), classical orthography'.

Probably. I don't see the better solution, if the webtranslateit has this limitation.
I hope this rename won't cause inconsistencies between webtranslateit and diaspora source code.

If what may impact users is that after some upgrade they might need to set the language again, I'll inform them.

**Comment by norayr** [comment] 2018-05-17 22:58
and thank you for your efforts.

**Comment by goobertron** [comment] 2018-05-17 23:14
@norayr:

> i don't understand how the fallback works.

Fall-back simply means which translation (locale) will be used if a string has not been translated in the locale being used. This means that our Armenian translation team will not have to write new translations for every string in the UI; only strings that differ from `hye` will need to be provided.

I don't know any Armenian so won't give an example for that, but for instance, if I were to prepare a British English locale (something I've been meaning to do for ages), I would only have to write something when the string differed from American English (used in the `en` locale, which would be the fall-back for `en-GB`) So I wouldn't have to translate 'Hello' for `en-GB`, because it is the same as in `en`, but I would provide a translation for 'What is your favourite colour?', because in `en` that would be 'What is your favorite color?'

It is there as a means of avoiding unnecessary duplication; also, if one locale has not been fully updated when new strings have been added to the UI, it will attempt to find a match for that string in the 'fall-back' locale, and so hopefully be able to provide text comprehensible to the user until the locale they have chosen has been updated.

> I hope this rename won't cause inconsistencies between webtranslateit and diaspora source code.

It won't. Diaspora's translations are pulled in from WebTranslateIt; the only difference will be the language names in the UI (given in English in WTI, but in native language in Diaspora).

> If what may impact users is that after some upgrade they might need to set the language again, I'll inform them.

That shouldn't happen. The proposal is that there will be a migration which will automatically update all users' accounts to use `hye` instead of `hy` when their pod is updated to the next software version.

> and thank you for your efforts.

You're welcome. It will be good to make Diaspora feel like 'home' to more people!

**Comment by norayr** [comment] 2018-05-17 23:27
ok, so we already have almost fully translated eastern armenian with reformed orthography.

and we'll sync eastern armenian classical to reformed, with just orthographical changes.
that we can do very fast, i believe. and we'll keep them synced.

then we need to find people who not only know western armenian, but also are willing to contribute.
this is not the task which will be accomplished tomorrow, i read and understand western, but i don't feel confident in how should the sentence in western be constructed, same is for other current translators.
so it won't harm if western will fall to eastern.

p. s. adding british english translation looks like a very good idea to me.

**Comment by goobertron** [comment] 2018-05-18 10:12
That is fine; I did not mean to imply that it would be the duty of the existing translators to provide a locale in Western Armenian. But that option will now be available for speakers of Western Armenian who wish to add translations in the future.

**Comment by goobertron** [comment] 2018-06-01 15:23
Hi again, @norayr. Everything is now set up for you. I'm sorry for the delay; other things took priority and I wanted to make sure that everything was set up properly before letting you know.

There are now three locales for Armenian on WebTranslateIt:
– the existing one, now renamed [Armenian (Eastern)](https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..hye/strings) with the code `hye`;
– [Armenian (Eastern) classical orthography](https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..hye-classical/strings) with the code 'hye-classical`;
– [Armenian (Western)](https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..hyw/strings) with the code `hyw`.

`hye-classical` and `hyw` will each take their 'inheritance' from the existing `hye`. This means that you will only need to supply translations for those new two locales where the translation differs from that in the existing `hye`. There is no way to note this fact in WTI, so would you mind letting your co-translators know this? It could save them a lot of work, depending on how different the variants of the language are from each other.

The person who runs WTI has confirmed that pluralisation rules have been set up correctly for all Armenian variants.

I have also added the new locales to the Diaspora locales list so that they can be added to the Diaspora UI when translations have been provided for them. I'll make a PR for this now so that it's ready to be merged when it is needed.

**Comment by norayr** [comment] 2018-06-08 12:39
thank you so much.
i requested invitation for armenian eastern (classical) and armenian western translations.

**Comment by norayr** [comment] 2018-06-08 13:30
ok, I have installed wti.
I would like to sync hye translations to hye-classical first, then upload them for all to edit.

As I understand this is the easiest way to pull hye, pull hye-classical, copy hye files to hye-classical, and then push hye-classical.

I have created ~/.wti file but it requires project API key.
How can I get one? Or should I?

**Comment by goobertron** [comment] 2018-06-08 16:33
Hi @norayr.

The different languages are not linked or 'synched' on WebTranslateIt (WTI) in the way you mention. We therefore don't want to migrate strings from one locale to another on that platform. If a string is the same in `hye-classical` as it is in `hye`, it should be left blank in `hye-classical`. Diaspora will then default to using the string from `hye`. The reason for doing that is that when a string is updated, you don't have the problem of outdated translations remaining in `hye-classical`. See, 

If you want to work on translations locally, the easiest way would be to pull the following files from this Github repo:

https://github.com/diaspora/diaspora/blob/develop/config/locales/diaspora/hy.yml
https://github.com/diaspora/diaspora/blob/develop/config/locales/devise/devise.hy.yml
https://github.com/diaspora/diaspora/blob/develop/config/locales/javascript/javascript.hy.yml

(Note: these will each be renamed `hye.yml` during the next software update.)

Or you could just copy the text from those links and paste the text into a text editor.

Then go through each string, and remove the text from any string where it is the same as `hye`. If it the text should be different in the new locale, edit it.

Then paste that newly translated string into the relevant line of https://webtranslateit.com/en/projects/3020-Diaspora/locales/en..hye-classical/strings

I could not recommend creating new `hye-classical.yml` files locally on that machine and then doing a pull request via Github. If we did that, it would over-ride any changes made by anyone else in WTI, and I notice that a few strings have already been added in WTI. As you're currently the only translator registered on WTI for `hye-classical` and `hyw`, I'll ask @jhass and @SuperTux88 whether they would consider accepting the first translation for those two locales as a Github pull request, which could then be pushed to WTI. I suspect this would cause difficulties, so the only way to do it would be manually to paste your fresh translations for those two new locales into the relevant fields in WTI.

Hopefully there will not be too many strings in those two new locales where fresh translations will be needed!

**Comment by norayr** [comment] 2018-06-09 08:29
no I don't want to cause difficulties.

just it'll be very easy for me to prepare hy-classical by having hye and running a classical spell checker on it. because there's no language difference, only the orthography.
so right now in the web interface, I need to open two tabs, see the hy eastern translation, copy paste it to hye-classical, then change the orthography.
if it were already there, in the window, it would be more convenient, just to right click on the word and choose the right correction, suggested by the spell checker.
and even more, if it were a local file, it would be even more convenient, because the browser works slower than local text editor.

but that's okay, i don't want to make anyone else feel uncomfortable.
and i am ready to carry on with the work in the browser.

with western everything is more complicated, i don't know it well enough, so most probably i won't touch it for now.

**Comment by goobertron** [comment] 2018-06-09 10:43
OK, so I recommend the following:

1. Copy the text from the files I linked in my previous comment, and pasting them into three separate documents.
2. Save two copies of each (one set called `hye.yml` and the other `hye-classical.yml`).
3. Then run the spell-checker on the three `hye-classical.yml` documents. (Please also check translations manually; don't rely only on a spell-checker.)
4. Save the edited files, then run a 'diff checker' on each of the `hye.yml` and `hye-classical.yml` files to highlight where there are differences.
5. You can then copy those strings highlighted as changed and paste them in to the relevant field of `hye-classical` in WTI.

I'm not sure which OS you use, but you should be able to find an app to download that will highlight differences between two files, if you don't have the capability in your OS. Some word-processors do it, and that might be enough.

**Comment by norayr** [comment] 2018-06-10 14:09
yes yes, i use funtoo, should be able to do this.
thank you! we can close the issue probably. (:

**Comment by goobertron** [comment] 2018-06-16 19:15
That's great news! @norayr, if you're happy that this has been completed, you can close the issue to save waiting for an admin to see it.

**Comment by SuperTux88** [comment] 2018-06-16 19:51
I close this, since #7822 is now merged. The translation can happen in WebTranslateIt now.

**Closed by SuperTux88** 2018-06-16 19:51 UTC
Labels: i18n
