### ISSUE TITLE
[New feature] Having an option to hide your profile picture to the public.

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#7058] opened 2016-09-04 20:08 UTC
The profile picture of each user is stored by Google and can be seen by unwanted people. This can be extremely critical for the privacy of some people.
A good chance to protect that privacy is that the user has an option to hide your profile picture to the public and that only they can see who their friends within the social network. Thus, google also can store the image. I think it's a feature important to develop vital.

**Comment by svbergerem** [comment] 2016-09-04 20:13
Duplicate of #4330.

**Closed by svbergerem** 2016-09-04 20:13 UTC
