### ISSUE TITLE
Previewed post gets hidden after sharing (0.5.0.0)

### ISSUE THREAD

**Issue by Selena-Gomez** [diaspora/diaspora#5927] opened 2015-05-05 06:11 UTC
When posting, if you use the preview feature and then finish it by sharing you'll see that the preview gets pulled back up and hidden, and the finished post is not shown until you perform a refresh.

**Comment by svbergerem** [comment] 2015-05-05 06:43
This is probably a duplicate of #5275. @Selena-Gomez could you check that?

**Comment by Selena-Gomez** [comment] 2015-05-05 06:52
Ah, yes it is, I hadn't noticed that the post ends up at the bottom.
Here's a .gif for anyone else that might have noticed this as well.
![diaspora_bug](https://cloud.githubusercontent.com/assets/1886075/7468057/f1466a32-f2c0-11e4-9c88-b67bcd307bd1.gif)

**Comment by svbergerem** [comment] 2015-05-05 06:54
Alright, thank you!

**Closed by svbergerem** 2015-05-05 06:54 UTC
