### ISSUE TITLE
User should be able to mention other users in comments

### ISSUE THREAD

**Issue by StepMiller** [diaspora/diaspora#1851] opened 2011-08-30 18:57 UTC
You can't mention anyone in a comment.
It's really  curious: If you write for example

@`tester@joindiaspora.com`

it will be transformed to a link -> `http://tester@joindiaspora.com/` with an @ in front of it...
##

**Comment by cmrd-senya** [comment] 2015-07-28 18:31
If nobody minds, I'd like to work on this one.

**Comment by jaywink** [comment] 2015-07-28 19:23
That would be awesome @cmrd-senya , thanks!

**Comment by goobertron** [comment] 2015-07-28 19:26
I don't think anyone would mind that at all! Thank you.

**Comment by Flaburgan** [comment] 2015-07-28 20:48
You're very welcome to do it! There are couple of things to consider though, I discussed with @jhass about it a long time ago, I think the first step would be to write specifications because this is a non-trivial feature (choices have to be made).

**Comment by jaywink** [comment] 2015-07-29 06:43
@Flaburgan unless you mean pure technical details then the high level spec was already decided on [here](https://github.com/diaspora/diaspora/issues/1851#issuecomment-36557842) :dancer:

**Comment by cmrd-senya** [comment] 2015-08-06 16:11
I'm leaving for three weeks and I won't be able to work on it for a while. If the issue is not solved by the time I'm back by someone else I'll continue.

**Comment by Flaburgan** [comment] 2015-08-09 21:10
@jaywink I remember a discussion with @jhass a long time ago where he told me that it will be difficult (impossible?) to send notification to non-contact. The notification is, imo, the most important part of the mention (the link to the profile is not why I use notification). So I guess https://github.com/diaspora/diaspora/issues/5522 has to be solved first. There is also https://github.com/diaspora/diaspora/issues/4491 which is not a blocker, but which is going to be worse if not solved before this.

**Comment by jaywink** [comment] 2015-08-10 08:03
@Flaburgan 

> it will be difficult (impossible?) to send notification to non-contact.

Nothing is impossible when it comes to writing code ;) Bend the code to your will, not your will to the code!

It's possible something has to be done on the receiver end if the users are not connected or profile is not found on remote, but you can't say it is impossible - the relevant paths just need to be looked at and triggers fired to make sure a notification is created for the mentioned user.

**Comment by pavi** [comment] 2015-08-11 20:06
Its a nice feature to have. :+1:

**Comment by cirosantilli** [comment] 2016-02-16 10:32
+1

**Comment by pravi** [comment] 2016-03-17 06:06
@cmrd-senya has added this issue as a stretch goal to his account backup/restore crowd funding https://www.indiegogo.com/projects/account-backup-and-restore-for-diaspora--3#/ He will work on this if he reaches 4200 €, he'll work on this.

**Comment by Bugsbane** [comment] 2016-04-17 00:59
...which he reached. He's been working dilligently on the main goal for the campaign (pod migration) but recently said in an update that he'd be looking at the other issues soon, so fingers crossed for some work on this! :dancers:

**Comment by Flaburgan** [comment] 2016-11-30 14:56
For your information, #6818 has been merged. There is still the interface to write but this feature will definitely be part of the next major release. Thank you @cmrd-senya!

**Comment by cmrd-senya** [comment] 2016-12-02 16:31
@AugierLe42e, so are you planning to work on UI? I'm fine with doing it myself, but @Flaburgan told me on IRC that you want to make it.

**Comment by AugierLe42e** [comment] 2016-12-02 19:59
Let's work on this together, what you think?

**Comment by cmrd-senya** [comment] 2016-12-03 10:30
Alright, let's meet on IRC then ;)

**Comment by cmrd-senya** [comment] 2016-12-09 22:38
I started to work on a controller action for mentionables at #7242. I move the description I wrote there to this issue, since it looks like people don't like to look inside the [wip] pull requests. Sorry for this cross-posting, on the second thought it seems that this place fits better to keep the discussion going.

Before I can continue work on this PR I'd like to discuss a few points.

At #6818 we made a decision on who is mentionable at what cases. Here is what we decided:
1) In comments for public posts we can mention anyone. We don't filter out non-contacts, because we can't do it technically.
2) In comments for private posts we can mention only commenters and likers of the post, and author.

Later we had a discussion on IRC with @SuperTux88 and @AugierLe42e, where we discussed what we should show to users in comments publisher.

I'm convinced, that the way backend and frontend work should be consistent. That's why in #7242 I refactored the `Comment#people_allowed_to_be_mentioned` method to the `Person.allowed_to_be_mentioned_in_a_comment_to` scope, which can be used both for the backend part to [filter out notifications](https://github.com/diaspora/diaspora/compare/develop...cmrd-senya:mentionable-route?expand=1#diff-eebd27939abf90e47e09e0113e79cd85R14) and in [the controller to get the list of people to show](https://github.com/diaspora/diaspora/compare/develop...cmrd-senya:mentionable-route?expand=1#diff-ab4e9273f7df75aa5004a42f757d6f51R57). Thus we use the same SQL to query these people. 

Of course, we can add extra conditions to limit the list of who we show in the publisher.

But here are some points I want to clarify.
1) Do we propose likers as well as commenters in publisher? If we don't then I guess we shouldn't allow likers to be notified of a mention as well.
2) Do we show non-contacts in publisher for public posts? We don't do that for posts. But actually why? What is wrong in mentioning non-contact? I'm fine with doing a sorting so that contacts are at the top of list, but why should we exclude non-contact people at all? If we provide a possibility to mention a non-contact (and we can't really filter out non-contacts) why shouldn't we show them in the publisher?

If we have a difference between our mention notification recipients and people who we propose in publisher, then we'll force people to use the markdown syntax `@{; }` to mention non-contacts which is hackish and inconvinient.

**Comment by SuperTux88** [comment] 2016-12-18 16:20
I just write here what I also mentioned in IRC:

I think the suggestions in the frontend should be ordered (then we can also add non-contacts).

For public posts that would be:
post-author -> comment-authors -> (like-authors? does that make sense for public posts?) -> contacts -> non-contacts (only where searchable == true)

For private posts that would be:
post-author -> comment-authors -> like-authors

I also think that for mention in comments there should already be a suggestion even with only typing the "@" (post-author and last few comment-authors). Optimally that is even possible without asking the backend, because we have all information already in the frontend.

**Comment by cmrd-senya** [comment] 2016-12-18 16:46
I generally agree with your points. Here are some specific thoughts:

> Optimally that is even possible without asking the backend, because we have all information already in the frontend.

The mention implementation at the frontend assumes that it gets mentionable people list by a query to a controller action (ContactsController#index for posts). Since we want to reuse this code, we'll need another controller action, and that is what I've started to implement at #7242. To implement it in some different manner (e.g. building a list from the data provided by gon) would mean a refactoring of the frontend mentions implementation, which is a longer way (and are there any issues with the current approach with fetching mentionable people?).

> I also think that for mention in comments there should already be a suggestion even with only typing the "@" (post-author and last few comment-authors).

Again, if should be done, perhaps, it should be modified both for mentions in posts and mentions in comments. Are there any reasons for publisher to behave different there for posts and comments?

So changing the way the frontend gets the list of people to suggest and the way it initiates the suggestion is out of scope of this issue, but if we have strong reasons to change the way it is implemented, we should do that before, because it'll be harded to change when we write more dependent code.

**Comment by SuperTux88** [comment] 2016-12-18 17:13
> are there any issues with the current approach with fetching mentionable people?

No, but it would be much faster to just display what we already have and with only typing the "@" there aren't even parameters to filter. But I said, that would be the optimal way, if that isn't possible then ask the backend ... but I think that is only needed when we need to search the database (filter on a big amount of comment-authors, filter contacts/non-contacts). Until now that was always the case (because for posts you need to filter contacts from the database), and I think now is probably a good time to change that? So my suggestion is: If you only type the "@" -> display what you already have (author and last few comment-authors), and if you type 2 or more characters -> ask the backend to search in the database.

> Are there any reasons for publisher to behave different there for posts and comments?

Yes, because for comments we have a useful amount of people to display with only typing the "@". But what would you display with only typing the "@" on a post?

I wouldn't change much for mentions in posts (only maybe add non-contacts, if contacts have a higher priority), but this issue is about mentions in comments, so I wrote what I think is useful for that use-case.

**Comment by cmrd-senya** [comment] 2017-01-13 03:17
Ok, now when #7242 is merged, the way for UI is clear.

**Comment by cmrd-senya** [comment] 2017-03-23 01:51
A thought came to me about "mentionable people" in comments to private post. Now it is implemented so that in a comment to private post we can mention only participants (commenters and likers). But I see another usecase: what if you are a private post author, and you forgot to mention someone in the post, or you decided to call some to join the discussion. Why can't you mention your contact? Since you're the post author, we have all the information to send a mention in comment notification to some of your contacts. I mostly talk about the case, when your post has that person in original recipients. 

So I propose to add a rule: if you're a private post author, you're allowed to mention in a comment any member of target aspects of this post.

Actually I think it could be also possible to allow the author to mention this way people, who aren't members of the target aspects. This would imply that when the mentioning comment is posted, the post and the comment is pushed to the mentioned person.

**Comment by goobertron** [comment] 2017-03-23 04:56
Ah, that's a good point. When I created the Loomio proposal on which this decision was taken, I was thinking about 'commenters' as being the people who were interacting on the post other than the post's creator. I therefore missed out the obvious point that the post's creator knows who can see the post and therefore can usefully mention them even if they have not yet participated in the post. That was my omission and my fault.

I support the proposed addition:

> if you're a private post author, you're allowed to mention in a comment any member of target aspects of this post.

Whether this needs a new Loomio vote, I'm not sure. I think it would probably be a good idea, because a decision was already made through a vote, although I doubt it would be a controversial addition.

Thanks!

**Comment by goobertron** [comment] 2017-03-23 04:59
However, this:

> Actually I think it could be also possible to allow the author to mention this way people, who aren't members of the target aspects. This would imply that when the mentioning comment is posted, the post and the comment is pushed to the mentioned person.

is different. Not technically, but in terms of how the network works. There was a conscious decision not to allow a widening of the scope of readership of a post after it has been created, for various reasons, including so that people who have commented on a post in the understanding that it is limited to a certain readership don't later find that a wider readership can now see their comments. This proposal would enable this, albeit on a small scale (individually mentioned people). I'm not sure the usefulness of this feature would outweigh possible negative consequences.

**Comment by cmrd-senya** [comment] 2017-03-23 23:44
So since #7386 is merged, do we close this one? Or should we implement another liitle change before, which I described in my previous comment in the topic?

**Comment by svbergerem** [comment] 2017-03-23 23:50
I'll close this since the feature has been implemented as decided here: https://discourse.diasporafoundation.org/t/mention-users-in-comment/177/23

For additional changes we can open new PRs/issues.

**Closed by svbergerem** 2017-03-23 23:50 UTC
Labels: bounty, feature

**Comment by SuperTux88** [comment] 2017-03-24 00:15
I think it's OK how it is now, because we still have the problem, that we don't know who can see the post, only which aspects were selected when creating it (so right after posting it is the same, but not after you changed some aspect-memberships). So I think we should first fix that, and then can discuss again if we want to enable it for post-authors.

> Actually I think it could be also possible to allow the author to mention this way people, who aren't members of the target aspects. This would imply that when the mentioning comment is posted, the post and the comment is pushed to the mentioned person.

This is a completely different topic and should have it's own discussion. Personally I think it's ok (as long as the post stays private, so no change privayte -> public). Because the receivers of the post only see that it is private, not how many people can see it (could be only you and the author, could be "all aspects" of the author). So it doesn't make a difference as reader, if the author adds a person after they posted it.

But again, out of scope for mentions and probably also only possible after fixing the problem above, because we can't track single-person targets currently. But you can create an issue for that if you like :)
