### ISSUE TITLE
Bootstrap modal-backdrop doesn't disappear after creating a new aspect

### ISSUE THREAD

**Issue by TheMadKhajit** [diaspora/diaspora#6562] opened 2015-11-27 10:41 UTC
This happens at random, but i have been able to reproduce it so many times..it basically halts progress because once modal-backdrop appear i am not able to click on anything except for the nav bar items.
I think the problem is somewhere inside the "sync" callback `app/assets/javascripts/app/views/aspect_create_view.js`.

**Comment by jaywink** [comment] 2015-11-27 10:48
Saw this yesterday on my pod too, running (almost) latest dev code. Thanks for supplying a fix!

**Comment by deXterbed** [comment] 2015-12-11 11:07
@jhass thoughts?

**Comment by svbergerem** [comment] 2015-12-20 15:53
@deXterbed You already mentioned that it might have something to do with the [aspects create view](https://github.com/diaspora/diaspora/blob/c62927b/app/assets/javascripts/app/views/aspect_create_view.js#L41-L63). I wasn't able to reproduce this yet. Our code closes the modal when the aspect we would like to create receives a `sync` or `error` event.

Is it just the backdrop or also the modal that doesn't disappear? Since we use the Bootstrap function to close the modal it should also remove the backdrop.

If it is only the backdrop which doesn't disappear it might be a Bootstrap bug or there might be something in your error console. In that case you should also see a flash message saying either that the aspect has been successfully created or there was an error creating the aspect.

In the other case there might be something wrong with our Backbone code and we would have to find out if there is maybe a case where neither the `sync` nor the `error` event is fired.

**Comment by denschub** [comment] 2016-03-02 19:32
Piiiing!

**Comment by deXterbed** [comment] 2016-03-02 22:00
@svbergerem thanks for looking into this, i didn't see any flash message or error it's just the backdrop and it won't let me click anywhere on the page, do we really need a backdrop here?

**Comment by svbergerem** [comment] 2016-03-02 22:38
> do we really need a backdrop here?

I like it. The backdrop helps me to focus on the modal.

> i didn't see any flash message or error it's just the backdrop

No flash message would mean that neither a `sync` nor an `error` event has been fired or that there has been an error somewhere in our code before we were able to show the flash message. If the aspect creation has been successful we should also reload the page. Are you sure that there is nothing in your js error console?

**Comment by deXterbed** [comment] 2016-03-02 22:40
@svbergerem i'll check the js console again and post the result

**Comment by cmrd-senya** [comment] 2016-07-11 07:55
I caught the issue many times while working on #6864. It happens because of a race condition -- that's why it's not easy to reproduce. It may happen that the backbone view gets reloaded and the aspect create callback is called only after the reload. In this case, modal doesn't disappear, because the modal node is not on DOM anymore.

I think I got rid of the issue in my PR, but it's [WIP], so I'll have to retest it once it's finished, but for now I think the issue will be fixed with the #6864.

**Comment by svbergerem** [comment] 2016-08-08 15:34
Fixed by #6864.

**Closed by svbergerem** 2016-08-08 15:34 UTC
Labels: bug, needs more info
