### ISSUE TITLE
Create a new aspect from the aspect dropdown fails

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#4913] opened 2014-04-06 19:18 UTC
The facebox doesn't appear and you get immediately a 500:

```
Started POST "/aspect_memberships" for 213.245.69.149 at 2014-04-06 21:15:06 +0200
Processing by AspectMembershipsController#create as JSON
  Parameters: {"person_id"=>14357}
Completed 500 Internal Server Error in 15.1ms

ActiveRecord::AssociationTypeMismatch (Aspect(#59068543400) expected, got NilClass(#59016804240)):
  app/models/user/connecting.rb:19:in `share_with'
  app/controllers/aspect_memberships_controller.rb:54:in `create'
  lib/rack/chrome_frame.rb:39:in `call'
  lib/unicorn_killer.rb:35:in `call'
```
In some cases (I don't success to see precisely which ones), you get the facebox, but then we you click on the create button, the Browser console display a weird 422 error.

**Comment by svbergerem** [comment] 2015-05-02 15:24
Is anyone still able to reproduce this bug?

**Comment by jaywink** [comment] 2015-06-14 14:13
No reply from anyone since over a month and couldn't reproduce myself on 0.5.1.0-RC - closing.

**Closed by jaywink** 2015-06-14 14:13 UTC
Labels: bug, confirmed, weird
