### ISSUE TITLE
Integrate comments of reshared posts

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6924] opened 2016-07-21 06:03 UTC
It would be useful to be able to combine into a single view, of comments of reshared posts, with the original post.

https://diasp.eu/posts/3696869

**Comment by denschub** [comment] 2016-07-21 08:23
Duplicate of a mixture of #4219 and some discussions on Loomio, like [this one](https://www.loomio.org/d/ObyhtVp6/-like-shared-posts-up-to-the-source-and-inform-also-the-sharing).

**Closed by denschub** 2016-07-21 08:23 UTC
