### ISSUE TITLE
Support VK

### ISSUE THREAD

**Issue by AlexTalker** [diaspora/diaspora#4984] opened 2014-06-02 19:41 UTC
Discussion on loomio: https://www.loomio.org/d/VHNgb8sk
Do you wish support VK social network, like Facebook and Twitter right now? Subject: https://vk.com

**Comment by cmrd-senya** [comment] 2015-06-24 08:29
I'm working on it currently.

**Comment by YakovL** [comment] 2015-06-24 08:35
@cmrd-senya thanks man, really glad to hear that.

**Comment by cmrd-senya** [comment] 2015-06-25 00:26
Ok, community, now I need your help. [Here](http://paste.ubuntu.com/11770607/) is my last groundworks.

I have some problems implementing this feature due to vk.com API design. The story is following. VK has two types of applications - standalone apps (mobile and desktop) and web-application. The main difference from our point of view, is that standalone application is obliged to use "https://oauth.vk.com/blank.html" as redirect_uri in authorization (that's why I had to write code lines 181-186 in [my patch](http://paste.ubuntu.com/11770607/)). We would like to use web application, because we need to redirect back to OmniAuth to finish authorization, but web application by VK API design is not allowed to make posts ([wall.post](https://vk.com/dev/wall.post) method)! If I force it to use redirect URI for standalone app, authorization passes well, but it obviously stucks on that page, without going back to Diaspora. Standalone app is supposed to extract access token from the URL, since web browser is supposed to be built into the app. Addition discussion on this topic is [here](https://github.com/mamantoha/omniauth-vkontakte/issues/25) (on russian).

To solve that, we either should modify authorization flow, to allow somehow to extract code from URL (iframes?). That would probably require changes in the way we work with OmniAuth or omniauth-vkontakte strategy.

Or, there is a way to call message post from javascript described [here](https://vk.com/dev/api_confirm). But that would require separate support code from all other services (since, as far as I understood, all that service stuff is done on the server side, not on the client).

**Comment by jhass** [comment] 2015-06-25 01:05
Ah well, you should have brought that up the moment you found that before investing any more time into it.

To be honest none of that sounds like a good idea. I'd personally vote to close this as a won't implement then, vk.com doesn't want web apps to make posts, we are a webapp, trying to circumvent that will only give us headaches and that hack will be hell to maintain.

**Comment by cmrd-senya** [comment] 2015-06-25 01:14
Well, I spent only two days and brought it up as soon as I had discovered that.

Maybe it is possible to implement it transparently for Diaspora by hacking omniauth-vkontakte? I don't feel myself expereinced enough to say that there is no satisfying solution.

I would suggest to leave it open for a while. Maybe someone (possibly even me) comes up with some bright idea.

**Comment by denys281** [comment] 2015-08-01 16:26
@cmrd-senya  if you want post something to wall you should use it through window confirmation http://vk.com/dev/api_confirm .

**Comment by cmrd-senya** [comment] 2015-08-01 21:15
@denys281, as far as I understand the API, this would require use of javascript, while the diaspora's services feature works on the server side and doesn't allow such type of user interaction. In any case, this is responsibility of an OmniAuth strategy, not diaspora. So probably it could be solved by implementing new OmniAuth strategy with this confirmation window support.

In any case, you are welcome to pick my e601f01ff92c95bec7d87360953f1fa409574c5f and play with it.

**Comment by cmrd-senya** [comment] 2016-04-14 18:00
So I checked this once again to be sure that nothing has changed after a while. It's not that "vk.com doesn't want web apps to make posts". It's rather "vk.com doesn't want web apps **authenticated with OAuth** to make posts". The way for webapps to make posts to vk.com is to use so called [Open API](https://vk.com/dev/openapi) which is a fully javascript thing and therefore doesn't fit to our services workflow. Vk.com simply doesn't allow webapps to make posts in fully automated way, like we do. So will vk.com be supported as service on diaspora*? I would say no, unless VK doesn't change their permissions policy.

Their javascript thingy may be still used, but it must be defined how it should work. For example, it could transfer posts you manually pick from your stream with mouse-click. But I'm not really sure if it is useful. Our services feature was designed to help people centralize their usage of social media within their diaspora account (post once, get posted everywhere), and VK Open API is designed to help people pull content to VK, which is not we are too much interested in.

Therefore, as this is a service feature request, I propose to close this as WON'T FIX so we don't give false hopes to users. If VK changes their policy, which is unlikely, we can reopen this issue. If someone sees some other scenario of interaction of diaspora* with VK allowed by VK API, it may be proposed with a different issue.

**Comment by cmrd-senya** [comment] 2016-04-14 18:10
![2016-04-14 21 05 40](https://cloud.githubusercontent.com/assets/10187586/14538555/03f3ffe4-0285-11e6-8fc9-bc44cc9a926f.png)
This is the limitation which disallows us to implement that.

**Closed** 2016-04-14 18:51 UTC
Labels: feature, newcomer, services
