### ISSUE TITLE
Support ActivityPub

### ISSUE THREAD

**Issue by evanp** [diaspora/diaspora#7422] opened 2017-04-11 17:18 UTC
Diaspora should support the [ActivityPub](https://www.w3.org/TR/activitypub/) ("AP") standard. AP provides a client-to-server API as well as a server-to-server federation protocol. It is the successor to the OStatus standard partially supported by Diaspora already.

Other social networking servers like pump.io and GNU MediaGoblin are moving to AP.  There is some more information on the state of the [ActivityPub network](https://www.w3.org/wiki/Socialwg/ActivityPub_network) on the W3C wiki. We're trying to get everyone involved in federated social networking to rally around this standard and get a truly federated network working.

**Comment by DeadSuperHero** [comment] 2017-04-11 17:22
Hi Evan, nice to see you here.

This is on our radar, and I think our system is modular enough to support a different federation protocol and schema, in theory. Unfortunately, adapting a new standard is a pretty slow process for us, and we're finally at a point that we are happy with our own federation protocol. However, I think many will agree that we eventually want to move towards greater compatibility with the rest of the federation.

One caveat is that we first need a dedicated person to work on it, which would involve creating a native Ruby implementation of ActivityPub that is compatible with Diaspora. The second is that we want to be certain that ActivityPub can support the privacy features that are leveraged by Aspects and private messages. As those are cornerstone features of our network, it's kind of an important prerequisite.

**Comment by evanp** [comment] 2017-04-11 17:33
@DeadSuperHero Hi! I'm glad to be here. I think @cwebber can talk to the aspects and privacy issues. It's one of the big things we wanted to do with AP -- make it possible to share privately across servers.

**Comment by annando** [comment] 2017-04-11 19:07
There are some unanswered questions in the protocol like the question how to sign and distribute comments.

Diaspora distributes comments via the thread owner while pump.io (and AP?) Is distributing comments through the commenting account. This is an important difference.

**Comment by jaywink** [comment] 2017-04-11 19:46
@annando actually, as far as I've been able to understand (read it a few times!), comments would be delivered by the thread owner. It would be impossible for the commenter to deliver them, that would be a technical impossibility, not sure how pump.io can do it?

>  When Activities are received in the inbox, the server needs to forward these to recipients that the origin was unable to deliver them to. To do this, the server MUST target and deliver to the values of to, bto, cc, bcc, and/or audience if and only if all of the following are true:
> 
>   * This is the first time the server has seen this Activity.
>   * The values of to, bto, cc, bcc, and/or audience contain a Collection owned by the server.
>   * The values of inReplyTo, object, target and/or tag are objects owned by the server. The server SHOULD recurse through these values to look for linked objects owned by the server, and SHOULD set a maximum limit for recursion (ie. the point at which the thread is so deep the recipients followers may not mind if they are no longer getting updates that don't directly involve the recipient). The server MUST only target the values of to, bto, cc, bcc, and/or audience on the original object being forwarded, and not pick up any new addressees whilst recursing through the linked objects (in case these addressees were purposefully amended by or via the client).

https://www.w3.org/TR/activitypub/#inbox-delivery

AFAICT that means exactly that the content owner is responsible for delivering any follow-ups - just like the Diaspora protocol requires.

**Comment by cwebber** [comment] 2017-04-11 20:29
Yup, servers of people higher up in the chain should deliver to their own collections of participants (read, Diaspora aspects or sets of followers) the content of comments they receive following the pattern described above.  Indeed, that's exactly for the delivering to groups you don't have access to problem.

**Comment by annando** [comment] 2017-04-11 22:08
@cwebber Yeah, I was one of the people who gave feedback on this.

Concerning this comment distribution via a third party I'm very far from understanding the definition. This is partly caused by language problems (my English is okay for colloquial talks, but not for more), but also caused by my understanding problems of definitions of every kind. I cannot learn by reading definitions, but only by looking at examples.

Concerning AP and AS2, how would the following things be defined with them:

* dislike (not removing of "likes", but disliking something)
* events and participation messages for these events (attend, not attend, maybe attend)
* forums (in OStatus they are called "groups")
* private messages (in difference to posts to a limited amount of users)

**Comment by jaywink** [comment] 2017-04-12 18:32
@annando 

> dislike (not removing of "likes", but disliking something)

    {
      "@context": "https://www.w3.org/ns/activitystreams",
      "summary": "Sally disliked a post",
      "type": "Dislike",
      "actor": "http://sally.example.org",
      "object": "http://example.org/posts/1"
    }

Dislike is a core AS2 Activity.

Event is also a [core AS2 Object](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-event):

    {
       "@context": "https://www.w3.org/ns/activitystreams",
       "type": "Event",
       "name": "Going-Away Party for Jim",
       "startTime": "2014-12-31T23:00:00-08:00",
       "endTime": "2015-01-01T06:00:00-08:00"
    }

There is also a [Group Actor type](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-group). Don't ask me how to use it though ;)

**Comment by annando** [comment] 2017-04-12 20:04
I'm definitely lost in these specifications. So there is some "like" and "dislike" in AS2, additionally "Like Activity" and "Like Collections" ... On Diaspora a "like" (or "dislike") is simply this: https://diaspora.github.io/diaspora_federation/entities/like.html - and it is transported like every other message, that's all.

To do anything with AS2 and AP (in Friendica) I will need some "translator" and some existing implementation, that's for sure.

**Comment by cwebber** [comment] 2017-04-14 16:41
@annando I'm not sure how it's more complicated... the Diaspora description and the ActivityStreams definition look not too far off from each other.  But if you need help, [give me a ping](https://dustycloud.org/contact/).

**Comment by annando** [comment] 2017-04-15 06:31
As an example: How do I repeat a post? In the current Diaspora protocol it is described here: https://diaspora.github.io/diaspora_federation/entities/reshare.html

In the AS2 description (and the vocabulary) I haven't found clue to do this.

I guess that I have to contact you very often :-)

**Comment by cwebber** [comment] 2017-04-18 01:18
Well you're welcome to contact me... as co-editor of ActivityPub, I even encourage it. :)

You're right that the (re)share bit was missing... [that was caught a few days ago](https://github.com/w3c/activitypub/issues/186), and we're talking about it tomorrow on the call.  That's the whole reason the spec is going through several cycles before it hits a recommendation!  Specs are written by humans, and humans fail... I probably fail more than most, even.  But we're seeking feedback.

And indeed, AP has already been shaped by the contributions of both of you (@annando and @jaywink).  We're now at the point in the spec where we're relying on people actually implementing things, and catching what's missed or needs to be adjusted based on that feedback.  I do want, and appreciate, your feedback, both from reading and from implementation experience if you're willing to give it.

So if you see things that are missing, or that need clarification, or have errors... yes!  Please do contact me!  Or [file an issue](https://github.com/w3c/activitypub/issues)!  This is the time to do it!

**Comment by cwebber** [comment] 2017-04-18 01:19
BTW, I wrote up a little [ActivityPub tutorial](https://raw.githubusercontent.com/w3c/activitypub/gh-pages/activitypub-tutorial.txt) which might even get put at the top of the AP spec (obviously with the ascii art becoming real graphics) in case that's of help to anyone here.

**Comment by hex-m** [comment] 2017-10-05 13:22
Is this issue just about the server-2-server part of AP (federation) or does this relate to https://github.com/diaspora/diaspora/issues/7422?

**Comment by Flaburgan** [comment] 2017-10-05 13:57
#7422 is this issue, which one are you talking about? But yes, this is about s2s, not c2s.

**Comment by hex-m** [comment] 2017-10-05 14:38
Thanks for the clarification. And sorry - I meant https://github.com/diaspora/diaspora/issues/3467.

**Comment by roipoussiere** [comment] 2018-05-07 13:32
Related discussion on Discourse: [Let’s talk about ActivityPub](https://discourse.diasporafoundation.org/t/lets-talk-about-activitypub/741).

**Comment by wizzwizz4** [comment] 2019-01-06 12:52
Any updates on this? ActivityPub's much more standardised now, and I think it would be great if Diaspora wasn't a (collection of) island(s) any more.

**Comment by denschub** [comment] 2019-01-06 13:39
>  In my personal opinion that is strictly a resource management thing.

No, it is not. There are issues by-design with ActivityPub that completely disagree with what diaspora\* is doing in terms of communication reliability, predictability, and general user-friendliness. Those issues have been outlined in the linked Discourse thread, and as much as I appreciate the euphemisms by @Flaburgan and @HankG, those issues are **not** solvable by throwing more development time into diaspora. So please stop acting like "low resources" is the reason why nobody is working on AP support. It is not.

**Comment by jaywink** [comment] 2019-01-06 13:52
The Discourse thread doesn't clearly list anything after a quick view. Would you @denschub mind recapping them here? I'm interested in seeing Diaspora adopt AP sometime in the future and maybe people outside the Diaspora project can help demystify AP for the project. This wont magically make development happen, but it might help get rid of the the "Diaspora cannot federate over AP" myth, which knowing both technologies in some detail I find it hard to believe.

Note AP is not a protocol specification like Diaspora. It is more like a framework. Thus I find it hard to believe Diaspora protocol could not be done with AP+extensions, having been a part of the working group for exactly the reason to make sure it can.

**Comment by HankG** [comment] 2019-01-06 13:52
> > In my personal opinion that is strictly a resource management thing.
> 
> No, it is not. There are issues by-design with ActivityPub that completely disagree with what diaspora* is doing in terms of communication reliability, predictability, and general user-friendliness. Those issues have been outlined in the linked Discourse thread, and as much as I appreciate the euphemisms by @Flaburgan and @HankG, those issues are **not** solvable by throwing more development time into diaspora. So please stop acting like "low resources" is the reason why nobody is working on AP support. It is not.

I'll speak solely for myself by reiterating what I said at the end of my comment: " As someone who uses Diaspora and Mastodon throughout the day every day I would love to see this happen.. As an active Diaspora developer I am looking forward to working on this eventually."  That doesn't mean there aren't problems to be overcome when it's time to work on it but those aren't insurmountable problems for Diaspora integrating with AP at some level.  They may be **hard** problems but not **insurmountable** ones.  They and that whole initiative is something that will require an intense amount of concentrated work though obviously as well.

**Comment by denschub** [comment] 2019-01-06 15:39
> The Discourse thread doesn't clearly list anything after a quick view. Would you @denschub mind recapping them here?

It's quite common for people to ask for a tl;dr, but there is none. You can't explain the world in two sentences, and that's not going to happen here, either. [This post](https://schub.io/blog/2018/02/01/activitypub-one-protocol-to-rule-them-all.html) is a starting point, but you already know that one. Here is another wall of text, explaining the same issue with different words, hopefully making the issue clearer. No, no tl;dr.

ActivityPub, if anything, is a transport protocol, and nothing responsible for for the application/presentation layers. ActivityStreams would be accountable for that. The ActivityStreams Vocab [describes](https://www.w3.org/TR/activitystreams-vocabulary/), generally speaking, a set of *things* you can do with other *things*. More specifically, AS describes that an `[Application, Group, Organization, Person, Service]` can `[Accept, Add, Announce, Arrive, Block, Create, Delete, Dislike, Flag, Follow, Ignore, Invite, Join, Leave, Like, Listen, Move, Offer, Question, Read, Reject, Remove, TentativeAccept, TentativeReject, Travel, Undo, Update, View]` one or more `[Article, Audio, Document, Event, Image, Note, Page, Place, Profile, Relationship, Tombstone, Video]`.

For each of those object types, AS describes a set of properties each object *may* have. That's a perfect rfc2119 *may* right there, everything is entirely optional. There is no real required set of properties (besides an identifier) for each object, so it's everyone's guess on what to do on receiving an object. Even more interesting, if you're not okay with the properties AS defines for you, not to worry, [you can happily come up with your own stuff](https://www.w3.org/TR/activitystreams-core/#extensibility):

> In Activity Streams 2.0, an "extension" is any property, activity, actor or object type not defined by the Activity Vocabulary. Consuming implementations that encounter unfamiliar extensions MUST NOT stop processing or signal an error and MUST continue processing the items as if those properties were not present.

Not only does AP/AS not provide any guarantee that a specific set of properties are there, but there could also be any other imaginable properties, and **by design** that is a feature and throwing one's arms in the air and acting like properties aren't there on receiving is perfectly fine.

I'm dead serious here: how are we supposed to build something that works for users based on that? From a pure implementer perspective, AP/AS is almost like coming up with a protocol that states "you can send XML files via email. We don't really want to tell you what's in those XML files, but you have to parse it anyway, and you have to act as you understand it". What some of you are praising as a feature, is actually really bad for implementations. You can't throw indefinite amounts of extensibility onto a machine-to-machine communication protocol and expect things to work reliably.

I am well aware that implementing AP is a fancy thing to do right now, and everyone writes flashy press announcements with their freshly added AP support. And well, good for them, but with me spending significant portions of my career working on web browsers and web standards (you know, the world where even a tiny bit of flexibility/ambiguity resulted in the worst possible outcomes), I seriously want to bang my head against a wall and ask myself why the world hasn't learned anything. Yes, it's nice that so many projects can claim to support AP, but I really wonder why nobody seems to consider what it actually *means*.

Let's go away from diaspora\* for a bit, as this is not about diaspora\* at all. Do you know [JetLovers](https://www.jetlovers.com/)? Okay, don't worry, I didn't expect you to: it's basically a social network for people who spend too much time on airplanes. You basically share the airport you're currently at (and your planned route), and it allows you to connect with coworkers/friends/... who just happen to be in the same airport, or even the same plane. I know this concept sounds weird to most of you, but it works well for illustrating a point. JetLovers could implement AP. For that, they'd send status updates in the form of `Person Creates Place`, probably, because that makes sense, right?

So, Alice is on Jetlovers, and Bob is using Mastodon. Alice is aware that both services are using ActivityPub because they both wrote fancy announcement blog posts claiming so. Therefore, Alice adds Bob to her contacts on JetLovers.

Now. What happens? Will Bob ever see Alice's `Place` updates? Mastodon doesn't support sharing locations, so what happens if they receive one? Do they display GPS coordinates in text form? Do they just drop it? What happens with Carol, a contact on NextCloud, which also supports AP?

I don't actually care what the answer to that is. The fact that this is a perfectly valid question for me to ask is the main issue. Both projects support ActivityPub, but that's nothing more than a merely blanket term, or the indication that a project is using a *framework*. For users, **it means nothing**. Supporting ActivityPub is a beautiful thing for people to be able to flatter themselves, claiming they work on "making decentralized social networks connect to each other." And up to a certain extent, this is actually true: they connect *nerds* to each other. That's about it.

I've heard horror stories from people implementing AP, telling me about their *workarounds*, and yet still claim that AP works just fine. Stuff like "oh yeah, if we can't display the object because we don't know it, we just link to the original item." Yeah, as if that is a workable solution. Sure, you folks on GitHub click the link and have no trouble with consuming that item on a remote pod, then coming back to your own instance and figure out a way to comment/like/whatever on that. It's naive to think that's a solution that will work for *users*. Users will click on the link, read the post, search for a link button or a comment field, maybe even find something that redirects them to the login form of that remote node ... whatever happens, they will get confused and never come back again because this thing is confusing as heck.

If Alice knows about the technical background, you might be able to explain the limitations. But what happens if Alice is not a software engineer, but a frequently traveling businesswoman selling heavy machinery? Alice doesn't care that you are all wonderful projects implementing a standard, and both implementations are perfectly valid ActivityPub nodes. She just realizes that, for some reason or another, her flight plan updates are not visible to Bob while her text-only updates are visible - at which point using the service in the first place has no purpose, so she stops doing that.

I've yet to find someone who is able to look me in the eye and seriously claim that this scenario is better than a simple "No, Alice, you can't communicate with Bob."

The current modus operandi seems to be to just look at Mastodon and copy their implementation because that seems to be the only way to get *something* working. That, however, is not about supporting AP, it's about supporting Mastodon's dialect of AP, and their subset of that. And *that* is just not going to happen with diaspora\*. While there is an overlap between feature sets and UX, there are way too many differences.

If diaspora\* ever supports AP, then it is likely in the form of an external service, just like we handle Twitter crossposts. And no matter how hard @HankG and others try to re-shuffle words here, what I say has the approval of the entire diaspora\* core team (which I have verified more than once): diaspora\* using AP for its federation is, in its current form, simply not going to happen. For us, building something isn't really about having an ideologically perfect project that supports all the latest flashy specifications, it's about creating something that works *for users*. And here, we can pick between two possible scenarios:

1. Implementing AP, and put ourselves in a position where we have to explain why *sometimes* communication works just fine, but with *some* endpoints, it *might* not work, polls will never arrive, people might not be able to send you identifiable private messages, but they'll just show up as limited posts, oh, and geolocation tags always get lost when talking to some endpoints.
2. Not implementing AP, being able to explicitly say "no, you can't communicate with X, but you can be sure that, if there is some form of communication, it works reliably and we are relatively sure that no contents get squished, lost, or otherwise transformed."

Option 1 is, for us, simply not workable. That's sacrificing UX for purely ideological reasons. It makes distributed social network *more confusing* for non-technical people to use, and that is absolutely not a thing we need. At the end of the day, we are **all** doing a horrible job at building consistent user experiences already, and I absolutely don't get why people are happy to make it even worse.

**Comment by HankG** [comment] 2019-01-06 16:04
I'll make this easy.  I agree with @denschub's post **100%**.  The part that seems to be lost is this:

> If diaspora* ever supports AP, then it is likely in the form of an external service, just like we handle Twitter crossposts.

I don't know what the AP integration will look like.  Is it an app?  Is it a side car service of some sort?  Is it something else?  Who knows? I'm certain it wouldn't become the lingua franca of Diaspora federation.  I imagine the _soonest_ I'd get to look at it seriously will be a year from now. So I'm not going to spend too many brain cells worrying about details like that for something so far away.  

Even if I had no other higher important things I'd rather work on I'd probably still wait at least half a year because of the churn problems highlighted.  I too am following the AP integration discussions across the other fediverse projects closely.  As an end user I don't care about the how I care about the existence of it in some form.  I'm going to just leave it at that point until I get within a reasonable time frame to look at it.

**Comment by jaywink** [comment] 2019-01-06 18:05
Wow, that is a lot of text without answering the question at all. I still don't see from Diaspora protocol perspective what are the blockers in federating a Diaspora style platform using AP as a framework. The time for generic "what is AP good for" and discussing whether it is bad or not is long gone. It is here and people are adopting it. If the Diaspora project wants to say "nah it's shit, we're not doing it", then that is a reason, but it isn't a technical one.

Any concrete technical questions on how something in Diaspora would work in an AP context I'm sure many people would be happy to answer (including myself). For generic AP discussion this is most definitely the wrong forum - I would suggest the W3C social issue tracker or irc channel.

> If diaspora* ever supports AP, then it is likely in the form of an external service, just like we handle Twitter crossposts.

Cross posting is not federation. That would be a shame if the implementation was one way only.

**Comment by SuperTux88** [comment] 2019-01-06 18:33
> I still don't see from Diaspora protocol perspective what are the blockers in federating a Diaspora style platform using AP as a framework.

Well, if we would replace salmon with AP, that wouldn't change much besides having more JSON and less XML, it still wouldn't be compatible with anything because it would still be a diaspora specific protocol (diaspora dialect of AP). It would only add work and doesn't add any value. AP doesn't magically mean compatibility, and that's what @denschub answered.

> If the Diaspora project wants to say "nah it's shit, we're not doing it", then that is a reason, but it isn't a technical one.

Nobody said that. AP is great, and it's exactly what it wants to be (a framework), but people want it to be more and think that everything that talks AP is compatible, but that's not the case. There is currently no reason for us to switch to AP, because our protocol just works fine, and as said, it wouldn't magically add compatibility, it would just add work and probably new bugs.

And there are also other problems that come with AP, but I'm not going to repeat the whole comment of @denschub :)

**Comment by jaywink** [comment] 2019-01-06 19:18
@SuperTux88 I wasn't arguing that Diaspora should immediately start work on AP. I was just disagreeing to this:

> No, it is not. There are issues by-design with ActivityPub that completely disagree with what diaspora* is doing in terms of communication reliability, predictability, and general user-friendliness.

I don't see those issues. Dennis didn't list anything. What he wrote was a more generic critique of AP.

Of course nothing magical would happen should Diaspora start to work on AP. Of course it would be a huge amount of work. Btw, there is no "pure AP" - it would anyway be a Diaspora dialect.

> but people want it to be more and think that everything that talks AP is compatible, but that's not the case

Who are these people? I doubt anyone who has even looked at the spec thinks that everything that utilizes AP should be automatically compatible to all the other implementations. That is not realistic. I don't know of any AP implementation like that. And there will never be one. One simple reason is delivery which is outscoped from the spec. That doesn't mean project maintainers cannot build compatibility for several "flavours". But a single implementation simply cannot be compatible fully with anything except itself.

Great that the Diaspora project is happy with its protocol, that is fantastic :tada:

**Comment by denschub** [comment] 2019-01-06 20:38
Okay, this conversation here actually serves no purpose anymore, I fear. The arguments here show that there are conflicting interpretations of what a *standard* should be. And that's probably fine, but given the circumstances, this discussion will not yield any results.

Yes, @jaywink, you **are right**, my comments **are** *generic critique of AP*, and that's precisely the point. AP is not designed as something to *just work*, but as a framework for people to build their own stuff. You're claiming you can't imagine someone expecting AP just to work, yet, in the initial post by @evanp, he is talking about "get[ting] a truly federated network working," and so are others, as you can follow up on Discourse. Sprinkling a bunch of AP on an implementation is not going to make "one large network of different implementations" happen, and we all agree on that.

To some, having AP as a buzzword for a "kinda similar, but not compatible" communication channel is fine. We all can acknowledge the SocialWG's plan of building a transport protocol without actually building something concrete (and no, that's not me saying things, that's literally the [SocialWG's charter](https://www.w3.org/2013/socialweb/social-wg-charter.html).), and if we take that as a goal, then cool, there we are. Comments like "go to the SocialWG issue tracker" are, btw, also highly inappropriate. What I am describing as "too much flexibility" is not a bug, it is the literal design behind AP, and a bug suggesting to define a set of required attributes, objects, and actors, would be `wontfix`ed immediately, as it would literally violate the goals of the WG and AP itself.

Others, however, have a different opinion. While some think it's perfectly fine that implementations have to talk to each other and that projects have to implement "compatibility for several 'flavours'" of a given specification, I wholeheartedly disagree, and that will not change, no matter how long we end up sinning in circles here.

To me, and it happens that everyone in the diaspora\* core team agrees, this is not *perfectly fine*. In fact, I think it's bad. To me, a specification is a reference document to follow during implementation, and the mere reason the specification exists is that I don't have to look at what other implementations are doing. In my opinion, as soon as you need to look at other applications to know what you *should* implement, the specification failed, because it no longer is the source of truth, and thus, it's not specifying anything. We don't need a spec for that. And with the current state, most projects should label themselves as "Mastodon-compatible" instead of "ActivityPub-compatible," because that's closer to reality than everything else.

I really tried my best to explain my reasoning; in a lengthy blog post (which, btw, got support from people inside the WG, and we agreed that there is no black and white here), in multiple comments on Discourse, on GitHub, and on other social media, to explain the risks of basing social network communication on something with such high levels of ambiguity, and I tried my best to explain why I think this is something terrible for end users, from both the "it kinda works" communication channel and the unified marketing label "ActivityPub". It saddens me quite a bit that some people just walk over all that, discarding those concerns as "no real issues," but I can accept that to some projects, this is simply not a concern.

There are different projects out there for a reason. That's always been the case, and it always will be the case. In computer history, there never was "one thing to solve everything," and there never will be. Especially in social media, there are too many conflicting demands and ideas for that even to be possible.

---

@annando Even though we've just talked a couple of days ago, I'll say it again: looking forward to your blog post on the issues you faced while implementing AP. I'll keep my part of the promise as well, and will make sure I either publish a revised opinion, or to follow up with questions on that. 🙂 

---

There is no point in continuing here, as there are two contradictory views on what a "standard" should be. That's not going to change, no matter how many hours we spend here. Continuing here will lead nowhere besides a place where people start getting ad hominem again, but this is not the right place for that. Feel free to shitpost about me on social media for locking this.

If someone steps by and is seriously interested in adding an AP service, propose your implementation on Discourse.

**Comment by cmrd-senya** [comment] 2019-01-06 23:15
I've read your discussion and have a thought I'd like to share.

What I understood is that AP is a framework. But a framework for what? I'd say that we can see it as a framework for creating federated protocols. It's like OAuth2 is a base framework for creating authorization protocols like OpenID Connect. Or like XMPP which defines some basic features in some RFCs and has lots of extensions in the form of XEPs. So I agree that "implementing AP" in diaspora* doesn't make sense itself. What would make some sense is to create a custom protocol (a dialect) based on AP for diaspora. Such dialect should be specified strictly without the ambiguity about what we send and what properties objects have.

We can't discuss implementing AP for diaspora because it makes no sense because of the AP ambiguity. So if there is anyone who wants to move on with supporting AP in diaspora, the first step to take would be to specify with some strict documentation the AP based protocol which is satisfactory for diaspora. I don't think anyone would be against it if someone will work on creating such specification. It could even be fun to discuss and work on. However that must be kept in mind that nothing guarantees that we will eventually implement this specification in diaspora. But there is no sense to discuss the topic of "AP in diaspora" before we have the specification of the dialect which would fit diaspora. As soon as we have such specification we can consider our resources and do some experiments if it is approved by the core team.

So if there is someone who is strong about the idea of diaspora working with something based on AP for federation, they should consider writing the AP based protocol specification for diaspora and only then propose this specification for implementation in diaspora. Working on such specification doesn't require any approval from the core team so this someone can just start working on it.

 Everything written above is my personal opinion though and may differ from the core team members opinion.

**Comment by deutrino** [comment] 2019-07-11 22:39
Does it make sense now?

![image](https://user-images.githubusercontent.com/304300/61090047-2a225780-a40b-11e9-8469-9b18e587ad51.png)

**Comment by MasterOfTheTiger** [comment] 2019-07-12 13:48
@deutrino Whether it makes sense to federate via ActivityPub or not is not the issue. The issue is how diaspora* would implement it (if I understand it correctly).

**Comment by wizzwizz4** [comment] 2019-07-12 14:39
I've been thinking about this for a few months, and I'd appreciate somebody tearing my proposal into shreds:

When establishing ActivityPub federation, detect what we're talking to. Then, mash stuff we send it into a format it can understand, and convert stuff that doesn't exist in Diaspora* into a format Diaspora* can understand.

For example: if a Diaspora* instance wants to federate with the Jen's Travel Associates forum, which only allows communication via geotagged images, Diaspora* might "import" posts as a [What 3 Words](https://what3words.com/) followed by an image, and "export" them as SVG files tagged at Null Island (or the same place as what they're replying to). Crude, yes, but it permits communication between vastly different platforms.

For a less pathological example: Mastodon "importing" can be as simple as escaping the plain text (so `[test](https://looks.like/a-uri-doesn-t-it)` doesn't get interpreted as a link, etc.) and slapping the images-plus-alt-text at the end. Similarly, "exporting" is as simple as compiling the Markdown to HTML, since iirc Mastodon clients can display **bold** and `code` even if the servers don't support posting formatted text.

I suppose this isn't really "supporting ActivityPub", since that's too ill-defined to be impossible; it's simply supporting _most ActivityPub-based systems_. Even crude support would be amazing: establishing just _some_ form of communication is preferable to no communication.

If this proposal isn't utterly useless, then the obvious next question is: what would this look like?

**Comment by 6543** [comment] 2019-10-24 12:51
I know about the privacy concerns of ActivityPub but it seams to be the successor ....

so my idear is this:
 - Diaspora -> Diaspora uses still its privacy frendly protocoll
 - Diaspora to XY uses ActivityPub ... so we dont dry out on our diaspora iland :(

**Comment by deutrino** [comment] 2019-10-26 23:32
Might it not make sense to push all posts that are visible to public (or, to a user-configurable set of aspects) to the AP fediverse, and do essentially what @wizzwizz4 suggests (https://github.com/diaspora/diaspora/issues/7422#issuecomment-510911395) in reverse in order to display incoming posts semi-intelligibly in with the Diaspora news feed?

**Comment by wizzwizz4** [comment] 2019-10-27 10:52
Also, it'd be good if you could send messages to Mastodon users… though that's difficult to implement, since you'd need a warning saying "server owner will be able to read this" (as I understand, Diaspora supports encrypted messages and Mastodon does not).

@deutrino How do you envisage comments on ActivityPub posts working?

**Comment by annando** [comment] 2019-10-27 13:16
@wizzwizz4 @deutrino it does not make sense to discuss about some partly protocol implementation. The issue is about implementing the ActivityPub protocol as an additional protocol in Diaspora. And according to the comments in this thread no one from the core team is working on it or plans to do so - which has to be respected.

So until there isn't some new contributor or some change in mind it doesn't make sense discussing about details of an implementation that isn't expected to come.

**Comment by goobertron** [comment] 2019-10-27 13:28
@wizzwizz4 @deutrino, please read the comments above yours, particularly those from core team members (shown by the 'Member' flag at the top of their comments. You'll see that until AP itself changes, it's not going to be implemented in diaspora\*.

My suggestion, made at the beginning of the year, was:

> As the people who currently have the most in-depth knowledge of Diaspora's code/architecture don't think that there is currently a workable implementation for AP within Diaspora, the onus is surely on someone who believes that there *is* a workable implementation for AP within Diaspora to propose that, with a schema/etc.
> 
> But this discussion should be happening in [Discourse](https://discourse.diasporafoundation.org/t/lets-talk-about-activitypub/741/), shouldn't it? There is a link in that Discourse thread to Dennis's long [blog post about AP](https://schub.io/blog/2018/02/01/activitypub-one-protocol-to-rule-them-all.html), which I imagine contains some of the detail people have been asking for in the last few comments here.

Feel free to contribute to the discussion on Discourse (after reading it first, of course, to see whether or not you suggestions have already been addressed). You can use your GitHub account to sign in to Discourse, so there's no need to create another account.

**Comment by denschub** [comment] 2019-10-27 22:42
Thank you, Goob.

In addition to the comments above, I will now close this issue. There are no immediate plans to implement AP/AS inside diaspora\* in any form, so I don't think it is worth having an issue open. My primary motivation for closing is the fact that there are USD 513 worth of bounties placed on this bug, and by leaving this bug open with no plans to act on it, we're effectively holding that money hostage. When the issue is closed and processed by Bountysource, the people who decided to put money on this issue can either receive a refund, or choose to put the money onto other matters. I think this is a much fairer approach than leaving this open and not doing anything about it.

To stop people posting on a thread where nobody reads it, I'll also lock this issue. If someone has new arguments, please raise them on Discourse, as explained by @goobertron above. If we change our decision and want to work on adding AP/AS support actively, we can either reopen this issue or open a new one.

**Closed by denschub** 2019-10-27 22:42 UTC
Labels: bounty, 👥 needs discourse, 🛰️ federation, 🤔 undecided
