### ISSUE TITLE
allow adding xmpp only contacts to aspects

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6089] opened 2015-06-09 08:40 UTC
When chat is enabled, allow adding xmpp only contacts so it shows up in xmpp clients.  As second step, contacts added via xmpp clients could be added to aspects.

**Comment by jhass** [comment] 2015-06-09 08:50
Duplicate of https://github.com/diaspora/vines/issues/10

**Closed by jhass** 2015-06-09 08:50 UTC

**Comment by pravi** [comment] 2015-06-09 08:58
I think it would be good to show such contacts in aspects and be able to modify them via the web interface.

**Comment by jhass** [comment] 2015-06-09 08:59
I think I disagree, aspects should stay the management tool for your streams primarily.

**Comment by pravi** [comment] 2015-06-09 09:42
Should we setup a vote on loomio?

**Comment by jhass** [comment] 2015-06-09 09:54
If you care that much about it....

**Comment by pravi** [comment] 2015-06-09 10:01
created a loomio vote https://www.loomio.org/d/UPWolQ8z/allow-managing-non-diaspora-xmpp-contacts-via-diaspora-aspects
