### ISSUE TITLE
Clicking like, unlike and like again causes error

### ISSUE THREAD

**Issue by abimelex** [diaspora/diaspora#6655] opened 2016-01-24 19:46 UTC
Unliking / Dislike a Post and liking it again causes first 422 Server response:

e.g.:

`query-31118357fae53e3c73a4fab320688aad.js:3 POST https://pod.geraspora.de/posts/4427998/likes 422 (Unprocessable Entity)`

And than JS errors on each click:

`Uncaught TypeError: Cannot read property 'guid' of undefined`

Steps to reproduce:
- Like a post
- Dislike a post
- Like post again. --> Error

Expected:
- Post is liked again
- Button or Linktext changes

**Comment by visualsayed** [comment] 2016-01-24 23:03
@abimelex  Could you please confirm if you are connected with the post's owner?

Are you sure the unlike action has been processed correctly?

You could try to unlike the post then refresh the page and see if the unlike action has been processed or not.

Thanks,
Sayed

**Comment by abimelex** [comment] 2016-01-24 23:17
Unlike seems to fail if the Post-owner is on the same pod. How is connected defined?

**Comment by visualsayed** [comment] 2016-01-24 23:43
@abimelex thanks for the clarification.

By [connected] I meant that the post's owner is in your contacts.

Now, I can confirm that the bug occurs when you unlike a post owned by a user who is not in your contacts.

I'll try to send a fix for this issue as soon as possible. 

Thanks,
Sayed

**Comment by visualsayed** [comment] 2016-01-26 00:58
@abimelex , It turns out that deleting a comment on a public post fails too if the post's owner isn't in the commenter contacts or the commenter isn't in the post's owner contacts.

So Here the steps to reproduce both bugs:

Given two not-connected users A and B:
1- As User A publish a public post.
2- As User B like the post and comment on it.
3- As long as User B isn't in user A contacts or User A isn't in user B contacts, User  B wont be able to unlike the post or delete his own comment.

The expected behaviour:
Given that the post is public then User B should be able to unlike the post and delete his comment without having to add User A to his contacts.

Thanks,
Sayed

**Comment by visualsayed** [comment] 2016-01-26 02:14
@abimelex, @jhass 

In diaspora both like and comment are Relayable objects and the actions of unliking a public post or deleting a comment are delegated to the User.retact instance method.

While the User.retact method is in charge, it does the following:

- Builds RelayableRetraction object.
- Builds Postzord::Dispatcher object, that returns an instance of Postzord::Dispatcher::Private then send the [post] message to this instance.
- The post method of Postzord::Dispatcher::Private executes post_to_subscribers on self which in turns executes deliver_to_local on self 
- deliver_to_local starts a sidekiq worker then Workers::Receive.new.perform is invoked
-  The perform method of  Workers::Receive instance invokes suppress_annoying_errors (which is inherited from Workers::Base to catch raised exception) with a block that instantiate an instance of Postzord::Receiver::Private then invokes parse_and_receive method on this instance
- Finally the parse_and_receive methods invokes validate_object method on self which raises Diaspora::ContactRequiredUnlessRequest exception and prevent the retraction of the RelayableRetraction object.

In our example of unliking a public post or deleting a comment on it, the method contact_required_unless_request in Postzord::Receiver::Private class ensures that the post's owner has the author in his contact otherwise   Diaspora::ContactRequiredUnlessRequest is rasied.

The current implementation of this method:
```
def contact_required_unless_request
    unless @object.is_a?(Request) || @user.contact_for(@author) || (@author.owner && @author.owner.podmin_account?)
      logger.error "event=receive status=abort reason='sender not connected to recipient' type=#{@object.class} " \
                   "recipient=#{@user_person.diaspora_handle} sender=#{@author.diaspora_handle}"
      return true
    end
  end 
```
A possible fix is to check if the RelayableRetraction object's parent is public and if it is return false from contact_required_unless_request which means that contact is not required, a suggested implementation look like this:

```
def contact_required_unless_request
    unless @object.is_a?(Request) || @user.contact_for(@author) || (@author.owner && @author.owner.podmin_account?) || relayable_with_public_parent?(@object)
      logger.error "event=receive status=abort reason='sender not connected to recipient' type=#{@object.class} " \
                   "recipient=#{@user_person.diaspora_handle} sender=#{@author.diaspora_handle}"
      return true
    end
  end 

def relayable_with_public_parent?(object)
  object.respond_to?(:relayable?) && object.relayable? && object.parent && object.parent.respond_to?(:public?) && object.parent.public?
end

private :relayable_with_public_parent?
```

Thanks,
Sayed

**Comment by svbergerem** [comment] 2016-01-26 12:10
Sounds like a duplicate of #4727.

**Comment by visualsayed** [comment] 2016-01-26 14:10
Agree, it is a duplicate.

**Closed** 2016-01-26 14:41 UTC

**Comment by visualsayed** [comment] 2016-01-28 05:29
@denschub  I revisit this and now I think that this one is a bug while the #4727 is a feature.
