### ISSUE TITLE
Name and bell do not turn back grey

### ISSUE THREAD

**Issue by maliktunga** [diaspora/diaspora#6264] opened 2015-07-28 22:12 UTC
Issue:
1. Log into https://social.mrzyx.de
[The name is grey]
2. Click on your name in the upper right corner (black bar)
[The name on hover becomes white]
3. Click on your name again
[The name is still white]
4. Move the cursor away from the name

What is expected: the name becomes grey
What happens: the name is still white

The same happens with the bell icon (Notifications)

Set-up: Diaspora Code 0.5.99.0-p0713edaf on https://social.mrzyx.de
Firefox 39.0 on Fedora 22

**Comment by jhass** [comment] 2015-07-28 22:21
Duplicate of #6137

**Closed by jhass** 2015-07-28 22:21 UTC
