### ISSUE TITLE
followed tags don't work anymore?

### ISSUE THREAD

**Issue by faustdotmef** [diaspora/diaspora#4503] opened 2013-09-07 09:10 UTC
i had account at diasp.org and dropped it because it didn't show posts with tags i followed. i thought it's problem of diasp.org but now i see that my new account don't show posts with followed tags anymore as well. and i saw few posts with #bug who have this trouble.
##

**Comment by svbergerem** [comment] 2016-12-05 00:53
Is anyone still able to reproduce this?

**Comment by svbergerem** [comment] 2017-03-16 13:57
There was no answer for more than 3 months, so I'll close this issue.

**Comment by SuperTux88** [comment] 2018-02-15 16:37
I'm reopening this, because I now had this once too. I had a reshare of a post in my stream, but since I follow the #diaspora tag (with which the original post was tagged) the original post should be in my stream too, but wasn't (should be right below the reshare). The reshare was the eleventh post from the top in my stream, so not at the break between too batches. The next post was more than 20 minutes older than the original post, while the reshare was 15 minutes newer then the original, so it should definitely be between these two posts.

I try to debug and reproduce this later.

**Comment by SuperTux88** [comment] 2018-02-15 17:09
OK, now as soon as the reshare is the fifteenth post (the last of the batch), the missing post is in the next batch (there were even more posts missing I didn't notice).

**Closed** 2018-02-25 03:36 UTC
Labels: bug, data issue
