### ISSUE TITLE
Empty private conversation

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5903] opened 2015-04-29 09:14 UTC
![capture du 2015-04-29 11 07 26](https://cloud.githubusercontent.com/assets/930064/7387877/3228548e-ee61-11e4-9be4-b620bab77107.png)

There is not content in the conversation created by @jaywink, and it's displayed third. It's not the first time I have this bug in d-fr. Nothing in the JavaScript Console and I have no idea what I should try to grep in the log.

**Comment by Flaburgan** [comment] 2015-04-29 09:22
Looking in the DB, there is not message linked to the conversation.

**Comment by denschub** [comment] 2015-04-29 10:48
dupe of #5103.

**Closed by denschub** 2015-04-29 10:48 UTC

**Comment by jaywink** [comment] 2015-05-01 11:17
Couldn't find anything in the logs on my side :( Another conversation failed too, Augier reported from d-fr.

@Flaburgan did you check your sidekiq log from this period?

**Comment by Flaburgan** [comment] 2015-05-01 14:45
Could you please give me the exact time you posted the message?

**Comment by Flaburgan** [comment] 2015-05-01 14:53
So you organization message also is empty. Sent today at 12:43:13. Here is what I found in production.log:

```
user:1 starting private receive from person:7ed1555bc6ae03db
event=verify_signature status=complete guid=a4168010d21c013260f16c626dd55703 validity=true

Sent mail to diaspora@pi-et-ro.net (67.2ms)
Failure to receive Conversation from sender:7 for user:1: Validation failed: Parent is invalid
#<Conversation id: nil, subject: "Organization", guid: "a4168540d21c013260f16c626dd55703", author_id: 7, created_at: "2015-05-01 10:42:08", updated_at: nil>
failed to save received object: ["Parent is invalid"]
```

**Comment by Flaburgan** [comment] 2015-05-01 15:09
Ok I continue to grep, here is what I found sooner this morning:
```
user:297 starting private receive from person:7ed1555bc6ae03db
user:1 starting private receive from person:7ed1555bc6ae03db
user:297 starting private receive from person:7ed1555bc6ae03db
event=verify_signature status=complete guid=73fab680d21c013260f16c626dd55703 validity=true
event=verify_signature status=complete guid=a4168010d21c013260f16c626dd55703 validity=true
event=verify_signature status=complete guid=a4168010d21c013260f16c626dd55703 validity=true
Failure to receive Message from sender:7 for user:297: Validation failed: Parent is invalid
#<Message id: nil, conversation_id: 1783, author_id: 7, guid: "73fab680d21c013260f16c626dd55703", text: "Fla and Augier didn't get the conversation due to ...", created_at: "2015-05-01 10:40:48", upd
ated_at: nil, author_signature: "TB2gGCo0pU8e34hxn3mK/Boi03gWRT1NdB2Xe5xvPLZnWL3O8K...", parent_author_signature: "TB2gGCo0pU8e34hxn3mK/Boi03gWRT1NdB2Xe5xvPLZnWL3O8K...">
failed to save received object: ["Parent is invalid"]
Failure to receive Conversation from sender:7 for user:1: Validation failed: Parent is invalid
#<Conversation id: nil, subject: "Organization", guid: "a4168540d21c013260f16c626dd55703", author_id: 7, created_at: "2015-05-01 10:42:08", updated_at: nil>
failed to save received object: ["Parent is invalid"]
Failure to receive Conversation from sender:7 for user:297: Validation failed: Parent is invalid
#<Conversation id: nil, subject: "Organization", guid: "a4168540d21c013260f16c626dd55703", author_id: 7, created_at: "2015-05-01 10:42:08", updated_at: nil>
failed to save received object: ["Parent is invalid"]
```

I'm the user 1 and user 297 is augierle42e.

**Comment by jaywink** [comment] 2015-05-02 11:03
I don't get what `Parent` here refers to. I don't really seem to find anything that matches that description for conversations.

@jhass any idea? The error is coming afaict from ActiveRecord, here https://github.com/jaywink/diaspora/blob/develop/app/workers/base.rb#L19-19

**Comment by jhass** [comment] 2015-05-02 11:55
I'd have to trace through the code, I suspect it's an included Message that throws the visible validation error (https://github.com/diaspora/diaspora/blob/develop/lib/diaspora/relayable.rb#L16) and we don't see why the Conversation didn't save.

**Comment by jaywink** [comment] 2015-05-02 12:23
Seems like there is 3 sidekiq jobs, the first one says "Failed to receive Message" and *has* a conversation_id. The next two say "Failure to receive Conversation". Don't quite follow the logic here, but there *IS* a conversation created in the first job since otherwise @Flaburgan would not see it in the UI :P

@Flaburgan do you have sidekiq debug logging on? I'd assume something would show there too, not just production.log. If not, can you turn it on?

**Comment by Flaburgan** [comment] 2015-05-02 17:33
I have a sidekiq.log file but I have found nothing in it grepping for your id `7ed1555bc6ae03db` or the message guid `a4168540d21c013260f16c626dd55703`. Where did I set the log level?
