### ISSUE TITLE
Users who reshared don't get federated

### ISSUE THREAD

**Issue by TheRadialActive** [diaspora/diaspora#6000] opened 2015-05-27 15:30 UTC
As you can see on the screenshots, the list of users who reshared the post are different on two different pods (click on the image to get to the post).

[![bildschirmfoto vom 2015-05-27 17-26-10](https://cloud.githubusercontent.com/assets/828436/7839980/96768542-0495-11e5-9eb9-853fab185c3f.png)](https://pod.geraspora.de/posts/3665409)

[![bildschirmfoto vom 2015-05-27 17-26-42](https://cloud.githubusercontent.com/assets/828436/7839981/9697d8dc-0495-11e5-98b1-76b303594bf5.png)](https://nerdpol.ch/posts/1652700 )

**Comment by jhass** [comment] 2015-05-27 15:36
Do you happen to have the guid (or id on either pod) of the reshare and the original post?

**Comment by svbergerem** [comment] 2015-05-27 15:59
@jhass The screenshots link to the posts. The guid of the original post is `5eba0c00e6b00132ae7000505600750e`. Guids of two reshares are `67f02880e6b10132c1f252540061b601` and `aa36a7f0e6b00132ae7000505600750e`.

**Comment by jhass** [comment] 2015-05-27 16:19
Oh, I didn't realize. @denschub & @SuperTux88 up for some log surfing?

**Comment by SuperTux88** [comment] 2015-05-27 16:51
I don't know if this helps: http://paste.coding4.coffee/?a59a1400c0a01b5e#lHWL/AVefuGBwvY0VdfXv4VzF+YNeddgE60O5S1OTUw=

**Comment by jhass** [comment] 2015-05-27 17:09
Thanks. Not really, it just shows that your pod got it successfully.

**Comment by denschub** [comment] 2015-05-27 23:25
As far as I can tell, I never recevied that reshare, so it's likely an issue on `spora.zone`. However, I don't feel like we need an issue for every federation issue that happens at the moment...

**Comment by jaywink** [comment] 2015-10-09 22:22
Did some testing between up to date develop pods:

Post in iliketoast.net
Reshare on diaspora-fr
Reshare of Reshare on diaspote.org
Reshare of Reshare on sechat.org
Reshare of Reshare on babillage.org

Result was:
* iliketoast received all 4 reshares
* diaspora-fr received all reshares except sechat
* sechat didn't receive any of the reshares
* diaspote received diaspora-fr reshare
* babillage received diaspora-fr reshare

The explanation is in followers I think:

toast:
 - dfr

dfr:
 - toast
 - diaspote
 - babillage

diaspote:
 - dfr

babillage:
 - dfr

sechat:
 - toast

So as you see, it matches quite closely (as far as my brain functions after going through so many pods and posts) to who follows who. A reshare is posted out to "contacts + original root" so this afaict works as it should.

**Comment by jhass** [comment] 2015-10-09 22:29
Yeah, it's probably works as intended, feel free to close it. And anybody who can provide something like the above demonstrating faulty behaviour, feel free to open  a new issue.

**Comment by jaywink** [comment] 2015-10-09 22:58
So, closing. Please reopen if you have a reason to think reshares are not being federated by the current way, ie "*to contacts of reshare making user + original root author*".

**Closed by jaywink** 2015-10-09 22:58 UTC
Labels: federation, needs more info
