### ISSUE TITLE
Post visible for mentioned people - Post was NOT shared with them!

### ISSUE THREAD

**Issue by Faldrian** [diaspora/diaspora#4160] opened 2013-05-20 21:04 UTC
We hat a serious bug on Diaspora 0.1.0.0 - a user created a post, shared with an aspect that did not contain Person A.
Person A was mentioned in the post and hat the post delivered to his stream, despite the post was not shared with him.
Person A could not comment or like the post and the single-post-view was not loaded, a white page was shown instead.
Person A did receive a mention-notification.

Desired Behaviour: The post should not be visible to the mentioned person and the person should not receive a notification - unless the person is in the choosen aspect or the post is public.

**Comment by cmrd-senya** [comment] 2016-07-01 02:28
Working on #1851 I noticed, that this issue actually exist now (tested on diaspora-fr.org and diasp.org).

Here on the screenshots you may see, that I managed to mention `senya2@diaspora-fr.org` from `senya@diaspora-fr.org` within a limited post even without having sharing relationships between the senyas and `senya2@diaspora-fr.org` may see that post in his stream.

Post with a mention:
![2016-07-01 05 23 01](https://cloud.githubusercontent.com/assets/10187586/16510110/f829742e-3f4b-11e6-8d85-1547c67b4d52.png)

Here you may ensure there is no sharing:
![2016-07-01 05 23 08](https://cloud.githubusercontent.com/assets/10187586/16510111/f842ffe8-3f4b-11e6-844a-b77e6fdab2fe.png)

**Comment by cmrd-senya** [comment] 2016-07-01 22:34
I guess this issue has to be reopened. This was closed as a duplicate of #2516, however #2516 is not there and at the same time, all the other symptoms described in the original message are here, except Person A doesn't get notification. [The test](https://github.com/diaspora/diaspora/blob/develop/spec/integration/mentioning_spec.rb) that has to prove the fix is actually invalid now. The issue is that in the test the `StatusMessage` is created using `User.build_post.save!` and it is different from how actually the `StatusMessage` is instantiated -- the `StatusMessageCreationService` is used. The approaches differ in a way they deal with aspect visibilities. This difference resulted in the test passing while actually the issue persisted. I [fixed](https://github.com/cmrd-senya/diaspora/commit/43cbdbf13990fa0da4befd849a1212ffdf01c88e) the test to use POST request instead as in real life, and now it fails, as expected.

I would propose a fix for that, but I'm planning to leave for a week. If nothing changes in that time, I'll write a patch just after my return.

This also blocks #6818 for me.

**Comment by Flaburgan** [comment] 2016-07-02 09:50
We definitely need a way anyway to tell the user that something unusual is happening. We should at least warn him "Warning, you're mentioning someone who doesn't have access to the post you are writing, he will not be notified". We should do that check when the user clicks on publish because he usually wrote the post (when the aspect selector is set on "All aspects") and then change the visibility just before posting. So can't do that when he writes the mention.

**Comment by denschub** [comment] 2016-07-02 10:04
Actually, nah. Let's keep this closed and open a new issue. The initial problem was a different and a lot of this discussion is outdated and irrelevant nowadays.

**Closed by denschub** 2016-07-02 10:04 UTC
Labels: bug, confirmed
