### ISSUE TITLE
/contacts page is really slow

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#6107] opened 2015-06-15 22:52 UTC
It takes ~30 seconds to load with 1800 contacts and goes to a 504 timeout with 16k contacts.
I'm not sure it was like this before the 0.5.1.0.

**Comment by denschub** [comment] 2015-06-26 02:09
This is a regression of 9de6a26a221d1f874e1e036a87512484368a6313. At [app/controllers/contacts_controller.rb#L43](https://github.com/diaspora/diaspora/blob/9de6a26a221d1f874e1e036a87512484368a6313/app/controllers/contacts_controller.rb#L43), we iterate over all contacts to get a representation for gon, which obviously is very bad if you have more than a few contacts...

@svbergerem since this is your work... any ideas? I guess AJAXing the contacts in small batches would be much better.

**Comment by svbergerem** [comment] 2015-06-26 07:37
@denschub Sure. One would have to make sure that infinite scroll and contact search are still working.

**Comment by piraz** [comment] 2016-01-22 17:53
@denschub It seems like gon.watch was made for that. https://github.com/gazay/gon/wiki/Usage-gon-watch

**Comment by jaywink** [comment] 2016-01-22 20:13
Why don't we just paginate?

**Comment by piraz** [comment] 2016-01-22 22:14
After looking at the gon.watch, it seems like this feature is for update values that change constantly and not paginate.

**Comment by Flaburgan** [comment] 2016-01-24 09:17
@jaywink because we have a filter input at the top. As it is working right now, it's plain JS without Ajax, so it needs to have the full list of users.

Currently, with 1631 contacts, the `contacts.html` is 1237ko.
I don't know how Gon works, but I thought about this problem and it looks like we have two solutions:
- We could filter server side, only asking for 20 contacts at each request (infinite scroll) and indicating the content of the search field in the request for the server to filter the contacts.
- We could only load the username and the diaspora* ID of every contact to still be able to filter client side but without loading every data of every user. Then make another request to get the missing data for the matched users.

Not sure which one is the best.

**Comment by jaywink** [comment] 2016-01-24 11:43
Well, pagination still works if you operate on a smaller set of data. The search of course would then be not ajax but would send the query and reload the page.

Of course that is more changes I guess, but currently it is totally unusable. I have almost a 1000 too and I can't manage my contacts any more so I just don't even try.. :P

**Comment by piraz** [comment] 2016-01-25 00:11
Why we don't start to cache some big data sets on redis? I think we could get those big datasets read-only but ready to snapshot queries.

We have redis installed as prerequisite anyway. TheRealTalk processes about 1.8 million tasks/month  and redis is still idle. Maybe we could start get some experience on caching this massive query and than start to cache(option, maybe?) other things.

I'm down to get this project as tutorial as my podmin cannot even touch on this page right now.

**Comment by piraz** [comment] 2016-01-31 17:13
It seems line the contacts for mobile has pagination.
Maybe I can start from there.

**Comment by svbergerem** [comment] 2016-01-31 17:15
The mobile page has no contact filtering. Neither pagination nor filtering is hard. Doing both properly at the same time is what makes this issue hard to fix.

**Comment by piraz** [comment] 2016-02-17 20:23
The mention feature on the post text box is affected by the number of contacts. Should we open a new issue for that?

**Comment by AugierLe42e** [comment] 2016-02-17 20:32
Nope. #6537 is probably going to solve that.

**Comment by cmrd-senya** [comment] 2016-08-16 09:24
Does anyone work on fixing this?

**Comment by jhass** [comment] 2016-08-16 09:30
I think Steffen mentioned something about using the new contact search route for the search and pagination/infinite scrolling for the list. Not sure whether he started work on that already though.

**Comment by svbergerem** [comment] 2016-08-16 09:55
My last idea was the following:

1. Remove the current search on the contacts page
2. Modify the contacts page code to use pagination/infinite scrolling instead of loading all contacts and aspect memberships
3. Implement a new search for the contacts page by adding a search bar that opens a new search page after hitting return. Modify the current contact search to return aspect memberships when some parameter is set and use that search + pagination/infinite scrolling for the search page.

All I did so far is step 1, so if you want to work on this then this issue is yours. ;) Otherwise I'll try to work on this when I have enough time.

**Comment by svbergerem** [comment] 2016-08-16 10:01
Since the people search now also includes contacts we might even consider dropping the search from the contacts page.

**Comment by cmrd-senya** [comment] 2016-08-16 10:20
> if you want to work on this then this issue is yours. ;)

Let me study the issue and consider my resources first

**Comment by Flaburgan** [comment] 2016-08-16 11:34
>Since the people search now also includes contacts we might even consider dropping the search from the contacts page.

+1 to find a way to unify search and contacts management. This was discussed in #4773.

However even if I approve this idea I feel like it's maybe not the time to do it, we'd like to freeze this weekend and this solution needs both time and thinking to be done correctly. Maybe we can find an easier workaround to be able to release 0.6 first and then work on this without pressure?

**Comment by svbergerem** [comment] 2016-08-16 11:43
@CSammy suggested on the IRC channel to keep the search bar but send users to the people search page once they hit return. We would only need an additional parameter there (`only_contacts`?) and use it in the `Person.search` call. I suggested this solution because I'd still consider combining pagination and filtering contacts like it works right now a problem that is harder to solve and needs more time and thinking.

**Comment by Flaburgan** [comment] 2016-08-16 11:47
Maybe we could `order by` contacts first instead of only contacts in the search page?

**Comment by cmrd-senya** [comment] 2016-08-16 12:23
It's still not quite clear to me. If we just implement pagination on `/contacts` and remove gon preload of contacts, what would break?

We have a search bar on every page that works in the same manner. Why we should change anything on contacts page specific for the search bar, if it works fine on every other page?

**Comment by jhass** [comment] 2016-08-16 13:29
The current contacts search searches through the currently displaced contacts only, not the ones on the next loaded page.

**Comment by cmrd-senya** [comment] 2016-08-16 13:35
Then contacts are loaded similary on every page, since we have the search bar everywhere? Why doesn't it make every page slow then?

**Comment by jhass** [comment] 2016-08-16 13:37
We're talking about the search on the `/contacts` page, not the one in the header bar.

**Comment by SuperTux88** [comment] 2016-08-16 13:43
There is a second search-field if you select one of your aspects (from the left sidebar on the contacts page), so you can filter your other contacts to add to this aspect. But to make this filter work, we load all contacts, what makes the contacts-pages slow. So if we just use the normal people search instead (maybe with a parameter to display only contacts?), we don't need to load all contacts.

**Comment by cmrd-senya** [comment] 2016-08-16 14:04
Ok, now it's clear, thanks!

I can work on it and I estimate that I can throw a PR by the end of the week considering [the workaround suggested](https://github.com/diaspora/diaspora/issues/6107#issuecomment-240078413). And proper search in contacts can be postponed after 0.6.0.0.

**Comment by SuperTux88** [comment] 2016-08-16 14:24
It would be good, if you have a PR before the end of the week, because it should be merged on friday (see [loomio](https://www.loomio.org/d/XBQ9Dbw5/comment/1100737): "If and only if #6107 is officially merged <= this Friday, I'll freeze 0.6.0.0 on this Sunday."). So we have still time for reviews.

**Comment by cmrd-senya** [comment] 2016-08-16 19:38
16.08.2016 17:25, Benjamin Neff пишет:
>
> It would be good, if you have a PR before the end of the week, because
> it should be merged on friday (see loomio
> <https://www.loomio.org/d/XBQ9Dbw5/comment/1100737>: "If and only if
> #6107 <https://github.com/diaspora/diaspora/issues/6107> is officially
> merged <= this Friday, I'll freeze 0.6.0.0 on this Sunday."). So we
> have still time for reviews.
>

I can do my best, but if there is someone who have resources to work on
it and confidence about the terms, then feel free to pick it.

And also: do we prefer pagination or infinite scroll? I'd vote for the
former.

**Comment by jhass** [comment] 2016-08-16 19:44
I think I would actually prefer infinite scrolling here.

**Comment by cmrd-senya** [comment] 2016-08-16 19:47
When I looked at the source code of `app.views.ContactStream` I saw that
it actually implements infinite scroll already, so I guess that the
better/easier way.

**Closed** 2016-08-18 06:47 UTC
Labels: confirmed, regression
