### ISSUE TITLE
when a mentioned user's profile is not known, request profile

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#5972] opened 2015-05-19 06:24 UTC
Currently when a user is mentioned (especially #newhere posts), other pods won't see a link to the profile. I think a pod should request profile of a user it doesn't know if when it processes a post with @mention in it.

**Comment by Flaburgan** [comment] 2015-05-19 07:02
I completely agree and thought I already opened an issue about that.

**Comment by pavi** [comment] 2015-05-19 08:20
I faced the same issue.

**Comment by jhass** [comment] 2015-05-19 08:36
Duplicate of #4491

**Closed by jhass** 2015-05-19 08:36 UTC
