### ISSUE TITLE
if I hashtag dandelion my post disappears down a black hole.

### ISSUE THREAD

**Issue by gravly** [diaspora/diaspora#7887] opened 2018-10-11 04:04 UTC
...and that is an exact description of my problem.  Some strange things:

- this occurs not just with the dandelion app, also posting to diaspora from both the desktop and mobile web client
- if I reproduce the #dandelion in the exact format dandelion uses to add tags to the footer of a post then the problem doesn't occur.  that is by using **Tags:** #dandelion (THIS TURNED OUT TO BE NOT FULLY ACCURATE - instead it's about the type of i in dandelion - see my next reply below)
- reporducible in all instances of posting public, or limited aspects

That points to a very strange filter rule operating at some level within the diaspora ecosystem.

I am a new member in the pluspora pod.

This is no hardship to workaround now I know what the problem is but I wasted quite a bit of time understanding why certain posts would seem to go through and then just fail to appear in my stream.

**Comment by Flaburgan** [comment] 2018-10-11 07:14
Hi and thank you for reporting an issue. There is no filter in diaspora so if the post is really disappearing, it is a bug.

However, I don't reproduce the problem. I just published [a post](https://diaspora-fr.org/posts/3776787) with the dandelion tag and it appears in my stream.

Can you please describe the exact steps you are following explaining what happens and what is expected **without using the dandelion app**? Thank you.

**Comment by gravly** [comment] 2018-10-11 09:47
Thanks for your response.  I can definitely consistently recreate this bug and write down the steps.  I'll try to do this soon.

In the meantime I have discovered why sometimes it works for me and sometimes it doesn't...

the autocreated #dandelion hashtag which the dandelion app auto inserts at the bottom of each message uses a strange small letter i in dandelion.  When I manually type #dandelion I don't get this strange i and that's when the post disappears.  It's almost like the dandelion app makers are aware of this diaspora bug and are working around it.  Here is a copy paste of the hashtag they use (look closely at the i)
#dandelíon

**Comment by Flaburgan** [comment] 2018-10-11 10:02
You said in your previous message that you were able to reproduce the problem posting from diaspora* itself. If that is still the case, please tell me the steps to reproduce. If you only have a problem within dandelion then please open an issue [in their repo](https://github.com/gsantner/dandelion). Thank you again.

**Comment by gravly** [comment] 2018-10-11 10:15
Android 7.0 on Zenpad3s 10

open chrome browser
go to pluspora.com (mobile interface opens)
login with my details
click button to create a new post
type anything at all
add a space or hit enter
type #dandelion
either Share now or add more text and hit Share
the progress bar appears to show the post successfully uploading

the post cannot be found in the profile or in the stream

this behaviour reproduces no matter what the surrounding text is, or how many times the hashtag is repeated, or whether there are other hashtags.  it also reproduces if I try sharing to different aspects, or to public.

alternatively repeat all the above steps except don't insert the dandelion hashtag (insert other hashtags if you wish)
hit Share
the post immediately appears in the stream, and can also be found on the profile by selecting that.

The behaviour is identical when  posting from the dandelion app itself.

Strangely as mentioned above, dandelion has a selection in settings which will automatically insert a dandelion hashtag as well as some other text and a link.  The option is called 'Append Shared By Notice'.

When I looked closely enough why the bug was not reproduced by this auto-added content I discovered dandelion developers use the hashtag #dandelíon

Notice the i is not an ordinary English language i.

If I copy this strange hashtag and repeat all the steps at the top of this post, and J stead of typing #dandelion, paste #dandelíon the bug is not triggered and the post appears as per normal.

**Comment by gravly** [comment] 2018-10-11 10:18
all of this behaviour was recorded using diaspora from the browser, not from the dandelion app.  however the dandelion app exhibits the identical behaviour.  hence my conclusion is that this is a diaspora issue, albeit a very weird one seemingly with some sort of unknown connection with the word dandelion.

**Comment by gravly** [comment] 2018-10-11 10:20
... a buffer or database got overloaded with dandelion hashtags maybe due to the apps auto-insert behaviour?  So then, the app developers selected a new hashtag which looks the same.  Just speculating.  I can't explain why you were not able to reproduce unless it is a pluspora issue and not a diaspora issue.

**Comment by Flaburgan** [comment] 2018-10-11 10:28
Can you please share your diasporaid (something like fla@diaspora-fr.org) here? And we also need to contact your podmin to search in the logs, as I definitely do not reproduce the problem.

**Comment by gravly** [comment] 2018-10-11 10:42
gray@pluspora.com

**Comment by gravly** [comment] 2018-10-11 10:47
my podmin will find a bunch of test posts I have done around this issue but should look closely for the strange i, as it is only those with the strange i hashtag which appear in my profile.  I can do a failed post if you like and record the time, if he needs this specific information to track it down.

**Comment by Flaburgan** [comment] 2018-10-11 10:49
Can you please do another failure post now that I am sharing with you?

**Comment by gravly** [comment] 2018-10-11 10:50
OK I will! do two posts and label one with the text failure and one with the text success.  You should only see the second one.

**Comment by gravly** [comment] 2018-10-11 10:52
done.  both shared public.  only one appeared, as expected.  posted within 30 seconds of each other.

**Comment by Flaburgan** [comment] 2018-10-11 10:57
Alright, indeed, I only see the "success" one. I pinged the podmin there, hopefully he'll be able to give us some hints as I have no idea what's going on.

**Comment by gravly** [comment] 2018-10-11 11:01
...so weird I feel like I need to make a screen recording to convince people I'm not mad!

More strangeness: the weird i on the "success" post looks like a normal i when I look at the public activity stream but when I click on my profile the weird i on the "success" post looks weird.

**Comment by gravly** [comment] 2018-10-11 11:02
anyway, thanks for your time and attention to this weirdness.  I'll let it go until someone else has something to add.  Have a great night/day wherever you are.

**Comment by Flaburgan** [comment] 2018-10-11 11:03
Thank you for reporting bugs. Hopefully your podmin will be able to help.

**Comment by Flaburgan** [comment] 2018-10-12 10:13
David found in the logs: `[2018-10-11T07:55:30] FATAL PID-3047 TID-46926468659380 Rails: ActsAsTaggableOn::DuplicateTagError (‘dandelion’ has already been taken)`

See [this diaspora conversation](https://diaspora-fr.org/posts/a2a09700af7101364741005056268def).

**Comment by Siedlerchr** [comment] 2018-10-12 15:08
I experienced the same just now from chrome at pluspora.com pod. In a comment when I try to post #dandelion I'll get a 500 server error and can't post. A different hashtag works

**Comment by AndreaBorgia-Abo** [comment] 2018-10-12 15:23
I wanted to ask a question related to Dandelion so naturally I've tried using the hashtag.
Firefox on Windows, using standard website layout
[error message](https://pluspora.com/uploads/images/scaled_full_0d90c953562079d20586.png)

**Comment by CSammy** [comment] 2018-10-13 09:52
I'll have a look into it.

**Comment by CSammy** [comment] 2018-10-13 12:11
This is most likely a collation-related error. I suspect the table in question is either still `utf8` for some reason, or its column `name` is `CHARACTER SET uft8mb4 COLLATE utf8mb4_unicode_ci`.

`*_unicode_ci` has the ugly habit to strip away accents and similar, meaning `dandelíon` becomes `dandelion` for the lookup via index, but is stored as `dandelíon`. As a consequence, (at least some) words with accents are considered to be equivalent to their counterparts without accents (`thé == the`) by the index, even though the difference is preserved in the actual storage. 

I have researched for a few hours and determined that a statement to change the collation of a column to the correct value of `utf8mb4_bin` would always rebuild the index. This means either the index was not rebuild due to a bug in MySQL (I doubt this one), or the collation on the particular column `name` was not changed. The latter again can be caused by the migration to change the collation (#5624) failing, or some completely different error taking place. Sadly, with all the migrations executed properly, I cannot reproduce this behaviour.

I was able to observe the behaviour after changing the collation by hand to `utf8mb4_unicode_ci`.

It would be good to have the podmin of pluspora.com participate here in order to be able to verify the status of the collation setting on the `name` column in the `tags` table. Fair warning to podmins: Please do not change anything in the database without getting back to us and doing extensive testing. It's easy to corrupt your database with ad-hoc changes and has happened to a few podmins already.

**Comment by Dartan** [comment] 2018-10-13 13:14
Sorry it's taken me so long to get here but I've been busy with some other things.

I did check and the collation is wrong on that table and the database too. Can I just do an alter database/table to fix it?

**Comment by 001101** [comment] 2018-10-13 21:17
Had the same issue on some posts on my pod that posts just disappeared after it was posted and I reloaded the site, but was only 2 times and now it is gone.

**Comment by CSammy** [comment] 2018-10-14 08:12
@Dartan Thank you for chiming in!

Well, if it is wrong for the entire database, something went seriously wrong with the migration that was supposed to fix this (20150106050733), or, if your pod is newer than 2015, then something went wrong with the database setup. Did you create your database/"schema" manually by chance? If so, that is probably the culprit. I'm investigating right now how to fix this without breaking everything.

**Comment by CSammy** [comment] 2018-10-14 09:28
@Dartan Please state the exact character set and collation combination your database is currently on, so we can map out the appropriate actions.

**Comment by Dartan** [comment] 2018-10-14 11:48
The default collation of the database is utf8_general_ci and the default characterset is utf8.
For the tags.name the collation is also utf8_general_ci and the character set is utf8.
For the posts table there are several fields with utf8_general_ci and utf8. (which I suspect is what is causing the issue with emojis).
In my database.yml it does list the collation as utf8mb4_bin and the encoding as utf8mb4. Not sure why it doesn't match what the database actually is.

Also, while I don't have much experience with mysql I do have 20+ years with mssql so if you need me to run any queries, just let me know. I suspect I'll have to change the default collation/encoding of the database and then each table/field individually.

**Comment by CSammy** [comment] 2018-10-14 16:40
> In my database.yml it does list the collation as utf8mb4_bin and the encoding as utf8mb4. Not sure why it doesn't match what the database actually is.

You created the database yourself, that is why :disappointed: 

I will get back to you as soon as I have a set of commands you can issue to fix this. Expect quite some downtime, as all text fields need to be changed which will require restructuring on the storage level for every involved table. I recommend you prepare a test copy of your database in order to test the commands we will share before issuing them on your production setup.

By the way, you are right in assuming this is also responsible for issues with emoticons.

**Comment by Dartan** [comment] 2018-10-14 16:42
Thank you so much for your help with this. I really appreciate it!

**Comment by denschub** [comment] 2018-10-14 17:09
Okay, at this point, you should probably move to Discourse. Initially, I figured I'd let this discussion stay here, but it now looks a bit different.

This issue here is caused by @Dartan manually creating the database, not letting `rake db:create` do this job. As such, this is kinda horrible, but migrating from `utf8` to `utf8mb4` is something we did in the past, and might actually have to do again in the future, as people tend to casually ignore installation docs. As such, having a thread in the [podmin support category on Discourse](https://discourse.diasporafoundation.org/c/support/podmin-support) is a good place to document the steps involved, so we can more easily find it and refer people to it, if needed.

@Dartan do you mind creating a topic on Discourse in that category titled something like "Help migrating a MySQL database from utf8_general_ci to utf8mb4_bin"? You don't need to write much in the text, just explain that you currently have an `utf8_general_ci` database and want help migrating it. You two can then continue that work over there, where it actually belongs, and where people will find it in the future. :)

@CSammy thanks for your work here, this is much appreciated. 🍪 

---

As this should be continued on Discourse, I'll close this issue. Remember that closing an issue is not locking it, so if there is an actual reason to continue here, feel free to do so. :)

**Closed by denschub** 2018-10-14 17:09 UTC
Labels: needs more info, setup issue, weird

**Comment by CSammy** [comment] 2018-10-15 13:37
Linking the [concluding Discourse thread](https://discourse.diasporafoundation.org/t/help-migrating-a-mysql-database-from-utf8-general-ci-to-utf8mb4-bin) for reference.
