### ISSUE TITLE
Facebook rejected app integration for publish_actions

### ISSUE THREAD

**Issue by Zelex** [diaspora/diaspora#5085] opened 2014-07-24 00:29 UTC
Web
For the login dialog, please use the JavaScript SDK without specifying an explicit display type. If you have special requirements precluding use of the SDK, set height and width on your window.open() call to properly size the dialog. People must have the complete option to change their audience settings. Learn more about Facebook Login.

**Comment by TwizzyDizzy** [comment] 2015-01-16 22:42
Well... that is odd. I just tried to re-submit my application for publish_actions (detailing the above facts) and therefore tested whether it still does not work. Obviously it did work -  as you can see:

  https://www.facebook.com/permalink.php?story_fbid=1528305794106210&id=100007804127198&pnref=story

The facebook app created for my diaspora pod obviously still has no publish_actions permission.

I am somewhat puzzled...

**Comment by jaywink** [comment] 2015-01-16 22:46
Well they never before requested "publish_actions" - and that has never been a part of our instructions. At some point people started saying new integrations cannot be made without this permission which never before was required. I'm still guessing it's not requested and podmins just assume it's required ;)

**Comment by TwizzyDizzy** [comment] 2015-01-16 22:52
I, in fact, assumed that we need that permission, obviously because the post I made back then had not been posted to facebook.

So we're basically back to Post #1, because the error itself is still displayed (I just verified that).

I am kind of embarassed for making such a fuss.

**Comment by jaywink** [comment] 2015-01-16 23:05
I hope you were wrong and no such permissions are required ;) And no worries, no need to be embarrased about anything. :dancer: These things happen all the time..

@Zelex would you like to try crossposting *without* this permission, ie [strictly following the guide](https://wiki.diasporafoundation.org/Integrating_other_social_networks#Facebook) in our wiki and just 1) creating the app, 2) adding keys to diaspora config, 3) connecting diaspora account to facebook account and 4) crossposting?

**Comment by Flaburgan** [comment] 2015-01-18 21:17
@jaywink I think we need the permission, the facebook API changed and is now the 2.0, the 1.0 is not working anymore. Btw I'm not even sure that we are compatible with the 2.0 API see https://github.com/diaspora/diaspora/issues/5260

**Comment by jaywink** [comment] 2015-02-09 20:59
Well I just went through the effort of creating a pod, creating a facebook app and following our wiki to make the integration - and everything worked smoothly - *there was at no point any need to submit anything for review*.

![](http://i.imgur.com/yRMHlqa.png)
![](http://i.imgur.com/QHbYmbP.png)

So closing this unless someone can prove that our current documentation is somehow out of date and publish_actions needs to be requested.

**Comment by qtheuret** [comment] 2015-02-10 09:47
@jaywink Did you try to link your Diaspora account with a Facebook account that is not an administrator of the Facebook application ?
I did that and if I link my Diaspora account with a Facbook account that is an administrator of the FB app, it works well but if I link it with a normal Facebook account, no message were sent to Facebook.

**Comment by jaywink** [comment] 2015-02-10 20:02
@qtheuret OK I'll try that too and report back.

**Comment by jaywink** [comment] 2015-03-10 10:41
Reopening due to popular demand. Several reports indicate @qtheuret is correct, didn't have time to test myself.

**Comment by jaywink** [comment] 2015-03-10 10:43
Btw, this is more of a documentation issue, not a code issue. This should be closed once the wiki instructions are fool proof.

**Comment by qtheuret** [comment] 2015-03-10 11:02
To add more information to solve this issue, I read this on http://www.nextscripts.com/instructions/facebook-social-networks-auto-poster-setup-installation/ :
> [Update – May 2014] Facebook changed some rules regarding the apps. This means that the Facebook App, Facebook profile or page and the user who authorizes the app MUST belong to the same Facebook account. So please make sure you are logged to Facebook as the same user who created the app.

**Comment by Anime-Machina** [comment] 2015-04-04 16:19
Well it seems I was right after all after a whole discussion of 'Yes' and 'No' and a shit ton of anger (Sorry still pissed off about it and I won't call their names right @jaywink ). Also when confronting of a new fact which did not quite taken serious with 'corrections' towards me from @jhass  wile it was a literal copy/paste from Facebook. At least we got this stuff got out of the way and yet I want to throw in another issue which came on 28th of March.

As of March 28 Facebook has rolled out Facebook API V2.3 (Bit earlier but the rules apply from 28th) they have applied several **NEW** rules. There is a **requirement** of having a **Java SDK** which is connected straight to **Facebook** their tracking system. This includes having a **'Signup with Facebook!'** on the landing page and a bonus of privacy stab in the back you have to install **Facebook Java SDK** which has the ability to track the activity on your pod. As a joke on 1st of April of team@pod.geraspora.de at 'post guid' **posts/a0b4d6f0ba3e013283b04860008dbc6c** came quite close to what the features of the **Java SDK** offers (feel the irony?).

**Every thing in a list:**

- You are required to have a **Sign up with Facebook** button on the landing page,
- Install **Java SDK** from Facebook,
- Agree with their "Privacy Policy",
- Allow them to track your users and your self on Facebook.

This info came from an old friend that continuously makes money with Facebook apps. And he has recently informed a lawyer for an explanation which I got confirmed trough phone. Because of the reason I kind of felt stabbed in the back (last time and I am still feeling it) you have to verify it your own at http://developers.facebook.com / Well known privacy policy. Or simply use a search engine or ask a common developer from Facebook which is already familiar with this system and policies (what I did).

**Comment by CannyFoxx** [comment] 2015-04-27 04:00
I turned off facebook api on my pod. Not working anyway. Facebook have a very aggressive policy of spying

**Comment by jaywink** [comment] 2015-04-27 12:21
It's unlikely there will be an easy permanent fix for allowing pod users (not app owner) to post to facebook via diaspora.

The only real option we have then is to make sure we don't show the "connect with facebook" button in the d* UI if there is possibility for users to post. I was thinking we could add a third setting to the Facebook services setting in `diaspora.yml` called `visibility` with options `false`, `all` or a *username*. False would mean it the buttons is not visible of course, `all` would mean the podmin has checked the FB app permissions (`publish_actions`) and thus guarantees the service works for all users. As a third option, a username can be provided, who the button would show for. This is expected to be the user who has created the FB app, since this user can *always* post, as has been tried.

This would allow podmins to set themselves cross-posting without having to worry about allowing non-working service linking to other users on their pod.

I can gladly do the change, if no one opposes. This would mean all podmins would need to check their current FB app when the change is deployed and set the correct value. Then we would really be able to tell users which pods really have working FB link, since some have the approval done already.

**Comment by denschub** [comment] 2015-05-25 02:21
Closing this. Additional configuration available with 7c0e50c2c270e696b7dbd6540d00b4cc38e25375, additional information regarding this change and issues is above. Feel free to reopen if you feel the urge of doing so.

**Closed by denschub** 2015-05-25 02:21 UTC
Labels: confirmed, documentation, services
