### ISSUE TITLE
opera failure

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6808] opened 2016-04-20 18:34 UTC
Unable to sign-in using opera web browser.

Access possible using firefox, xombrero
Unable to sign-in using opera, lynx, elinks, icecat

**Comment by jhass** [comment] 2016-04-20 18:49
Can't reproduce with Opera 36.0.2130.65

**Comment by githubgnulinux** [comment] 2016-04-20 21:38
Reproduce with icecat?

**Comment by jhass** [comment] 2016-04-20 21:50
See #6194 for Icecat, you opened this for Opera, let's keep on focus.

**Comment by denschub** [comment] 2016-04-21 03:36
duplicate of #6775, #6194 and #5906. If you disable JS, stuff won't work.

**Closed by denschub** 2016-04-21 03:36 UTC
Labels: needs more info
