### ISSUE TITLE
push for LibreJS compliance

### ISSUE THREAD

**Issue by pizzamaker** [diaspora/diaspora#6098] opened 2015-06-13 14:41 UTC
According to LibreJS, some of the JavaScript required to load Diaspora is unfree. That's either because LibreJS doesn't know that the scripting is free or because the JavaScript code used really is proprietary.

IMO this should be fixed, as some free software supporters avoid Diaspora for this reason.

**Comment by jhass** [comment] 2015-06-13 14:43
Duplicate of https://www.loomio.org/d/Wv4XnypZ/make-diaspora-work-with-librejs

**Closed by jhass** 2015-06-13 14:43 UTC
