### ISSUE TITLE
When uploading too many photos, they overflow and block the text box.

### ISSUE THREAD

**Issue by johannesgunnar** [diaspora/diaspora#5610] opened 2015-01-31 22:38 UTC
When uploading a lot of photos to stream, they take up the whole text box, blocking the text. (on Ubuntu 14.04, Firefox 35.0.1, JoinDiaspora)
![screenshot - lau 31 jan 2015 - 22 17 36](https://cloud.githubusercontent.com/assets/2924543/5990093/8e0c9c18-a999-11e4-849b-8d830696d9b1.png)

**Comment by jhass** [comment] 2015-01-31 22:45
Duplicate of #3098

**Closed by jhass** 2015-01-31 22:45 UTC
