### ISSUE TITLE
accessibility of signup page

### ISSUE THREAD

**Issue by RichMorin** [diaspora/diaspora#7973] opened 2019-02-01 01:51 UTC
The signup mechanism is unusable by the blind, as it requires the user to read distorted text from an image. In the short term, what workarounds are there other than requesting sighted assistance? Longer term, there needs to be a discoverable and accessible alternative.

**Comment by jakehell** [comment] 2019-02-12 12:51
It doesn't seem like the library that diaspora is using for captcha has a non visual option, like audio (https://github.com/galetahub/simple-captcha).

**Comment by goobertron** [comment] 2019-02-12 13:46
There's a long-standing issue about making the captcha accessible (#5043). Sadly no one has found or offered the right solution yet. It would be wonderful if someone would work on making diaspora\* UI more accessible throughout.

**Comment by SuperTux88** [comment] 2019-02-12 15:48
I'm closing this as duplicate of #5043.

**Closed by SuperTux88** 2019-02-12 15:48 UTC
Labels: accessibility
