### ISSUE TITLE
More intuitive share links

### ISSUE THREAD

**Issue by drhops** [diaspora/diaspora#3631] opened 2012-10-08 06:17 UTC
After signing up at joindiaspora.com, I wanted to share a post from my stream via its link, and it took me quite a while to find that "posted 33 minutes ago" was the link to the post.  Could we add a more intuitive post link icon or text?

**Comment by svbergerem** [comment] 2015-02-18 00:07
duplicate of #4975

**Closed by svbergerem** 2015-02-18 00:07 UTC
Labels: feature, ui
