### ISSUE TITLE
HTML tags intended as literal characters should be double-encoded in XML messages

### ISSUE THREAD

**Issue by MrPetovan** [diaspora/diaspora#8047] opened 2019-07-28 00:26 UTC
Related Friendica issue: https://github.com/friendica/friendica/issues/7433

Source Diaspora post: https://diaspora.kapper.net/posts/1816752#df609e90920e01372f02558e28f9c4e5
Received Friendica post: https://friendica.mrpetovan.com/display/df609e90920e01372f02558e28f9c4e5

Received XML message was:
```xml
<comment>
  ...
  <text>I prefer to think of a website as a book - on the home page(=cover) the &lt;h1&gt; is the name of the website
on the other pages (=chapter) the current page title is the &lt;h1&gt; and the name of the website is at the pageheader as an &lt;h2&gt; or normal paragraph (but still on first position)
...</text>
  ...
</comment>
```
However in this case it should have been:
```xml
<comment>
  ...
  <text>I prefer to think of a website as a book - on the home page(=cover) the &amp;lt;h1&amp;gt; is the name of the website
on the other pages (=chapter) the current page title is the &amp;lt;h1&amp;gt; and the name of the website is at the pageheader as an &amp;lt;h2&amp;gt; or normal paragraph (but still on first position)
...</text>
  ...
</comment>
```
To yield the correct display in remote clients.

**Comment by denschub** [comment] 2019-07-28 11:09
> However in this case it should have been: [...] To yield the correct display in remote clients.

What's your rationale behind this suggestion? [Our docs state that diaspora\* federates the text as Markdown, *not HTML*](https://diaspora.github.io/diaspora_federation/entities/status_message.html), and that's what we do. The only escaping done is to be able to wrap the text into XML, but that's about it. Markdown explicitly allows RAW, unescaped HTML in its content, [and if you look at the CommonMark spec](https://spec.commonmark.org/0.29/#raw-html), it expliclity states that even unknown HTML tags shall not be escaped. It could be argued that diaspora\*s frontend actually violates that, as we do escape tags we don't know and don't want to display, but I'm having trouble seeing anything wrong with our federation layer.

Isn't the issue more that you assume we federate HTML, when we, in fact, don't?

@SuperTux88 do you have an opinion here?

**Comment by MrPetovan** [comment] 2019-07-28 13:16
But the `<h1>` tag in the source message wasn't meant as "Raw HTML", rather as `literal chevron-h-1-literal chevron`. This subtlety is lost when sent over XML because we expect the content of the `<text>` tag to be HTML-encoded (to avoid a random `</text>` tag in the post body that could break the XML message structure for example).

So when we receive the raw XML message and unescape the content of the `<text>` tag, we're left with actual raw HTML tags that weren't the intent.

If you were sending the same body over JSON with chevron single-encoded, it wouldn't have been a problem. The problem only comes from the XML format Diaspora messages are delivered with, not from Markdown that can contain HTML.

**Comment by denschub** [comment] 2019-07-28 14:11
> But the `<h1>` tag in the source message wasn't meant as "Raw HTML"

You actually don't know that, because there is no way for users to indicate such an intention. The reason we don't actually interpret the chevrons inside the code block as HTML tags is because you don't parse content inside fenced code blocks, but rather treat is as literal text. [CommonMark is very explicit](https://spec.commonmark.org/0.29/#fenced-code-blocks):

> The content of a code fence is treated as literal text, not parsed as inlines.

The comment in your example is stored the following way inside diaspora\*s database:

    I prefer to think of a website as a book - on the home page(=cover) the <h1> is the name of the website
    on the other pages (=chapter) the current page title is the <h1> and the name of the website is at the pageheader as an <h2> or normal paragraph (but still on first position)

    example for a wordpress header.php i have currently open:
    ```php
    <?php
      /**
      * @Site Headline
      * @use bloginfo('description')
      * @description uses "description" instead of "title" because logo includes the title
      */
      $siteNameTag = is_front_page() || is_home() ? 'h1' : 'h2';
    ?>
      <<?php echo $siteNameTag; ?> id="site-name" class="title">
        <a href="<?php echo esc_url(home_url()) ?>/" rel="home"><?php bloginfo('description'); ?> <?php bloginfo('name'); ?></a>
      </<?php echo $siteNameTag; ?>>
    ```
    i also would love to see the "outline" algorithm wordking. At SEO level you still get banned for headline spamming.

As you can observe, there is no escaping here - because it's not needed. Markdown will treat everything in a code block as literal text, so the markdown parser *will* escape those tags when producing the HTML output. If those tags are used outside of a comment block, it may very well be valid HTML, so we literally can't escape.

The reason we don't render those headline tags as headlines is because there is no matching closing tag in the same block. That's what our Markdown parser does, and interestingly, commonmarker follows this, while commonmark.js renders the tags and just closes them at the end of the block. I'm unsure what the correct behavior here is, but that's not the point. We use Redcarpets defaults here, and while we eventually should switch to a CommonMark compliant parser, but even that would not resolve the escaping issue.

Just to explain the issue, this is perfectly fine input:

    <h2>foo</h2>

    ```
    <h2>foo</h2>
    ```

This content would be stored without any alteration in the database, and also federated the same way. In diaspora\*, following CommonMark in that case, this would render as:

<img width="204" alt="Screenshot 2019-07-28 at 15 50 22" src="https://user-images.githubusercontent.com/344777/62007590-7da4dd00-b14f-11e9-886a-5ef0e3aaadde.png">

And practically all Markdown parsers will agree with diaspora here. As an example, you can use [the playground demo for commonmark.js](https://spec.commonmark.org/dingus/), which renders exactly the same as diaspora: it correctly renders the headline as a headline, because it's valid HTML, while it escapes the chevrons inside the fenced code block.

You are expecting us to escape something, but there is no escape we could do. If we escape all chevrons, it would break the headline from showing up as HTML, and if we'd escape the tags inside fenced code blocks, we'd actually see the escape sequences in the render output, because Markdown parsers do not treat content inside fenced code blocks as HTML, so nothing would ever unescape those.

The only escaping we ever do is when sending stuff out, because it has to be wrapped inside XML. These days, I might be tempted to suggest using `<![CDATA[ ... ]]>` here, but it's too late for that, and even this change would not resolve your issue.

> If you were sending the same body over JSON with chevron single-encoded, it wouldn't have been a problem.

Except we wouldn't. If our payload were JSON, the only thing we would escape is quotes and backslashes - the chevrons would stay unescaped chevrons, as there is no reason to escape them.

The post you've linked is essentially a inconsistency caused by Markdown parsers that were created before CommonMark was a thing, and technically it's a diaspora bug because diaspora\* probably should render headlines here, if we were to follow CommonMark. This is not an escaping isssue and I don't see how escaping anything would make the situation any more predictable.

**Comment by denschub** [comment] 2019-07-28 14:21
Interestingly enough, even our markdown-it for rendering posts on the desktop interface does not render the headlines, although it's 100% CommonMark compliant. This smells like a spec issue, because the CommonMark spec is not really clear here. Still, escaping would not help.

**Comment by MrPetovan** [comment] 2019-07-28 14:44
I'm not talking about the fenced code block that are working fine. I'm talking about what's before:
```
I prefer to think of a website as a book - on the home page(=cover) the <h1> is the name of the website
on the other pages (=chapter) the current page title is the <h1> and the name of the website is at the pageheader as an <h2> or normal paragraph (but still on first position)
```
To be able to be rendered on screen as such in Diaspora by your Markdown parser, it has to be transformed into:
```
I prefer to think of a website as a book - on the home page(=cover) the $lt;h1$gt; is the name of the website
on the other pages (=chapter) the current page title is the $lt;h1$gt; and the name of the website is at the pageheader as an $lt;h2$gt; or normal paragraph (but still on first position)
```
This indicates the chevrons are meant to be literal chevrons, not HTML tags that wouldn't appear on screen.

You said you don't send HTML, but you actually do since Markdown syntax allows HTML. It's actually Markdown+HTML. As such, any intended literal chevron have to be escaped to prevent HTML tags to be interpreted by any Markdown parser.

Additional information: this display problem wouldn't happen if the unescaped unclosed HTML tag was an inline one. The fact that it is an unescaped unclosed block tag in the middle of a paragraph throws our Markdown parser off.

The only way Diaspora can convey that this unclosed block HTML tag in a paragraph is meant literally is to escape the chevrons like it is done to display it on Diaspora itself.

**Comment by denschub** [comment] 2019-07-28 14:50
> You said you don't send HTML, but you actually do since Markdown syntax allows HTML. It's actually Markdown+HTML.

We send Markdown. With everything that Markdown entails.

> The only way Diaspora can convey that this unclosed block HTML tag in a paragraph is meant literally is to escape the chevrons like it is done to display it on Diaspora itself.

No. This is a bug in diaspora - if we follow CommonMark, we would not ignore the tags and instead render a headline there, because that's the only way that follows CommonMark. Escaping is still not a solution.

**Comment by MrPetovan** [comment] 2019-07-28 14:55
Maybe, but it still displays what most Diaspora users are expecting, so it doesn't look like a bug you will want to fix anytime soon.

**Comment by denschub** [comment] 2019-07-28 15:01
Not sure. I'd rather stick to the spec in the rare case there actually is one, and here it seems to be relatively clear. Escaping things will cause all kinds of weird edgecases, and I'm tempted to rather stick on having CommonMark implemented in a predictable way than doing magic that's not covered by any documentation (escaping only unbalanced tags and persisting that escaping is "magic", in that sense).

I opened https://discourse.diasporafoundation.org/t/consider-dropping-modifying-markdown-it-sanitizer-to-stay-in-accordance-with-commonmark/2759 for a discussion on this, and we can go back to GitHub when there is an actionable item. Thanks for the report.

**Closed by denschub** 2019-07-28 15:01 UTC
Labels: post parsing, 🛰️ federation, 🤔 undecided

**Comment by MrPetovan** [comment] 2019-07-28 15:03
You're welcome, thank you for your time as well.

**Comment by SuperTux88** [comment] 2019-07-28 20:53
> @SuperTux88 do you have an opinion here?

I agree with you here, this is no federation-issue, we send exactly what the user entered. We don't alter any content on federation and that would also lead to problems with signatures when relaying, the federation just sends what is in the database (and escape it once because of XML, if it would be JSON the `<h1>` wouldn't be escaped at all and probably lead to the same result on the other end).

> But the `<h1>` tag in the source message wasn't meant as "Raw HTML"

It isn't the federation layers job to "guess" what the user "meant" and maybe escape something a second time. If the user meant it that way, then they should have entered `&lt;h1&gt;` instead of `<h1>` and it would be federated as `&amp;lt;h1&amp;gt;` (since it still would be escaped once when creating the XML).

If you think you know what the user "meant" then you're free to "guess" that on your end and change it when you receive it, but it would probably lead to more problems (because of signatures). And I think it's really hard to detect and "guess" what users meant and would probably lead to a lot of false positives. If the user meant something, they should just enter it the way they meant it, so there is no need to guess. And therefore I agree with @denschub here, that this is probably a render bug on our end.
