### ISSUE TITLE
At registration: initial hash tag items once given can't be deleted

### ISSUE THREAD

**Issue by Darkwing371** [diaspora/diaspora#6352] opened 2015-08-27 11:23 UTC
I can't post a screenshot, but:

In the registration process the user is asked to provide some initial hash tags of interests to follow. Each item is then displayed "chzn-style" with a small closing cross to again cancel it from the list if needed. And exactly that doesn't work. There is no chance in deleting an item once given.

Can anyone confirm that and maybe have a look? (At the time I was using FF 37.0. *duckandrun* ;) )

Thanks!

**Comment by svbergerem** [comment] 2015-09-13 15:40
I'm not able to reproduce this with Firefox 40 on develop. I can remove hashtags by clicking the cross as well as using the backspace key.

**Comment by jaywink** [comment] 2015-09-18 20:45
@Darkwing371 could you post which pod you are on? Can't reproduce either.

**Comment by theworldbright** [comment] 2015-09-18 20:48
I think I once had this problem when I was working with develop. I never really found a way to reproduce it.

**Comment by Darkwing371** [comment] 2015-09-18 21:02
It happened on diasp.de – and I used FF 37 back than. Maybe this issue is obsolete now.
(I wanted to reproduce this now, but at the moment they have an error 500 at registration process. ^^)

Could it be that Ghostery or AdBlockPlus played a part in that incident? Just guessing …

**Comment by svbergerem** [comment] 2016-03-31 11:46
I'll close this. We can reopen this issue if anyone is able to reproduce this.

**Closed by svbergerem** 2016-03-31 11:46 UTC
Labels: needs more info
