### ISSUE TITLE
Improvement - Language "select menu"

### ISSUE THREAD

**Issue by genma** [diaspora/diaspora#6845] opened 2016-06-01 08:48 UTC
I post this issue in order to suggest a diaspora feature that will be an improvement.   Diaspora is a international community and when you start to share with many foreigner people, you have many post in language you don't know. The improvement will allow to filter all this messages.

This is the description of my needs and functionality : 

- In Settings, a new Language entry menu is added. I can select all the language I'd like to post in or read post. For me, it will be French and English.
- When I write a post, I'd like to have a button where I choose the language in which the post is written. 
This button will be as the button "public" or "friend". For example, I choose French. Only people with whom I share the post that have "French" in their language see this post. The non French speakers dont' see this post so I don't "spam" them :-)
- In reverse, if a german friend of mine post a post tag "german", I don't read it. But he post a post tag "english", I can see it. 

=> The goal is to have a filter by language. 

Ask me if it's not easy to understand, if you need more explanation...

**Comment by jhass** [comment] 2016-06-01 09:10
Duplicate of #3513

**Comment by SansPseudoFix** [comment] 2016-06-01 09:10
Well, duplicate of #3513 and you have a  a discussion on PR #4998  ,plus [loomio discussion](https://www.loomio.org/d/4vTqCj5X/language-filter-for-diaspora-as-a-gsoc-project) about it too (and [bounty](https://www.bountysource.com/issues/289-limit-wall-to-user-language?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)).

**Closed by jhass** 2016-06-01 09:10 UTC
