### ISSUE TITLE
List words when writing # in a publication.

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#6930] opened 2016-07-26 23:33 UTC
Hi, it would be interesting for the user when writing a # in a publication, the words associated with writing as well as done in the Search display.
![captura de pantalla de 2016-07-26 20 31 53](https://cloud.githubusercontent.com/assets/5890886/17158935/0bff4ce8-5370-11e6-89ee-8bb16eaeb653.png)

**Comment by denschub** [comment] 2016-07-27 12:35
Duplicate of #6076.

**Closed by denschub** 2016-07-27 12:35 UTC
