### ISSUE TITLE
Clarify aspects in limited posts

### ISSUE THREAD

**Issue by juliaviluhina** [diaspora/diaspora#6426] opened 2015-09-24 22:25 UTC
May be, it is feature.

Posts, which were published for some aspects, are marked as Limited
Can I get information about aspects of this post?
I think, it would be helpful to know about limited posts written by owner of account.

**Comment by jhass** [comment] 2015-09-24 22:35
We had this before but I can't find it atm. The issue is that it quickly is lying, it would suggest "those are the people who can see the post" but if you modify the aspects a contact is in or add or remove a contact that does not affect the visibility of your past posts.

**Comment by svbergerem** [comment] 2015-09-24 22:37
Duplicate of #3181.

**Closed by svbergerem** 2015-09-24 22:37 UTC

**Comment by Loelo** [comment] 2015-11-27 18:18
Also duplicate of [#4995](https://github.com/diaspora/diaspora/pull/4995)

Seems to be a very needed feature !
