### ISSUE TITLE
Group feauture

### ISSUE THREAD

**Issue by koyuawsmbrtn** [diaspora/diaspora#7150] opened 2016-10-18 20:54 UTC
Most social networks have something called groups. I like the aspects very well, but this is something different. What if you could invite people to groups and they can post certain stuff? Like a group for Linux or Music or your favourite hobby. Most social networks have this feature built-in and this is an essential feauture I miss the most on Diaspora. The thing is only people who you follow and they follow back can invite you to groups. This doesn't count for "auto-followed" people.

Hopefully someone accepts this feature request though I'm very bad at programming

See you soon
*~Koyu*

**Comment by SuperTux88** [comment] 2016-10-18 20:56
Duplicate of #6278

**Closed by SuperTux88** 2016-10-18 20:56 UTC
