### ISSUE TITLE
No way to distinguish users when drafting a new message

### ISSUE THREAD

**Issue by gsantner** [diaspora/diaspora#6855] opened 2016-06-07 12:42 UTC
Currently there is no way to distinguish which user is who when drafting a new message and start typing a name. Please add the id in the search popover e.g. `username <pod.mypod.com>`.

Pod-Version: 0.5.99.0-pbea9d795  

![unbenannt](https://cloud.githubusercontent.com/assets/6735650/15857837/c081e600-2cbd-11e6-817f-965b0eeaaabd.png)

**Comment by Flaburgan** [comment] 2016-06-07 15:06
I was sure we already have an issue about this, but I don't find it.

**Comment by gsantner** [comment] 2016-06-07 15:09
I also spent some time on searching, and couln't find it, but you're maybe right.

**Comment by svbergerem** [comment] 2016-06-07 19:28
Duplicate of  #5091.

**Closed by svbergerem** 2016-06-07 19:28 UTC
Labels: ui

**Comment by denschub** [comment] 2016-06-07 22:06
Good catch, thanks, @svbergerem!
