### ISSUE TITLE
"Manage connected services" button below "New post" textarea does not work

### ISSUE THREAD

**Issue by TwizzyDizzy** [diaspora/diaspora#6731] opened 2016-03-02 21:31 UTC
Hi folks,

I just realized, by accident, that the small wheel below the textarea for a new post is currently not taking you to the "services" page.

***Expected***:
*click on wheel* -> *get to* https://pod.url/services

***What actually happens***:
*click on wheel* -> only "#question_mark_pane" is added to the current URI in the location bar of the browser. You stay on the current page.

If you need any further help with debugging this, please do not hesitate to get back to me.

Cheers
Thomas

**Comment by svbergerem** [comment] 2016-03-02 22:10
I'm able to reproduce this on the master branch but I'm unable to reproduce this on the develop branch.

**Comment by denschub** [comment] 2016-05-25 20:05
Closing this, seems to work in `develop`.

**Closed by denschub** 2016-05-25 20:05 UTC
