### ISSUE TITLE
Mentionning does not hightligh the right text when nicknam appears 2 times on text

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6545] opened 2015-11-14 12:32 UTC
Steps to reproduduce : start mentionning someone using `@` but do not select a result and leave the text as is and then start mentionning the person a second time but select the result in the mentionning box. The replaced text is the first part of the text and not the second.

![screen shot 2015-11-14 at 13 31 00](https://cloud.githubusercontent.com/assets/3429231/11163544/ff8b58ea-8ad3-11e5-9c1c-9348c33681ea.png)
![screen shot 2015-11-14 at 13 31 13](https://cloud.githubusercontent.com/assets/3429231/11163548/1548b010-8ad4-11e5-82b5-013d096a5dd7.png)

**Comment by svbergerem** [comment] 2015-11-16 00:41
I guess this is a duplicate of #4786.

**Closed by svbergerem** 2015-11-16 00:41 UTC
Labels: bug, ui
