### ISSUE TITLE
Profile images from facebook accounts are fetched over HTTP not HTTPS

### ISSUE THREAD

**Issue by tomato42** [diaspora/diaspora#5808] opened 2015-03-21 20:25 UTC
When a user has a profile photo imported from Facebook (served from facebook servers), the image URL is HTTP not HTTPS, causing a mixed content warning.

**Comment by Flaburgan** [comment] 2015-03-21 20:48
We changed the way FB images are fetched in the current develop branch, so I think this is no longer the case (we do not send a request to FB anymore).

**Comment by jhass** [comment] 2015-03-21 21:29
Yes, in fact duplicate of #5341 I'd say.

**Closed by jhass** 2015-03-21 21:29 UTC
