### ISSUE TITLE
Configure default sharing to "public"

### ISSUE THREAD

**Issue by tukkek** [diaspora/diaspora#6885] opened 2016-06-26 02:30 UTC
I've seen this discussed multiple times on the network (and it's also something I'd find very helpful myself since I mostly post to public) so I decided to open this request.

When you post something to diaspora* the default sharing is to "all aspects". It would be nice for the network to remember your last used option or let you decide a default one either via preferences on using the "gears" button (image not mine, just a relevant screenshot) https://diasp.org/uploads/images/scaled_full_adaa9239789705f8f54e.png

The reason this would be beneficial:

1. Having "all aspects" currently is arbitrary. People will likely use one of the options more than others but this could be "all aspect", one of the aspects, "public", etc. There is no reason I can think of for "all aspects" to be the de facto standard for the network.

2. Currently diaspora* is not a huge network, most of us don't have real-life friends there to network with or a huge number of contacts. We're here for novelty, freedom and as an alternative to major social networks. In this sense "public" is probably a better option since it means more content is generated for all of the users in the network. New users could even start sharing by default to "all aspects" and not realize their posts won't reach anyone unless people have started sharing with them beforehand - a reasonable and pretty likely mistake.

Anyway this request is not about which one should be the default, but trying to make a point that the default should be configurable on a per-user basis. Even being not such a new user I repeatedly still end up posting to "all aspects" when I want to post "public", so I  guess this is something that would benefit everyone in a way or another.

**Comment by SuperTux88** [comment] 2016-06-26 02:42
duplicate of #4319

**Comment by tukkek** [comment] 2016-06-26 02:51
Sorry about that, I did a quick search for similar issues but came up with nothing.

**Closed** 2016-06-26 03:54 UTC
