### ISSUE TITLE
Auto-complete tags

### ISSUE THREAD

**Issue by MathiasRenner** [diaspora/diaspora#7564] opened 2017-08-21 15:19 UTC
Auto-completion of tags in posts or comments is IMHO a very important feature. 

I couldn't find any evidence that someone is workin on it, even if I doubt that this is true - given that diaspora is kinda stable for so long now. So let's join forces and see if this feature could get into the next (sub)release :-)

**Comment by Flaburgan** [comment] 2017-08-21 15:25
Duplicate of https://github.com/diaspora/diaspora/issues/6076

**Closed by Flaburgan** 2017-08-21 15:25 UTC
