### ISSUE TITLE
Can't disable notifications of a freshly liked post

### ISSUE THREAD

**Issue by noplanman** [diaspora/diaspora#7008] opened 2016-08-20 17:29 UTC
When liking a post, it does not automatically update the little bell notification icon.
So in the background, the notifications have been enabled, yet this is not visible on the front end.

When I then click the bell icon, to disable the notifications, I get a `422 Unprocessable Entity` error.

After a refresh of the page, the icon is properly set and enabling/disabling notifications works properly again.

**Comment by svbergerem** [comment] 2016-08-20 18:02
This is a duplicate of #5811. Thank you anyway for reporting this issue.

**Closed by svbergerem** 2016-08-20 18:02 UTC

**Comment by noplanman** [comment] 2016-08-20 18:26
D'oh, didn't find that one with my search, sorry!

**Comment by svbergerem** [comment] 2016-08-20 18:28
No problem. I also needed two tries to find it and I knew it was there.
