### ISSUE TITLE
Special character cuts off text

### ISSUE THREAD

**Issue by polsVoice** [diaspora/diaspora#5147] opened 2014-08-24 15:36 UTC
I found out that a certain character will truncate the text in a post. The character is erased, as well as everything after it. It's not immediately obvious, though, because it only happens after the page is reloaded.
Here are the steps I used.
1. Create a post with the text:
I am a 😔 meat popsicle
2. Hit the Preview button. The preview will show:
I am a 😔 meat popsicle
3. Hit the Share button. The post will read:
I am a  meat popsicle
(The special character has been replaced with the generic square icon.)
4. Reload the page. The post now reads:
I am a

**Comment by svbergerem** [comment] 2015-03-11 09:58
I can't reproduce this on develop with MariaDB. Maybe #5530 fixed this?

**Comment by jhass** [comment] 2015-03-11 11:39
Mmh, quite possible. Did anybody ever reproduce this on PostgreSQL?

**Comment by dimaursu** [comment] 2015-04-05 21:32
@svbergerem #5530 should definitely fixed this kind of inconsistency, that is if you are running the version after the merge, of course. This issue should be closed.

**Comment by denschub** [comment] 2015-05-04 00:53
Closing; working on MySQL and PostgreSQL with 0.5.0.0.

**Closed by denschub** 2015-05-04 00:53 UTC
Labels: bug, confirmed, data issue, post parsing, weird
