### ISSUE TITLE
Export photo button can stay blocked

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6225] opened 2015-07-22 08:06 UTC
![request-photo](https://cloud.githubusercontent.com/assets/3429231/8820815/f484fae4-3058-11e5-8ade-18cb9c871e98.png)

It has been like this for weeks now. I have no idea why it is blocked like that so I have no way to reproduce. It a major blocking point so I propose that there should be a guard checking when user data or user photos have been requested and determine that a request has failed when the data or photos are still unavailable after a certain time.
##

**Comment by Flaburgan** [comment] 2015-07-22 19:26
@jhass this is not about the UI. When Jason first implemented this feature, the sidekiq worker was not set correctly. So in the DB the checks of "exporting" and "exporting photos" are set to true, but nothing is processed in reality.

**Comment by Flaburgan** [comment] 2015-07-22 19:33
Hm, nevermind, my exporting value is true ( @jaywink is it safe to update this to false in sql directly?) but Augier's one is false, so the problem doesn't come from there.

**Comment by jaywink** [comment] 2015-07-22 19:52
@Flaburgan I don't understand the question :P I didn't implement photo export

**Comment by svbergerem** [comment] 2016-02-08 00:32
This looks like a duplicate of #6625. @AugierLe42e can you confirm that this has been fixed?

**Comment by AugierLe42e** [comment] 2016-02-08 11:34
I confirm the issue is absolutely not resolved. Actually, the button has completely disappeared:

![button-disappear](https://cloud.githubusercontent.com/assets/3429231/12884684/387cb4e4-ce60-11e5-9f4c-33e9ed498b05.png)

Unless have missed something and the button was indeed removed?

**Comment by denschub** [comment] 2016-02-08 11:37
When did you start the export? If it's been a while, set `exporting_photos` in your user to false and try again.

**Comment by svbergerem** [comment] 2016-02-08 11:41
I just exported my photos on my pod and it worked fine:

![export photos](https://cloud.githubusercontent.com/assets/3798614/12884803/fc58ae0e-ce60-11e5-87f8-e4e35c4033e8.png)

While the pod processes the photos the button is not rendered. Maybe we should set `exporting_photos` to false if that failed? And maybe add a note about the failed export on that page?

**Comment by Flaburgan** [comment] 2016-02-08 12:51
Yeah we still have a problem here, even on  `master` (framasphere is impacted).

**Comment by svbergerem** [comment] 2016-02-08 12:55
@Flaburgan the fix will be part of 0.5.7.0: #6659.

**Comment by Flaburgan** [comment] 2016-02-08 12:59
It's not that problem, I don't have the related stack trace in the log.

**Comment by svbergerem** [comment] 2016-02-08 20:57
@Flaburgan so there is a user with `exporting_photos` set to true for a long time and there is nothing in the logs? Did you enable logrotate?

**Comment by Flaburgan** [comment] 2016-02-08 23:50
I tried again this morning, I created a new account, uploaded a profile picture and then click the button to request my photo. Since then I have the "We are currently processing your photos. Please check back in a few moments." message. I have logrotate enabled.
Here is what I see in `eye_processes_stderr.log`: 
`IP - - [08/Feb/2016:13:58:07 +0100] "POST /user/export_photos HTTP/1.0" 302 - 0.1102`
And in `production.log`:
```
[2016-02-08T13:58:07] INFO  PID-7540 TID-16913200 Rails: Started POST "/user/export_photos" for IP at 2016-02-08 13:58:07 +0100
[2016-02-08T13:58:07] INFO  PID-7540 TID-16913200 ActionController::Base: Processing by UsersController#export_photos as HTML
[2016-02-08T13:58:07] INFO  PID-7540 TID-16913200 ActionController::Base:   Parameters: {"authenticity_token"=>"y73X8vg=="}
[2016-02-08T13:58:07] INFO  PID-7540 TID-16913200 ActionController::Base: Redirected to https://framasphere.org/user/edit
[2016-02-08T13:58:07] INFO  PID-7540 TID-16913200 ActionController::Base: Completed 302 Found in 96ms (ActiveRecord: 40.2ms)
``` 
Nothing in `sidekiq.log`

**Comment by Flaburgan** [comment] 2016-02-08 23:57
Exporting photo is set to true in the database, btw, and nothing else than `http:multi` in sidekiq planned jobs.

**Closed** 2017-08-14 02:08 UTC
Labels: bug, ui
