### ISSUE TITLE
No connection with other pods

### ISSUE THREAD

**Issue by CannyFoxx** [diaspora/diaspora#5725] opened 2015-03-03 22:49 UTC
Hello! Today I reinstalled my pod (he stand on production server) with wiping all data. After installation, i tried to follow some people from other pods. Some of them set automatically following. But now they don't follow me.
I tried to create account on other pod and follow myself on my pod. Data shown in this pod were outdated, and I have not received notification of the follow from another pod.
What wrong i do?

**Comment by Flaburgan** [comment] 2015-03-03 23:20
You said you wipe all data. Did you recreate user (with the same username) on a new pod but still using the same domain name? Because you cannot do that.

**Comment by CannyFoxx** [comment] 2015-03-03 23:30
Yes, i used old domain with username. So, can i send some request to other pods for deleting old username?

**Comment by jhass** [comment] 2015-03-04 00:28
No you can't. Your options are to get a backup of your old DB, close your account and choose a different username (same for all usernames that existed on the previous installation) or reinstalling to a different domain name.

This is by design and a won't fix to prevent identity theft.

**Closed by jhass** 2015-03-04 00:28 UTC
