### ISSUE TITLE
Birthday date: year anomaly

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#7171] opened 2016-11-04 13:44 UTC
If you set your birthday date, but finally want to only keep year, you can't. You only can set month and day without year.

Expected: unset month and day, update and only display year.

Edit: tested on Framasphere.

**Comment by gauravkumar28** [comment] 2016-11-05 21:13
I am interested in fixing this problem. Can you give a bit more detail

**Comment by SansPseudoFix** [comment] 2016-11-06 09:25
Well, I don't know how to be more specific: we should have the possibility to set any input as a birthday (even only day). Actually, you can't.

**Comment by svbergerem** [comment] 2016-11-06 10:02
Currently you can set a birthdate or a birthday. Are there any use cases for setting just a year, a month or a day?

**Comment by SansPseudoFix** [comment] 2016-11-06 12:16
Actually, I don't use it at all, but a user wanted to only set year, and couldn't: he selected year-month-day, and saved but wanted to change to only display year, and couldn't.

I think it would be useful to allow only year and month (and both), just to know how old are users. Only day is quite silly, but eh, why not?

**Comment by SuperTux88** [comment] 2016-11-06 12:25
The problem is, that the birthday is saved and federated as "date", so it needs to be a full date. If you only select day and month we save the year "1004" and we have a check that we don't display the year if it is 1004.

**Comment by Flaburgan** [comment] 2018-03-25 21:33
This feature request doesn't seem to add anything imo. I'd vote for closing it. Opinions?

**Comment by SuperTux88** [comment] 2018-03-26 05:28
This feature request is also incompatible with our database and the federation protocol (and therefore with all others implementing the protocol). If somebody really only wants to write the year, they can simply add it to the description of the profile. So lets close this for now, we can always reopen it if something changes.

**Closed by SuperTux88** 2018-03-26 05:28 UTC
Labels: ui
