### ISSUE TITLE
Export and import contact list

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#7135] opened 2016-10-01 14:24 UTC
Hello,
a feature that can facilitate the migration of pods, may be to export the list of contacts to import it into the new pod.
Thank you

**Comment by AugierLe42e** [comment] 2016-10-01 21:35
Duplicate of #908.

**Comment by dcapeletti** [comment] 2016-10-01 22:07
I just want to export the contact list in a file. Then in the new pod, you can import contacts and tell them all via a message (if you wish).
A migration wizard is to migrate other issues, is to migrate an entire account, files and all imagine, so do not apply.

**Comment by denschub** [comment] 2016-10-01 22:36
It, in fact, is a duplicate and if you'd have read the entire discussion, you'd agree. ;)

**Closed by denschub** 2016-10-01 22:36 UTC
