### ISSUE TITLE
Tags on hovercards missing first letter in link

### ISSUE THREAD

**Issue by 4ndyD** [diaspora/diaspora#7098] opened 2016-09-13 02:48 UTC
Since 0.6 I've noticed when pointing my cursor at the hashtags on users' hover cards that they point to a url with the first letter of the tag missing.
i.e. a user who says they are interested in photography will have a hyperlink "photography" that actually points to joindiaspora.com/tags/hotography

**Comment by Flaburgan** [comment] 2016-09-13 06:39
Duplicate of https://github.com/diaspora/diaspora/issues/7074. This bug is already fixed in the coming 0.6.1.0 release. You only have to wait for the fix to reach you ;) But thanks for reporting, this is the kind of bug we want to discover.

**Closed by Flaburgan** 2016-09-13 06:39 UTC

**Comment by 4ndyD** [comment] 2016-09-14 17:47
Thanks, I'm don't know why that didn't turn up when I searched for tags & hovercards the other day, I'm sure I had removed is:open :confused:
