### ISSUE TITLE
Can we add video embedding of youtube and vimeo, etc. more obvious?

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#6765] opened 2016-03-22 14:03 UTC
%subj% That you added a video, instant pic of the video after you added a link or maybe add a video icon near send button idk...

**Comment by Flaburgan** [comment] 2016-03-22 14:23
Just post a link to youtube and vimeo, you'll see the video embedded after reloading the page.

**Comment by jhass** [comment] 2016-03-24 14:15
Closing this as a duplicate of #4465

**Closed by jhass** 2016-03-24 14:15 UTC
