### ISSUE TITLE
Don't require email on sign up

### ISSUE THREAD

**Issue by xaionaro** [diaspora/diaspora#7415] opened 2017-04-08 12:34 UTC
Please, don't require email on sign up. It's should be an _optional_ field.

**Comment by Flaburgan** [comment] 2017-04-09 16:27
As we only use e-mail to send notification or send a password reset, I agree about this.

**Comment by goobertron** [comment] 2017-04-09 17:21
Perhaps, then, if this is implemented, the section of check-box options 'Receive email notifications when' in the user settings should be removed, as should any other section which relies on email (export data?).

**Comment by xaionaro** [comment] 2017-04-09 18:49
@goobertron, why? It just should be an *optional* field (that also can be edited via profile settings). When you requires optional field on sign up it:
* Creates a significant inconvenience.
* Frighten away people who cares about their anonymity (on reflexes). When service _requires_ an email it doesn't look like a privacy-aware service.

**Comment by Flaburgan** [comment] 2017-04-09 19:10
Well, until now, we were sure the e-mail was filled. If it because optional, then it can be null, then every place we use it we have to test it's not.

**Comment by xaionaro** [comment] 2017-04-09 19:12
@Flaburgan 

Ok, l can donate few bucks for this. I think a lot of people will donate.

**Comment by goobertron** [comment] 2017-04-09 21:20
@xaionaro I think you misunderstand me. I am not disagreeing with your proposal. I am making a suggestion of something else which should be implemented if your proposal is implemented. If the email field has been left blank by a user, we should remove those user settings which depend on the user having entered an email address, such as notifications by email (which obviously can't be sent).

**Comment by cmrd-senya** [comment] 2017-04-09 21:24
> @xaionaro I think you misunderstand me. I am not disagreeing with your proposal. I am making a suggestion of something else which should be implemented if your proposal is implemented. If the email field has been left blank by a user, we should remove those user settings which depend on the user having entered an email address, such as notifications by email (which obviously can't be sent).

But why? We want notifcations to be configurable. Why do we need to remove them? We can just hide them for those who have "email == nil".

> Ok, l can donate few bucks for this. I think a lot of people will donate.
@xaionaro, you can use https://www.bountysource.com/issues/43929595-don-t-require-email-on-sign-up for that

**Comment by goobertron** [comment] 2017-04-09 21:27
> But why? We want notifcations to be configurable. Why do we need to remove them? We can just hide them for those who have "email == nil".

I meant to hide them, only for users who don't enter an email address. I didn't mean to remove them from the settings for all users. Looking back, I see that my comments weren't at all clear about this. Apologies for that, and thanks for challenging what I said.

So, a new configuration: if 'email == null', hide settings which require an email address. Just as you said. Thanks!

**Comment by svbergerem** [comment] 2017-04-11 09:42
This is a duplicate of #5861.

**Closed by svbergerem** 2017-04-11 09:42 UTC
