### ISSUE TITLE
[RTL] Are using the wrong Unicode Control Character?

### ISSUE THREAD

**Issue by GreenLunar** [diaspora/diaspora#6453] opened 2015-10-04 08:41 UTC
It appears you are using RLO (U+202E RIGHT-TO-LEFT OVERRIDE)

‮It appears you are using RLO (U+202E RIGHT-TO-LEFT OVERRIDE)

See https://joindiaspora.com/u/willhill in Hebrew interface.

Will Hill appears as ‮Will Hill

**Comment by GreenLunar** [comment] 2015-10-04 09:31
Original:
Are you sure the RTL "contributors" or alleged users, that you communicate with, serve diaspora* interests? (DELETED)

Correction:
Are you sure the RTL "contributors" or alleged **RTL** users, that you communicate with, serve diaspora* interests? (DELETED)

**Comment by jhass** [comment] 2015-10-04 09:36
Duplicate of #4785

**Closed by jhass** 2015-10-04 09:36 UTC
