### ISSUE TITLE
YouTube playlist links load embedded player for only the first track

### ISSUE THREAD

**Issue by defcronyke** [diaspora/diaspora#7154] opened 2016-10-22 03:19 UTC
As per the title. We linked to our new album, and the embedded player will only play the first track from it. I think it would be better for it to play all the tracks in the playlist, since it's a playlist link.

**Comment by svbergerem** [comment] 2016-10-23 21:38
Works for me with `https://www.youtube.com/playlist?list=PLt5AfwLFPxWIpgtcFs_7fHGUedGEKu73p`.

**Comment by defcronyke** [comment] 2016-10-23 21:43
The playlist link works, but the embedded player which loads from that link on the post only shows the 1st video in the playlist. Other social networks detect a YouTube playlist link and load the whole playlist in the embedded player that shows. I'll fix it if no-one else wants to, but I'm not familiar with the diaspora codebase, so someone else may be able to do it better than me.

**Comment by svbergerem** [comment] 2016-10-23 21:46
![YouTube playlist](https://cloud.githubusercontent.com/assets/3798614/19629705/ac252a9e-997a-11e6-8430-5e16e93a0633.png)

It plays the first video but also has buttons to skip to next and previous videos and automatically plays the second video of the playlist after finishing the first one.

**Comment by defcronyke** [comment] 2016-10-23 21:53
It's loading just the first video, not the playlist for my link. For yours it is correctly loading the whole playlist.
!["It's loading a single video, not the playlist"](http://i.imgur.com/DmmAl4q.png)

**Comment by svbergerem** [comment] 2016-10-23 22:00
I'd say that is YouTube's fault: https://www.youtube.com/oembed/?url=https://youtu.be/rXPhqjqKnCc?list=PLA9w7gX4C1R3bYLDm4DyRwy9Fo2QPbnTy&format=json

**Comment by SuperTux88** [comment] 2016-10-23 22:10
Your link links to a video (in a playlist), and the link of @svbergerem links directly to the playlist. And YouTube seems to handle these links differently. So if you want to embed the playlist you need to link to the playlist.

**Comment by defcronyke** [comment] 2016-10-23 22:42
It is a playlist link, but it's the shortened version which youtube gives you if you say you want to Share the video.

**Comment by defcronyke** [comment] 2016-10-23 22:47
@svbergerem, other social networks detect the playlist url and load the whole playlist instead of just the first video. If you want to see an example you can check our Patreon, which I won't link because I don't want to spam it.

**Comment by svbergerem** [comment] 2016-10-23 22:52
@defcronyke We ask YouTube how we should embed the URL and YouTube tells us that we should embed it as a single video like I wrote [here](https://github.com/diaspora/diaspora/issues/7154#issuecomment-255617661). I don't know if there is some reason for YouTube to behave like this but if you'd like YouTube to behave in a different way then please follow https://support.google.com/youtube/answer/4347644.

I'll close this issue since diaspora\* works as expected (by doing what YouTube tells us to do).

**Closed by svbergerem** 2016-10-23 22:52 UTC
Labels: embedding

**Comment by defcronyke** [comment] 2016-10-23 22:54
@svbergerem, so you'd rather have worse behaviour on Diaspora because that's what Google wants? If the issue is just that you don't want to write a special case for it, would you be receptive to a PR which adds a case for it?

**Comment by svbergerem** [comment] 2016-10-23 23:00
@defcronyke There are special playlist URLs that embed the playlist. Some users might want to embed a single video while playing it from a playlist and won't notice that they are actually copying a URL that also includes information about the playlist. That might be the reason why YouTube behaves like this but as I wrote above I don't know the exact reason. Maybe it's a bug, maybe it works as intended. All I'm saying is that I think that we should trust YouTube about how to embed videos.

**Comment by defcronyke** [comment] 2016-10-23 23:08
@svbergerem, if YouTube gives you a single video from my link, then YouTube is wrong, because it is absolutely a playlist link. Try sharing any playlist on YouTube with the share button, and you'll get a link with the same format.

**Comment by svbergerem** [comment] 2016-10-23 23:09
@defcronyke 

> then YouTube is wrong
