### ISSUE TITLE
Underscores in URLs are dropped when posting

### ISSUE THREAD

**Issue by Hobbit-Habit** [diaspora/diaspora#7941] opened 2018-11-29 03:48 UTC
If I post a URL to diasp.org, containing underscores, such as this:

https://www.youtube.com/watch?v=_2_-21bdGe4

It is published as this (i.e., without the underscores):
https://www.youtube.com/watch?v=2-21bdGe4

**Comment by SuperTux88** [comment] 2018-11-29 04:04
This is a duplicate of #5563 where it was decided to not fix this edge case because it's [an upstream bug](https://github.com/markdown-it/markdown-it/issues/38) and is not fixed there either. You can fix this edge-case by surrounding the link with `<` and `>`, so `<https://www.youtube.com/watch?v=_2_-21bdGe4>` posts the link as you want.

**Closed by SuperTux88** 2018-11-29 04:04 UTC
