### ISSUE TITLE
add participation button on mobile site

### ISSUE THREAD

**Issue by lu-x** [diaspora/diaspora#6540] opened 2015-11-11 11:48 UTC
##

**Comment by netoeuler** [comment] 2016-01-22 01:05
What's participation button? 'Report', 'Ignore', 'Active notification' and 'Hide"?

**Comment by jaywink** [comment] 2016-01-22 20:18
'Active notification' - ie enable notifications.

![selection_212](https://cloud.githubusercontent.com/assets/1174866/12521888/1619741c-c156-11e5-9f76-06a0396985e8.png)

**Comment by netoeuler** [comment] 2016-01-23 01:42
Yes. I use in portuguese, so I try to translate it. 
So, the answer to my question is 'yes'? If yes, I can do it.

**Comment by jaywink** [comment] 2016-01-23 09:45
Go for it! :)

**Comment by Flaburgan** [comment] 2018-03-25 20:51
@netoeuler I guess you're not working on it anymore?

**Comment by netoeuler** [comment] 2018-03-27 13:39
No, I had problems to set up an enviroment to contribute to Diaspora and I don't have time to do this right now. Sorry about that. :/

**Comment by Flaburgan** [comment] 2022-10-31 21:48
This actually is a duplicate of https://github.com/diaspora/diaspora/issues/4225, closing.

**Closed by Flaburgan** 2022-10-31 21:48 UTC
Labels: ✨ feature, 📱mobile
