### ISSUE TITLE
Sort pictures in creation order

### ISSUE THREAD

**Issue by ita1024** [diaspora/diaspora#7947] opened 2018-12-28 21:07 UTC
Posts containing several photos will show those photos in a random order because that order is undefined. Whenever the stream is loaded again, the pictures may be displayed in a new and completely confusing manner.

The following seems to pin a proper order and the "ASC" keyword appears in the production.log file:

```diff
diff --git a/app/models/photo.rb b/app/models/photo.rb
index 75d7f83..beb2fca 100644
--- a/app/models/photo.rb
+++ b/app/models/photo.rb
@@ -49,6 +49,8 @@ class Photo < ApplicationRecord
   before_destroy :ensure_user_picture
   after_destroy :clear_empty_status_message
 
+  default_scope { order(created_at: :asc)}
+
   after_commit :on => :create do
     queue_processing_job if self.author.local?
```

**Comment by denschub** [comment] 2018-12-28 22:51
Duplicate of #4571.

**Closed by denschub** 2018-12-28 22:51 UTC
