### ISSUE TITLE
Groups and Interest pages.

### ISSUE THREAD

**Issue by GeigerCounter** [diaspora/diaspora#7850] opened 2018-08-31 23:57 UTC
This seems like a simple enough request, but it will probably require some overhauls to the way Diaspora works. In essence, what I'm requesting is to have Group pages and pages for business that are separate from, but controlled by individual users. This is so that I don't have to register a new account to have a page for my business and my hobbies. This would make Diaspora more useful to certain types of users and for people looking to connect with entities and not individuals. It would also allow people to have separate "blog-like" pages for creative hobbies that they'd like to keep separated out and would allow podmins to create interest based communities outside of just using hashtags to do it.

**Comment by SuperTux88** [comment] 2018-09-01 00:05
Duplicate of #6278

**Closed by SuperTux88** 2018-09-01 00:05 UTC
