### ISSUE TITLE
No way to add Contact in mobile view

### ISSUE THREAD

**Issue by JonnyTischbein** [diaspora/diaspora#5609] opened 2015-01-29 21:26 UTC
I can't find a way to add a new contact to my ascpect (friend - list). When searching a new person only 
[1] appears. 

I'm using Android 4.4.4 unoffical CyanogenMod (Condor)  with Firefox Version 35. Pod: https://pod.geraspora.de
The Android Browser show the same behaviour. Is just the Link or drop-down menu missing or is their an issue with mobile and adding people ?

[1] - ![screenshot_2015-01-29-22-15-16](https://cloud.githubusercontent.com/assets/10757520/5966589/12de75b4-a806-11e4-9f61-6264cfd6b809.png)

**Comment by SansPseudoFix** [comment] 2015-01-29 22:26
Yeah, right now, you can't. But [soon](https://github.com/diaspora/diaspora/pull/5594) :)

**Comment by jhass** [comment] 2015-01-29 22:27
Duplicate of #4055

**Closed by jhass** 2015-01-29 22:27 UTC

**Comment by JonnyTischbein** [comment] 2015-01-29 22:30
Okay I'm sorry! I searched for label mobile and couldn't find any issue report.
