### ISSUE TITLE
Notifications are not updated when stream is reloaded

### ISSUE THREAD

**Issue by SansPseudoFix** [diaspora/diaspora#6473] opened 2015-10-09 11:06 UTC
With new stream loading, notifications are not shown when I reload.
##

**Comment by jaywink** [comment] 2015-10-10 15:27
I'd almost call this regression since they *used* to update when clicking 'Stream'. So functionality has in essence broken ;)

**Comment by jaywink** [comment] 2015-10-11 12:45
I'm tagging this as a bug and regression since it does break old functionality. Previously when you clicked on for example pod name, notifications were loaded. The fact that they don't load now is behaviour change which hasn't been discussed, so imho it is a bug.

Also, "mark all read" in the notifications panel is broken in some cases. To reproduce:

* mark all notifications as read
* wait some time until there are new notifications
* click the notification icon -> notifications are fetched and displayed

expected: mark all read button is active (as there are clearly unread notifications)

what happens: button is disabled

![selection_088](https://cloud.githubusercontent.com/assets/1174866/10416818/66a98574-7026-11e5-8857-447550033c15.png)

Discussed with @svbergerem that if a proper fix cannot be done for the coming minor release, selected links can be changed to have old functionality by removing `rel=backbone` from them. I'll try to do a fix today to implement a route for the notification counts and poll when needed.

**Comment by svbergerem** [comment] 2015-10-11 12:50
> selected links can be changed to have old functionality by removing rel=backbone from them

Which won't implement the feature for the stream selection when you select another stream. (I am not talking about the links in the header)

**Comment by denschub** [comment] 2015-10-12 02:10
I marked this bug to block the upcoming release which I froze moments ago since I think this will make users angry. I'd be pretty happy to see a fix soon, if possible. :)

**Comment by denschub** [comment] 2015-10-20 02:45
Closed via aabe6951e5f4626b1a518fb096ced2a9a1e91c47

**Comment by svbergerem** [comment] 2015-10-20 06:58
This issue still exists for the stream links in the left navbar.

**Comment by denschub** [comment] 2015-10-20 07:01
True, thanks. Related to (and possibly in the future solved by) #6493.

**Closed** 2016-11-22 02:55 UTC
Labels: backbone code, bug, ui
