### ISSUE TITLE
sign-in fails via mobile web browsers

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6884] opened 2016-06-23 16:11 UTC
Using various mobile phone web browsers hosted in fdroid (e.g. lightning), unable to sign-in to diaspora

See https://github.com/diaspora/diaspora/issues/5906
https://github.com/diaspora/diaspora/issues/6807
https://github.com/diaspora/diaspora/issues/6194

**Comment by denschub** [comment] 2016-06-23 20:11
Duplicate of the issues you already mentioned.

**Closed by denschub** 2016-06-23 20:11 UTC
