### ISSUE TITLE
Posts fail to load using gnu/linux icecat

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6194] opened 2015-07-14 08:39 UTC
Sign-in successful, but stream of posts fails to load; blank white space only visible in the area where posts should appear.

See also:
https://github.com/diaspora/diaspora/issues/5906
https://github.com/diaspora/diaspora/issues/5928
https://github.com/diaspora/diaspora/issues/5982

**Comment by jhass** [comment] 2015-07-14 08:43
Please check your browsers error console for any errors. Also which version of Icecat?

**Comment by jhass** [comment] 2015-07-15 17:30
Closing for now. Will reopen if information necessary to reproduce are provided.

**Closed by jhass** 2015-07-15 17:30 UTC
Labels: needs more info

**Comment by onpon4** [comment] 2016-04-05 14:26
> Closing for now. Will reopen if information necessary to reproduce are provided.

All you need to do is disable JavaScript in your browser. The problem is simple: Diaspora's Web interface has gratuitous JavaScript dependencies. Lots of them.

The mobile interface almost works without JavaScript. The only problem there is the menu, which depends on JavaScript. That could be fixed easily by changing the menu to one based on CSS.

Making the desktop version work without JavaScript as well should not be that difficult of a task.

**Comment by denschub** [comment] 2016-04-05 15:48
> Making the desktop version work without JavaScript as well should not be that difficult of a task.

Looking forward to your pull request!

**Comment by onpon4** [comment] 2016-04-05 21:15
I don't think I'm cut out for making a pull request that would actually be accepted. I don't know how to program in JavaScript and am not interested in learning, so while I would probably be able to produce a version of the HTML that doesn't require JavaScript, it also wouldn't use JavaScript for anything. I wouldn't personally consider that a problem, but I get the impression that the Diaspora developers would.

Also, prior experience tells me that the Diaspora developers are not willing to accept or work on contributions that they don't consider to be perfect. I once submitted a pull request that just added some comments to JavaScript files (for LibreJS), and the developers who saw it would not accept it until I confirmed something in a Ruby test environment, which I was not successful at setting up.

**Comment by denschub** [comment] 2016-04-05 21:56
So how come you feel able to judge that everything is an easy task, but when asked to contribute you claim you're not able to do it? Stop trolling.

Locking this issue. If someone has to contribute something useful, ping one of the core members in IRC and we'll unlock it.
