### ISSUE TITLE
'Failed to post message' warning bug

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#3688] opened 2012-10-27 17:31 UTC
Over the past few weeks this bug has happened periodically. It shows the 'Failed to post message' warning whenever a comment is made, even though the comment is posted successfully.

Not sure what else to say to help identify it. It is happening to me and others on joindiaspora.com at the moment - not sure about other pods. There's something else not quite right at the moment, as I am unable to delete two test posts I made, and also other people (some of whom are on joindiaspora.com) don't seem to be able to read my comments on posts made by other people. Don't know if that will help.

Other people, some of whom I think are on other pods, have noticed the 'Failed to post message' bug in recent weeks, so I think it's likely to be a software bug rather than a jd.com database problem. Might be wrong, though. The stuff in the second paragraph might point to a database thingy.

Hope it's ok to post this here - do tell me where it should be if not here.

**Comment by dgets** [comment] 2015-01-19 00:01
Is there any chance of mapping failures of this sort to load average/memory usage on the server, at least for _joindiaspora.com_?  I mean, I guess if you've all got it nailed down to a particular process that seems to be causing it then perhaps this would be superfluous...  Just taking a shot in the dark here...

I really need to get my OpenBSD pod working.  I just don't have a machine that has enough memory to handle the heavyweight framework for this kind of service for more than a concurrent two, maybe three users, especially if I'm running anything else from that machine.  :P

**Comment by svbergerem** [comment] 2015-07-21 19:17
Is this issue caused by capacity problems of jd? In that case I'd say we can close this because there is not much we can do except for reducing the memory usage but that would be another issue.

**Closed** 2015-09-13 20:47 UTC
Labels: bug, joindiaspora only
