### ISSUE TITLE
Sharing public posts: an intrusion in your privacy

### ISSUE THREAD

**Issue by jpggithub** [diaspora/diaspora#7673] opened 2017-12-12 23:09 UTC
When one share a public post, it is automatically published on his public profile.
IMHO, it's a kind of intrusion in one's privacy and it is more or less counterintuitive in this "ethical" network.
For any content (even public post), diaspora would have to ask which aspects are concerned by this sharing.
At least, diaspora could informed explicitly the user of the consequences of sharing public posts.

The Diaspora FAQ propose to copy/paste the content of a public post to make a private sharing: it's not very easy if you have some pictures and you have to read the FAQ to know the consequences of sharing a public posts.

**Comment by Globulle** [comment] 2017-12-13 08:40
What is counterintuitive by having a "public post" actually public ? I don't understand your point. By the way, in your settings you can choose the default sharing setting you want, and make it to a given aspect.

**Comment by Flaburgan** [comment] 2017-12-13 08:54
Closing as a duplicate of https://github.com/diaspora/diaspora/issues/5770

There is an old discussion about that feature [on discourse](https://discourse.diasporafoundation.org/t/not-public-reshare/475). A way to be able to do that would be to refer to a post from another one, which can be private. We discussed about that with @denschub and @SuperTux88 on IRC, and the discussion is now [continuing on discourse](https://github.com/diaspora/diaspora_federation/issues/83). Please join us there.

**Closed by Flaburgan** 2017-12-13 08:54 UTC
