### ISSUE TITLE
Feature request: administrable group community

### ISSUE THREAD

**Issue by tykayn** [diaspora/diaspora#7885] opened 2018-10-10 09:50 UTC
hi all,

would'nt it be great to be able to make groups with administrators/moderators ?
i searched for something in the issues but couldn't find anything.

the thing would look like this:
* an activity feed where only members could publish in it.
* it would be managed by administrators, chossing who can be invited to contribute.
* anyone can create a group, and administrate several groups if they want.
* we can choose the visibility of the feed to people external to the group.

(i am a web dev, so i can provide help in here)

**Comment by SuperTux88** [comment] 2018-10-10 09:57
Duplicate of #6278

**Closed by SuperTux88** 2018-10-10 09:57 UTC

**Comment by Flaburgan** [comment] 2018-10-10 10:18
Hi @tykayn and thank you for sharing your idea! As SuperTux pointed out, the group feature has already been suggested. Nobody's working on that issue at the moment, so you can comment on #6278 if you want to contribute. Be aware though that this is a very big task and probably a good start for a new comer, please read [our wiki page](https://wiki.diasporafoundation.org/Getting_started_with_contributing) about first contributions. Welcome!
