### ISSUE TITLE
Facebook service is gone

### ISSUE THREAD

**Issue by polsVoice** [diaspora/diaspora#5949] opened 2015-05-12 00:18 UTC
I recently changed my Facebook password, so I disconnected the service from my Diaspora account so that I could re-connect with my new password. However, as soon as I hit the "Disconnect" link, Facebook disappeared from Services entirely. (I heard that the FB service was broken due to FB's new API. Was it removed entirely?)

**Comment by denschub** [comment] 2015-05-12 01:52
Are you using your own pod? If not, which pod are you on?

**Comment by polsVoice** [comment] 2015-05-12 08:44
@denschub I'm on diasp.org. I don't know whether or not those issues are related to this issue. They don't sound quite the same. I mean, I don't even have the option available anymore. In my services, there is only "Connect to tumblr", "Connect to Twitter", and "Connect to WordPress".

"Connect to Facebook" is gone.

**Comment by dmorley** [comment] 2015-05-12 14:32
I am sure its related. I just disconnected and tried to reconnect and got. 
Invalid Scopes: publish_stream, offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by denschub** [comment] 2015-05-12 15:32
So, duplicate of #5085.

**Closed by denschub** 2015-05-12 15:32 UTC
Labels: needs more info
