### ISSUE TITLE
Sharing anomaly after stop ignoring a previous contact

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#4757] opened 2014-01-31 16:51 UTC
If you ignore someone who was sharing with you and then remove that block and add them to an aspect again, the profile sidebar tells you that they are not sharing with you (even though you are still in one of their aspects).

Steps to reproduce:
1. Set up two accounts, User A and User B.
2. User A places User B in to an aspect. (User B can also place User A into an aspect, although I don't think this is necessary.)
3. User B ignores User A.
4. User B removes the block on user A and adds them to an aspect again (adding them to an aspect might also not be necessary).
5. User B navigates to User A's profile page.

The profile sidebar is grey with a circle to inform that User A is not sharing with User B, although they are. I tested this by posting a message from User A limited to all aspects, and this showed up on User B's screen.

Also, User A is able to start a new private conversation with User B, but User B cannot now start a new private conversation with User A, although they can reply to a conversation started by User A.

There is a side issue to this: when you remove the block on a previous contact and add them to an aspect again, they receive a fresh notification that you have started sharing with them. This gives an indication that you may previously have been ignoring them, which I don't think we want. I suggest that when you remove the block from a previous contact, a dialog asks whether you wish to restore them to the aspects you had them in previously, and if you say yes, they do not receive a notification that you are now sharing with them again.
##

**Comment by Flaburgan** [comment] 2015-04-27 19:58
I just found that bug again and explain the problem in the JS in #5897 
But as you said, the view problem is not the only one: we also have a bug in the back-end because now, the user blocked and then unblocked still sees the other user as part of his aspect. There definitely is something quite critical here.

**Comment by svbergerem** [comment] 2017-03-21 15:46
This issue seems to be fixed now. When blocking a user we remove them from all aspects but we aren't removed from the other user's aspects. Did I miss something or can we just close this?

**Comment by Flaburgan** [comment] 2017-03-21 15:55
I will have another look as I played with ignore locally yesterday with #7379 and I still feel something is strange.

**Comment by SuperTux88** [comment] 2017-03-25 21:29
As I remember correctly, I removed everything that can cause this, so I think it should be fixed. I think #7382 was the last thing, with displaying wrong information, but in the database should be the correct state. But yeah, "needs more info" when @Flaburgan still thinks something is strange.

**Comment by svbergerem** [comment] 2017-08-17 14:50
@Flaburgan Ping. :)

**Comment by Flaburgan** [comment] 2017-08-27 20:41
I didn't reproduce any bug now. I was quite sure there was a bug in https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/app/models/person.js a related file with the usage of the `isBlocked`, `isSharing`, `isReceiving`... methods but I can't find a problem, maybe you want to have a quick look of that part of the code before closing, but if you found nothing then we can close that.

**Comment by svbergerem** [comment] 2017-08-28 00:03
We only use these methods in the profile header view presenter. Let's close this issue.

**Closed by svbergerem** 2017-08-28 00:03 UTC
Labels: bug, data issue, needs more info
