### ISSUE TITLE
Low contrast for logo

### ISSUE THREAD

**Issue by eloydegen** [diaspora/diaspora#4610] opened 2013-11-30 22:13 UTC
The logo in the top to go to the beginning of the page is gray/black, but the background is also black/gray. I made a white logo wich is way better visible. (It could be improved, but it is for the idea)

![logo](https://f.cloud.github.com/assets/3866292/1649536/40e0ac1e-5a0c-11e3-9cc0-3717be87bdd1.png)

**Comment by svbergerem** [comment] 2015-07-21 15:25
We don't use that logo in the header anymore so this issue is now a duplicate of #5270.

![navbar](https://cloud.githubusercontent.com/assets/3798614/8219401/2f55d2ee-154a-11e5-8b09-b9ebc4d1cc89.png)

**Closed by svbergerem** 2015-07-21 15:25 UTC
Labels: feature
