### ISSUE TITLE
Bug in setting HELO for SMTP?

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#8290] opened 2021-09-06 14:21 UTC
I don't remember where, but @SuperTux88 pointed that the reason some users don't receive e-mails sent by my pod https://diaspora-fr.org is because the HELO domain isn't correctly set, and this is indeed the case:

```
Return-Path: <nepasrepondre@diaspora-fr.org>
Delivered-To: flaburgan@XXXXX
Received: from localhost (HELO queue) (127.0.0.1)
	by localhost with SMTP; 6 Sep 2021 15:36:34 +0200
Received: from unknown (HELO output25.mail.ovh.net) (10.108.106.101)
  by mail150.ha.ovh.net with AES256-GCM-SHA384 encrypted SMTP; 6 Sep 2021 15:36:34 +0200
Received: from vr49.mail.ovh.net (unknown [10.101.8.49])
	by out25.mail.ovh.net (Postfix) with ESMTP id 4H38ZB34ThzHLLP15
	for <flaburgan@XXXX>; Mon,  6 Sep 2021 13:36:34 +0000 (UTC)
Received: from in37.mail.ovh.net (unknown [10.101.4.37])
	by vr49.mail.ovh.net (Postfix) with ESMTP id 4H38ZB1VbMz1sr4nP
	for <flaburgan@XXXX>; Mon,  6 Sep 2021 13:36:34 +0000 (UTC)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=91.121.29.72; helo=diaspora-fr; envelope-from=nepasrepondre@diaspora-fr.org; receiver=flaburgan@XXXX 
Authentication-Results: in37.mail.ovh.net; dkim=none; dkim-atps=neutral
Received: from diaspora-fr (ns300193.ip-91-121-29.eu [91.121.29.72])
	by in37.mail.ovh.net (Postfix) with ESMTPS id 4H38ZB0kGGz1GqqfQ
	for <flaburgan@XXXX>; Mon,  6 Sep 2021 13:36:34 +0000 (UTC)
Received: from localhost ([127.0.0.1] helo=diaspora-fr.org)
	by diaspora-fr with esmtp (Exim 4.86_2)
	(envelope-from <nepasrepondre@diaspora-fr.org>)
	id 1mNEnU-0001c4-FU
	for flaburgan@XXXX; Mon, 06 Sep 2021 15:36:28 +0200
```

As you can see, we have here `helo=diaspora-fr`: it misses the `.org` to be the real domain.

However, I checked my diaspora.yml file and the domain is correctly set:
```
mail:
  smtp:
      ## The domain for the HELO command, if needed.
      domain: 'diaspora-fr.org'
```

I checked the code at https://github.com/diaspora/diaspora/blob/develop/config/initializers/mailer_config.rb but everything looks fine there. Is there a bug in diaspora? Do I have a config problem elsewhere?

**Comment by SuperTux88** [comment] 2021-09-06 14:47
(The related comment was here: https://github.com/diaspora/diaspora/issues/8138#issuecomment-906034894)

This is not a bug in diaspora, this is a setup issue. Diaspora talks to the mailserver configured in the `diaspora.yml`/`diaspora.toml`, and uses the configures `HELO` which you can also see in the first `Received` block (`Received` blocks are read from the bottom to top): `Received: from localhost ([127.0.0.1] helo=diaspora-fr.org)`. This is everything diaspora can control, everything else is outside of diasporas control and is your setup.

It looks like already in the next step the `.org` gets lost, when `91.121.29.72` (which looks like it is your server) talks to `in37.mail.ovh.net` it only uses `diaspora-fr`. So it looks like you have an Exim installed on your server, diaspora talks to Exim using the correct `HELO`, but then Exim uses something else to talk to the next server in the row. I'm not very familiar with Exim (I use Postfix), but you need to check how to tell your Exim what it should use as `HELO` when talking to other mailservers (maybe `diaspora-fr` is your hostname and Exim uses just the hostname as `HELO` by default? But you can probably set to something else).

I'm closing this here, since this is a setup issue and not a diaspora bug. If you have more questions you can create a topic in discourse.

**Closed by SuperTux88** 2021-09-06 14:47 UTC

**Comment by Flaburgan** [comment] 2021-09-06 15:10
Thank you! Exim is indeed using the domain name of the server, which was set to diaspora-fr
So running `~$ hostname diaspora-fr.org` and modify `/etc/hostname` (for the setting to survive reboot) was enough to solve it. Hopefully mails will arrive now.
