### ISSUE TITLE
Add WYSIWYG editor to private messages

### ISSUE THREAD

**Issue by 4ndyD** [diaspora/diaspora#7097] opened 2016-09-13 02:32 UTC
It's not entirely clear what markdown can be used in Conversations. It seems that images don't embed (I'm guessing to protect privacy by not having your contact make requests to the server hosting them), and having the text editor from #6551 in place there would make life easier for many people.

**Comment by svbergerem** [comment] 2016-09-13 08:22
Duplicate of #5210.

Embedding images with markdown should be working in conversations just like everywhere else. (Although we still render the messages server side  using redcarpet instead of client side using markdown-it)

**Closed by svbergerem** 2016-09-13 08:22 UTC
Labels: feature, ui
