### ISSUE TITLE
Closed account still getting notification emails

### ISSUE THREAD

**Issue by wiegelmann** [diaspora/diaspora#8070] opened 2019-10-18 19:26 UTC
After an account is closed users still getting notification emails.

Related to issue #6221

**Comment by denschub** [comment] 2019-10-18 21:33
This is technically impossible, [as we set the email address to a non-functioning `@example.com` address inside the account deletion](https://github.com/diaspora/diaspora/blob/995f3394a86ae1df2814d8242771d44d86bf4bc0/app/models/user.rb#L562).

Please elaborate on your case. How was the account that still receives emails closed?

**Comment by Dartan** [comment] 2019-10-25 16:46
@jhass was helping me close accounts through the Ruby console and some of them failed because of deadlocks and didn't truly close (they appeared closed but the email was still on the account). I was able to get them closed by running the following in the Ruby console:

AccountDeletion.uncompleted.each(&:queue_delete_account)

**Comment by denschub** [comment] 2019-10-25 17:24
That's mildly concerning. Do you know where it deadlocked?

**Comment by Dartan** [comment] 2019-10-25 17:27
This is what was in the dead queue in sidekiq:

ActiveRecord::Deadlocked: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `users` SET `users`.`unconfirmed_email` = NULL, `users`.`confirm_email_token` = NULL ...

**Comment by Dartan** [comment] 2019-10-25 17:29
It's worth noting that I was trying to delete about 200 bot accounts at once so that probably had something to do with it.

**Comment by wiegelmann** [comment] 2019-10-25 19:04
Ok in my case not a bug, just an old db schema. The dead job said:

> ActiveRecord::NotNullViolation: Mysql2::Error: Column password_salt cannot be null: UPDATE users SET encrypted_password...

Dropped the password_salt column and the AccountDeletion works like a charm.

**Closed** 2019-10-26 07:58 UTC
Labels: 😐 weird
