### ISSUE TITLE
On the photo page: Add a button which directs to the singele post view of each photo

### ISSUE THREAD

**Issue by kas70** [diaspora/diaspora#6610] opened 2015-12-30 14:01 UTC
Currently it's only possible to show the photos in the gallery without comments/likes etc..

**Comment by Flaburgan** [comment] 2015-12-30 15:34
Isn't the Single Post View enough?

**Comment by jaywink** [comment] 2015-12-30 15:52
> Isn't the Single Post View enough?

I'm assuming at least that "directs to the post" == single post view.

**Comment by kas70** [comment] 2015-12-30 16:04
@jaywink yup. i edited the title.

**Comment by yurkobb** [comment] 2016-01-01 16:18
I second this. It's not only about comments/likes, but about the context of the photo (the text content of the post). It may contain information such as what the photo is about, who is the author etc. Having a gallery of the photos without any way to reach the original post is of very limited use.

**Comment by Fensterbank** [comment] 2016-01-02 21:52
I noticed this issue too and began to implement it a few days ago.

It will look like this and contains meta information (post date, likes, comments and reshares) and a button which opens the single post view.

![diaspora-gallery](https://cloud.githubusercontent.com/assets/1684826/12076234/e8a0a1bc-b1a2-11e5-81b2-36e59ce25116.png)

We should avoid to show more information of the post (like content) in the gallery, because the content could be huge.

**Comment by jaywink** [comment] 2016-01-04 20:46
@Fensterbank looks awesome! :+1:

**Comment by jhass** [comment] 2016-01-07 14:11
Not yet merged, closing this as a duplicate of #6236

**Closed by jhass** 2016-01-07 14:11 UTC
Labels: feature
