### ISSUE TITLE
Allow contacts to see the previous posts

### ISSUE THREAD

**Issue by spontex** [diaspora/diaspora#6596] opened 2015-12-22 11:00 UTC
When you add a friend, he can't see previous stuff posted in your aspect.
This is a show stopper for Diaspora, since you cannot "attract" your friends and family: when they sign up and log in, they will only see an empty page but not your latest great posts, and may never come again. They must wait to be added to one of your aspects and come a second time to see something.

I believe that the default behaviour in the main social networks (which I don't use) is that you can see stuff as soon as you accept an invitation.

- The ability to "add an e-mail address" to an aspect could generate a unique private link allowing to register and to be automatically added.
- When added to an aspect, one should see all the previous posts to that aspect.

Thanks

**Comment by svbergerem** [comment] 2015-12-22 11:59
This is a duplicate of #5905. @jhass explained there why diaspora behaves like this:

> Yes, this is by design, aspects define the recipients at the time of posting, not at the time of viewing. This is to avoid accidental leak of a private post to an unwanted recipient and makes the federation protocol a lot easier as a side effect.

**Closed by svbergerem** 2015-12-22 11:59 UTC

**Comment by spontex** [comment] 2015-12-22 12:59
This is a pity. I would so much like to attract new friends and family and share with them all my previous photos...
Then there could be a new feature like "share again all this aspect posts"?

**Comment by AugierLe42e** [comment] 2015-12-22 13:30
I admit that this looks like an issue to me. I agree diaspora has to gives protection against data leaks, but it also have to reduce accessibility friction. Any newcommer would expect diaspora act like this because this is how traditional SN act. This issue should stay open, IMHO.

**Comment by cmrd-senya** [comment] 2015-12-22 14:05
I think it's not very hard to implement, you just have to push all previous post for the aspect to a new aspect member. I think we could add this at least as an option (like a setting for an aspect - whether to push old post to new members or not).

**Comment by spontex** [comment] 2015-12-22 14:47
Ok, this could be an option ("Share again previous posts with this contact" when adding a new aspect member ).
Is there an internal recording of the aspects related to each post? I wonder because they do not appear, it is only written "Limited" for private posts.
