### ISSUE TITLE
Tabulation seems to be inserted after each line break in code blocks of a reshare in stream.

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/diaspora#6253] opened 2015-07-27 10:48 UTC
Here is an exemple:

* original post:

![original](https://cloud.githubusercontent.com/assets/3429231/8904154/594cb02c-345d-11e5-8079-6fe303d1ca74.png)

* reshare:

![reshare1](https://cloud.githubusercontent.com/assets/3429231/8904175/80291c8a-345d-11e5-9ecd-a8993edfba10.png)

It doesn't do this on SPV:

* [original post](https://diaspora-fr.org/posts/1412151),
* [reshare](https://diaspora-fr.org/posts/1412225).

**Comment by svbergerem** [comment] 2015-07-27 11:54
I guess this is caused by the following handlebars issue: https://github.com/wycats/handlebars.js/issues/858

We are using exactly one partial in handlebars and that is the status-message partial inside of reshares.

**Comment by Flaburgan** [comment] 2015-08-23 09:30
#6253 is merged, this can be closed.

**Closed** 2015-08-23 09:30 UTC
Labels: bug, ui
