### ISSUE TITLE
Bolded markdown URLs broken in two distinct ways.

### ISSUE THREAD

**Issue by gordon-morehouse** [diaspora/diaspora#5874] opened 2015-04-21 15:48 UTC
### WHAT ACTUALLY HAPPENS

1. Enter a bolded bare URL such as `**http://www.google.com/**`
2. Post
3. URL is not presented in bold and has two asterisks appended when clicked.

Italics not tested.

### WHAT I EXPECT TO HAPPEN

The URL should be presented in bold without markup cruft dangling from either end in the href.

**Comment by svbergerem** [comment] 2015-04-21 16:07
> URL is not presented in bold

The HTML for those URLs is ok. We just need to change the CSS:
![strong url](https://cloud.githubusercontent.com/assets/3798614/7256677/e7272598-e850-11e4-9ffb-6ee2f3832996.png)

> has two asterisks appended when clicked

I am not able to reproduce that.

**Comment by svbergerem** [comment] 2015-04-30 09:10
#5887 fixed the first issue. Since I wasn't able to reproduce the second one, I'll close this. Feel free to reopen if you are able to reproduce the second issue again.

**Closed by svbergerem** 2015-04-30 09:10 UTC
Labels: bug, newcomer, ui
