### ISSUE TITLE
librejs ecmascript errors

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6807] opened 2016-04-20 18:16 UTC
Install gnu/linux icecat web browser

Unable to sign-in using icecat web browser. Diaspora fails to recognise librejs

http://www.fsf.org/campaigns/jstrap

**Comment by jhass** [comment] 2016-04-20 18:26
Duplicate of #6103

**Closed by jhass** 2016-04-20 18:26 UTC
