### ISSUE TITLE
Boolean logic search function

### ISSUE THREAD

**Issue by githubgnulinux** [diaspora/diaspora#6214] opened 2015-07-20 12:50 UTC
Please allow boolean search logic to be applied to multiple tags within the search dialogue box.

For example #bug AND #diaspora AND #tor NOT #orbot, will search for posts the meet this criteria.

**Comment by jhass** [comment] 2015-07-20 12:56
Duplicate of https://www.loomio.org/d/6SCqkjph/improve-the-search-engine

**Closed by jhass** 2015-07-20 12:56 UTC
