### ISSUE TITLE
Search by tags doesn't work

### ISSUE THREAD

**Issue by nicubuga** [diaspora/diaspora#6733] opened 2016-03-03 06:27 UTC
It doesn't!

**Comment by Flaburgan** [comment] 2016-03-03 08:20
I guess your pod is joindiaspora.com?diaspora/diaspora a écrit :It doesn't!

—Reply to this email directly or view it on GitHub.


  
  


Envoyé depuis Firefox OS

**Comment by nicubuga** [comment] 2016-03-03 08:38
joindiaspora, punkbeer, diasp.eu, etc. Only socializer or smth worked... (and some other site in shrek-style)

**Comment by Flaburgan** [comment] 2016-03-03 08:43
This is probably a duplicate of https://github.com/diaspora/diaspora/issues/6152

**Comment by svbergerem** [comment] 2016-03-03 12:59
What exactly isn't working? You wrote

> Search by tags doesn't work

so nothing happens when you put a hashtag into the search form in the header? Are you redirected to any error page? Or do you mean instead that the tag stream doesn't load any posts? (which would be a duplicate of #6152)

**Comment by nicubuga** [comment] 2016-03-04 08:29
Flaburgan, svbergerem - yup it's #6152. Do you remember these issues? This is my second complaint that has already been pointed out...

**Comment by jhass** [comment] 2016-03-04 09:59
Closing as a duplicate.

**Closed by jhass** 2016-03-04 09:59 UTC
