### ISSUE TITLE
Allow full-screen and full-size view of photos

### ISSUE THREAD

**Issue by X3KT0** [diaspora/diaspora#7888] opened 2018-10-12 10:31 UTC
Can you please allow viewing photos attached to posts in full-screen mode and in the photo's full size?

**Comment by goobertron** [comment] 2018-10-12 11:02
This is a duplicate of #7664, which has been marked 'needs discourse', i.e. needs to be discussed before anything is done in Github. And there's a discussion open in Discourse [here](https://discourse.diasporafoundation.org/t/high-resolution-full-sized-images-for-lightbox/434/).

Please close this ticket and contribute to the Discourse discussion if you have further ideas. Thanks.

**Comment by Flaburgan** [comment] 2018-10-12 11:12
Thank you @X3KT0 for filling a bug!

@goobertron  Hm, actually, I see two different issues: the allowed weight (so, in bytes) of uploaded pictures (currently limited to 4MB, in the coming 0.8 major version, diaspora* will resize the picture automatically to be under that weight), and the size on screen (so, in px).

This issue here is about the size on the screen. The first post of the other issue looks more about the weight of the file (and I guess that's why it needs discourse). But as said now there is an automatic resize done, so the problem is only about pixels.

I will close this in favor of #7664 and post there to explain the problem changed.

@X3KT0 waiting for it, know that if you right click on an image and remove the "scaled_full_" in the path to only have the image id, then you will have the raw file.

**Closed by Flaburgan** 2018-10-12 11:12 UTC
