### ISSUE TITLE
"failed to post"

### ISSUE THREAD

**Issue by stoneartist** [diaspora/diaspora#5575] opened 2015-01-18 04:09 UTC
# bug #help #peace #orthodoxy_twisted 
###  thanks for you'se all do - i'd fix it if i could . ( show me how and i'll be happy to "monkey see , monkey do" )  

the above also would not post ? i'm sure it's my own doing . ?

* 8:05 pm - tried a number of different channels mobile/desktop 

have i been hacked . ?

stoneartistevens@gmail.com not sure what user name is , maybe stoneartist@joindiaspora.com ? If you can help thanks ,

**Comment by stoneartist** [comment] 2015-01-18 04:19
and it would seem each of the efforts to post - actually posted . ?

**Comment by dgets** [comment] 2015-01-18 07:14
Yeah I'm actually just going to update one of my issues added right now because joindiaspora.com has been reporting that comments and posts aren't published when they actually are if you can get the feed to update.

I'm sure the repository maintainers here are just loving this.

**Comment by goobertron** [comment] 2015-01-18 13:01
This is a long-standing issue, particularly with joindiaspora.com, which has many performance issues due to overloading. See #3688.

**Comment by stoneartist** [comment] 2015-01-18 23:10
overloading , meaning too many users or from a user reposting over and over not knowing that it had posted . ? also i was able to delete some multiples of the original [#]bug message, but at this turn it would seem the db won't remove the remaining post. thanks again - when i can , i'll try and throw money into the diaspora "crankcase" please say which port would be the most useful ; if it's a monthly deduction of $3 for coffee , so be it - pretty heady stuff to think you may the engineers on "radio free earth" as we lurch into the abyss .  .

**Comment by svbergerem** [comment] 2015-05-03 15:12
Is this a duplicate of #3688?

**Comment by stoneartist** [comment] 2015-05-03 15:46
i don't know . i haven't encountered the error in several months .

**Comment by svbergerem** [comment] 2015-05-29 23:55
I will close this issue now. Feel free to reopen if you are able to reproduce this again. (Maybe on a pod which is not joindiaspora :-P)

**Closed by svbergerem** 2015-05-29 23:55 UTC
