### ISSUE TITLE
feature: simplify post formatting; ideas

### ISSUE THREAD

**Issue by dystopiacybernetica** [diaspora/diaspora#5261] opened 2014-09-30 18:49 UTC
I know I'm probably asking for something already thought about and/or discarded; anyway, I think it'd be a very cool feature to have some built-in text editor, instead of having to open the markup instructions window and copy-paste the code (especially when it's about custom links or images, cause it's really a pain in the ass). Or maybe, if that would be too much of a problem at a code level, just give the option: insert photo--> "upload" [already there] and "from URL".

(sorry for the mess in trying to explain my idea in english)

**Comment by svbergerem** [comment] 2015-07-21 15:48
Duplicate of #5801.

**Closed by svbergerem** 2015-07-21 15:48 UTC
Labels: feature
