### ISSUE TITLE
Photo album and organization of photos

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#7233] opened 2016-11-30 18:07 UTC
Hello, first of all I think it's good to add the possibility of creating photo albums, to put photos of an event on the album.
Today all the photos that we upload, do not have this organization and it is difficult to find photos of a past event when you have more than 300 photos stored. With the photo albums it would be a matter of putting the images on that album.

Second. When we create a publication in which they have photos attached, there is the possibility of automatically adding them to an existing album or creating a new one. Maybe by default it could be left in the photos part and then the user can move them to the existing albums.

Third. That the albums follow the same permissions of the publications, through the Aspects.

Fourth. You have a hyperlink Photos in the Input panel to facilitate access to the user's photos.

**Comment by SuperTux88** [comment] 2016-11-30 18:20
Duplicate of #3904

**Closed by SuperTux88** 2016-11-30 18:20 UTC
