### ISSUE TITLE
Inconsistent hashtag propagation

### ISSUE THREAD

**Issue by ntnsndr** [diaspora/diaspora#7114] opened 2016-09-19 22:21 UTC
I'm a university professor interested in using Diaspora* as a teaching tool and as a means of collaboration among my students. However, we found that we were unable to use a hashtag as a means of communicating with one another. For instance, we noticed that our hashtag on two separate pods resulted in seeing, in each, a different subset of the posts we made to that hashtag:

https://framasphere.org/tags/cucmp
https://diasp.org/tags/cucmp

Is this a known issue? Or is there something that we're missing?

Thanks to you all for your good work on this important project.

**Comment by denschub** [comment] 2016-09-19 23:32
Not an issue, just a non-exisiting feature.

Dupe of #2407.

**Closed by denschub** 2016-09-19 23:32 UTC

**Comment by Flaburgan** [comment] 2016-09-20 06:36
You can read more about that [here](http://geexxx.fr/2013/07/23/comment-ca-marche-la-federation-de-diaspora/#english). Even if the federation quite changed since I wrote this blogpost (thanks to @SuperTux88), the tag behavior is still the same.
