### ISSUE TITLE
[Federation] Send the mentionned user to pods with the post

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#5369] opened 2014-10-23 09:30 UTC
When someone sends a post where he mentions a user, the mention will not appear in the post on the pods which don't know this user. The user should be either sent by the pod in the same time than the message or fetched by the pods which don't know him, to be able to display the mention.

**Comment by svbergerem** [comment] 2015-01-04 16:33
I think this is a duplicate of #4491.

**Closed by svbergerem** 2015-01-04 16:33 UTC
Labels: feature

**Comment by Flaburgan** [comment] 2015-01-04 18:49
You're right, we discussed about it with Jonne and I forgot to close this one, sorry.
