### ISSUE TITLE
Weird behavior with Unicode 6.3 chars

### ISSUE THREAD

**Issue by polsVoice** [diaspora/diaspora#4804] opened 2014-02-23 05:56 UTC
I was playing around with some of the newer Unicode characters, and got some strange results. For example, I tried pasting U+1F63C into my name. It pastes in fine, but it won't save. Different things happened every time I tried to save it: the first time, it cleared the name field, the second and third times it just reset it.

What's really weird, though, is what happens if you try to put it into a post. It showed up fine in Preview, but then when I saved the post, it appeared as a box. When I reloaded the page, the box had disappeared, and the entire rest of the post after it had been erased!

I get similar results with other new characters ([the emoticons U+1F60x-U+1F64x](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Emoji) and the [game cards U+1F0Ax-U+1F0Fx](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Game_Symbols)).

**Comment by witgithacker** [comment] 2015-01-13 06:00
http://2014.jsconf.eu/speakers/mathias-bynens-javascript-loves-unicode.html ?

**Comment by jhass** [comment] 2015-01-13 11:10
Probably related to #5530

**Comment by svbergerem** [comment] 2015-04-04 01:44
Maybe a duplicate of #5147. Would be great if @denschub could test both after the 0.5.0.0 release because AFAIK both have been reproduced on his pod.

**Comment by cmrd-senya** [comment] 2015-04-10 00:23
I don't know, if it is related to the bug, but besides the bug I have the following problem.  

If I post to diaspora with a json request and a message contains emoticons, I got everything cut after the emoticon, including itself.  

The following (pseudo) example
```ruby
request = Net::HTTP::Post.new(uri.request_uri,initheader = {'Content-Type' =>'application/json'})
msg = "ffff 😃 tttt"
request.body = { "status_message" => { "text" => msg, "provider_display_name" => @providername }, "aspect_ids" => aspect}.to_json
return http.request(request)
```
makes a post and the post looks like "ffff ".  

A real-life test can be done with my [diaspora-api](https://github.com/cmrd-senya/diaspora-api) gem.  

I wonder if this problem has anything to do with diaspora? Or maybe it is just json or http level?

**Comment by denschub** [comment] 2015-04-10 01:51
@cmrd-senya Did you test on the latest release or the 0.5.0.0-rc?

**Comment by cmrd-senya** [comment] 2015-04-11 12:07
I tested it with the release, and for some reason json request { "status_message" => { "text" => msg, "provider_display_name" => @providername }, "aspect_ids" => aspect} doesn't work with 0.5.0.0 at all (tested on diasp.ca). Any ideas why?

**Comment by jhass** [comment] 2015-04-11 12:21
"doesn't work" is not very helpful. What do you get?

**Comment by cmrd-senya** [comment] 2015-04-11 12:33
For both 0.4.1.2 (socializer.cc) and 0.5.0.0 (diasp.ca) I receive the answer
```html
<html><body>You are being <a href="https://diasp.ca/users/sign_in">redirected</a>.</body></html>
```

I am making post request to https://diasp.ca/status_messages. Is that correct?  

The same request for https://socializer.cc/status_messages works fine.

**Comment by jhass** [comment] 2015-04-11 12:38
I don't follow, you seem to contradict yourself. You say you're getting redirected to sign in on both pods, yet you say it works fine on one?

**Comment by cmrd-senya** [comment] 2015-04-11 12:43
I get 302 as the answer for my POST json request (post a status message), but in case of 0.4.1.2 my status message get posted, while in 0.5.0.0 - not.

**Comment by jhass** [comment] 2015-04-11 12:44
Details matter here, is the response identical in both cases? Same headers, same body?

**Comment by jhass** [comment] 2015-04-11 12:46
Also more importantly this bug is about posting a post with Unicode codepoints outside the BPM, using regular methods. Doing so by abusing our application internal APIs is unsupported, which we made clear in the past, and something to figure out on your own.

**Comment by cmrd-senya** [comment] 2015-04-11 12:48
Yes, I do it with [the script](https://github.com/cmrd-senya/diaspora-api/blob/master/lib/diaspora-api.rb), [post method](https://github.com/cmrd-senya/diaspora-api/blob/master/lib/diaspora-api.rb#L76).

I invoke it in the following way:
```ruby
require '/home/senya/diaspora-api/lib/diaspora-api.rb'

c = DiasporaApi::Client.new

#if c.login("https://socializer.cc", "senya", "password")
if c.login("https://diasp.ca", "senya", "password")
	t = "hurr durr"
	a=  c.post(t, "test")
	puts a
	puts a.body
end

**Comment by cmrd-senya** [comment] 2015-04-11 12:51
I understand, sorry for the offtopic.  
If you could (and want to) help me in anyway, we can move the discussion to a different place.  
I think client interface for Diaspora is still important for the project, though no official efforts is done. It eventually helps to make D* a better place.

**Comment by jhass** [comment] 2015-04-11 12:55
The official efforts are done, finding an authentication scheme that works in this context is just easier said than done.

**Comment by denschub** [comment] 2015-05-04 00:53
Closing; working on MySQL and PostgreSQL with 0.5.0.0.

**Closed by denschub** 2015-05-04 00:53 UTC
Labels: bug, post parsing
