### ISSUE TITLE
cross-pod picture bug in posts

### ISSUE THREAD

**Issue by viisauksena** [diaspora/diaspora#5674] opened 2015-02-16 09:54 UTC
Making a Limited Post - on the sender Pod everything looks fine but at the receiving pod there is this extra thumbnail (see picture) ... the original post consists of [some text, some youtube link and a picture]
the receiving pod is on latest code 
Code head-pe9179e33  https://pod.rauberhaus.de/source.tar.gz
![diaspora-picture-bug](https://cloud.githubusercontent.com/assets/10057308/6209786/b303a2e6-b5c9-11e4-9110-79e10ce6fcaf.png)

**Comment by svbergerem** [comment] 2015-02-16 11:33
Duplicate of #4697.

**Closed by svbergerem** 2015-02-16 11:33 UTC
