### ISSUE TITLE
if simple #hashtags are used in #compoundhashtags, email hashtags broken

### ISSUE THREAD

**Issue by gordon-morehouse** [diaspora/diaspora#5902] opened 2015-04-29 04:56 UTC
If I make a post that, in email notifications, sums up as "foo bar baz #lol #wat #lolhuh #fail #lolcats", then in said notifications, only the "#lol" part of the "#lolhuh" and "#lolcats" hashtags will be URL-ified, and that URL will link to #lol, not #lolhuh or #lolcats respectively.

**Comment by gordon-morehouse** [comment] 2015-04-29 04:56
(One way to reproduce this is to get someone to reshare a post you made with #simple hashtag first and #simplecompound hashtags later in the post; that's how I discovered it.)

**Comment by Flaburgan** [comment] 2015-04-29 07:01
yeah I saw that for a long time, forgot to report...

**Comment by svbergerem** [comment] 2015-05-03 09:51
I'm not able to reproduce this on develop:

**post**:
`#tag #hashtag #loltag #cat #lolcat`

**notification mail for "like"**:
```
...
<p>testuser@localhost:3000 liked your post:</p>
<p><a href="http://localhost:3000/tags/tag">#tag</a> <a href="http://localhost:3000/tags/hashtag">#hashtag</a> <a href="http://localhost:3000/tags/loltag">#loltag</a> <a href="http://localhost:3000/tags/cat">#cat</a> <a href="http://localhost:3000/tags/lolcat">#lolcat</a></p>
...
```

The same thing happens when someone reshares the post. I'll close this issue. Feel free to reopen if you are able to reproduce this on develop.

**Comment by Flaburgan** [comment] 2015-05-03 22:21
The bug is still there in the last develop, it's the beginning of the words:
`#test #testyeah`

`<p><a href=3D"https://diaspora-fr.org/tags/test">#test</a> <a href=3D"htt=
ps://diaspora-fr.org/tags/test">#test</a>yeah</p>`

**Comment by svbergerem** [comment] 2015-05-03 22:24
As I wrote above I'm not able to reproduce this but since you were able to do so I'll reopen.

**Comment by Flaburgan** [comment] 2015-05-03 22:25
@svbergerem test with the same first letters of tag. first #some and then #something and you'll see that "thing" is not part of the link for #something.

**Comment by svbergerem** [comment] 2015-05-03 23:30
@Flaburgan Ok, now I was able to reproduce the bug. m(

**Closed** 2015-05-31 00:25 UTC
Labels: bug, post parsing
