### ISSUE TITLE
Make the switch to the desktop view persistent on mobile

### ISSUE THREAD

**Issue by thedayofcondor** [diaspora/diaspora#7904] opened 2018-10-22 21:56 UTC
Hi, as the mobile view is still not fully functional, would it be possible to make the act of "toggling mobile" persistent (per device - eg stored in a cookie)?

It may just be me, but too many times I started writing a post, tried to mention someone, realise I am in mobile mode, have to copy what I have written, switch to desktop, paste the post and continue typing...

**Comment by derwendtde** [comment] 2018-12-28 18:54
Same here, I second that. I would consider it viable as well to add a 

`[pod.tld]/stream?PARAMETER` 

as well, so one can tell from the URL which mode has been chosen.

**Comment by Flaburgan** [comment] 2022-10-31 10:50
Hello, I'm not sure how you are fallback to the mobile version after having clicking on "Switch to desktop", in my case I'm staying on the desktop version after I clicked whatever I'm doing.

**Comment by Flaburgan** [comment] 2022-10-31 12:24
Actually this is a duplicate of https://github.com/diaspora/diaspora/issues/7332
Which means at least 3 persons had the problem but I still don't reproduce. Let's continue the discussions there.

**Closed by Flaburgan** 2022-10-31 12:24 UTC
Labels: ✨ feature
