### ISSUE TITLE
Unicode not properly rendered in Poll

### ISSUE THREAD

**Issue by Akhilan** [diaspora/diaspora#5024] opened 2014-06-24 07:32 UTC
Poll feature supports only english letters. it makes poll useless for all other languages.  
Eg: https://diasp.org/posts/3193904

![poll unicode](https://cloud.githubusercontent.com/assets/937169/3368228/7db5a57a-fb71-11e3-9fc3-a402bfad5e9a.png)

**Comment by svbergerem** [comment] 2015-03-11 09:24
Is anyone still able to reproduce this bug?

**Comment by VeevenV** [comment] 2015-03-11 16:36
Yes, still reproducible. Just created [a new poll on joindiaspora.com](https://joindiaspora.com/posts/5742394).

**Comment by svbergerem** [comment] 2015-03-11 16:49
@VeevenV could you post the question and the answers here on github? In the json file for that post are also question marks for question and answers so I think they are even like that in the database.

Would be great to have an example to test on a development pod.

**Comment by VeevenV** [comment] 2015-03-12 15:18
@svbergerem Here are the question and answers:

ఈ డయస్పోరా పోల్‌లో ప్రశ్నలూ జవాబులూ తెలుగులో కనిపిస్తున్నాయా?
* అవును
* కాదు

**Comment by Flaburgan** [comment] 2015-03-12 15:42
To be honest, there are not rendered correctly here on github and in my webmail too. So this looks like not diaspora dependent.

**Comment by jhass** [comment] 2015-03-12 15:44
@Flaburgan they are, you just miss the font:

![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150312_164409.png)

**Comment by svbergerem** [comment] 2015-03-12 15:46
@Flaburgan You just need the right fonts. When you are using a debian based OS `fonts-telu` will help you. (The language is Telugu)

**Comment by svbergerem** [comment] 2015-03-12 15:54
@VeevenV I am not able to reproduce this with the development version of diaspora* and MariaDB or PostgreSQL.
![](https://cloud.githubusercontent.com/assets/3798614/6621689/5bcc1630-c8d8-11e4-913d-76529a71f4b4.png)

We recently had some unicode related DB changes so I think we fixed this bug.

**Comment by VeevenV** [comment] 2015-03-12 16:13
@svbergerem Great. Hoping the fix will be released with 0.5.0.0.

**Comment by svbergerem** [comment] 2015-03-15 15:53
I'll close this. If anyone is still able to reproduce this with the development version we can reopen this issue.

**Closed by svbergerem** 2015-03-15 15:53 UTC
Labels: bug, needs more info, ui
