### ISSUE TITLE
display name entered during sign up is not persisting

### ISSUE THREAD

**Issue by pravi** [diaspora/diaspora#6323] opened 2015-08-16 12:43 UTC
It goes back to diaspora handle and it has to be enteted again in profile.

**Comment by svbergerem** [comment] 2015-08-22 19:12
I'm not able to reproduce this on develop. @pravi Could you list some steps to reproduce this? I tried the following:

1. Go to the sign up page
2. Enter email, username, password and captcha
3. Click on Sign up
4. On the getting started page enter your name ("Test User7" in my case)
5. Click on the big blue button

**Comment by svbergerem** [comment] 2016-01-22 00:14
I got no answer for half a year, so I'll close this issue. Please leave a comment if you are able to reproduce this.

**Closed by svbergerem** 2016-01-22 00:14 UTC
Labels: bug, needs more info
