### ISSUE TITLE
Where to put code for workaround for "internal server error" in admin panel?

### ISSUE THREAD

**Issue by k0sebamse** [diaspora/diaspora#7254] opened 2016-12-16 18:45 UTC
Hi,

as there is still the issue that some overviews in the admin panel die with a "500 internal server error" (e.g. when calling account deletions) I was trying to put the workaround found [here ](https://github.com/sferik/rails_admin/issues/1870#issuecomment-30716687) in my application.rb

As I have no experience with Ruby I tried it in several places (beginning of the file, end of the file, somewhere it looks meaningfull to me ;-)) but Diaspora refused to start afterwards.

So where do I have to add the code from the workaround to make my admin panel fully functional again?

Thanks in advance guys.

Cheers
Mirco

**Comment by SuperTux88** [comment] 2016-12-17 03:44
This is an issue tracker and not a support platform (if you have an error message, you can try to ask for help in [IRC](https://wiki.diasporafoundation.org/How_we_communicate#IRC)), also this is a duplicate of #7027

**Closed by SuperTux88** 2016-12-17 03:44 UTC
