### ISSUE TITLE
Mobile version width on Windows Phone 8.1

### ISSUE THREAD

**Issue by Tekarihoken** [diaspora/diaspora#5454] opened 2014-12-03 07:34 UTC
When using the mobile version of the website , when we are clicking on the menu. Instead of showing the menu in the screen it display it at the left side of the screen and show the right background on the screen.
It display it as if the screen was the twice of its actual size.

**Comment by jlnostr** [comment] 2015-01-03 18:40
Cannot reproduce it.
```
OS version: 8.10.14219.341
Device: Nokia Lumia 930
Pod: diasp.de
```

**Comment by Tekarihoken** [comment] 2015-01-04 14:07
This is a screenshot : 

![wp_ss_20150104_0001](https://cloud.githubusercontent.com/assets/614642/5606202/543454b2-9423-11e4-80cd-9e15305f60fa.jpg)

* OS version : 8.10.12393.890
* Device : Nokia Lumia 920
* Pod :  framasphere.org

**Comment by jlnostr** [comment] 2015-01-04 17:01
Could be possible that it is fixed with newer versions. On my device is the Developer Preview. Screenshot below.
![wp_ss_20150104_0001](https://cloud.githubusercontent.com/assets/5391936/5606713/98d3f740-943b-11e4-8517-65976b0ac251.png)

**Comment by Flaburgan** [comment] 2015-01-04 18:47
diasp.de doesn't use the develop version. What's your mobile @jlnostr?

**Comment by jlnostr** [comment] 2015-01-04 20:34
I am using a Nokia Lumia 930. OS version: 8.10.14219.341

Am Sonntag, den 04.01.2015, 10:47 -0800 schrieb Fla:

**Comment by Tekarihoken** [comment] 2015-01-06 00:29
In fact it seems that the way it is displayed on your mobile is also not correct some words are not complete.
Maybe the difference come from the difference of word size between German and French.

However this bug is very similar to a bug that I have had in the past with Loomio,and the dev have corrected it very quickly. I will see if there is some hints in the commit

**Comment by Tekarihoken** [comment] 2015-01-06 00:43
In fact it was due to an issue in bootstrap on IE10 and 11 on WP.
http://getbootstrap.com/getting-started/#support-ie10-width

**Comment by Flaburgan** [comment] 2015-01-07 09:37
@Tekarihoken we do not use bootstrap in the mobile version at the moment.

https://github.com/diaspora/diaspora/pull/5523 should improve this situation, I'll tell you here when it will be merged.

**Comment by svbergerem** [comment] 2016-02-07 22:38
#6233 has been merged some time ago which might have improved the situation. Would be great if anyone could check if this fixes the problem.

**Comment by Flaburgan** [comment] 2016-02-09 13:46
Tested with Nokia Lumia 530 running windows 8.1, this issue is solved and can be closed.

**Comment by svbergerem** [comment] 2016-02-09 13:49
Thank you!

**Closed by svbergerem** 2016-02-09 13:49 UTC
Labels: bug, mobile
