### ISSUE TITLE
Calendar and Events

### ISSUE THREAD

**Issue by dcapeletti** [diaspora/diaspora#7334] opened 2017-02-17 13:19 UTC
I found the idea of having a calendar in Diaspora useful and interesting.
The main reason is that someone could create an event and share it. Users could subscribe to the event so that when the time comes, Diaspora warns on his wall or sending an email warning.
It is also interesting to share a common calendar with people of the same aspect.
I just wanted to share the idea, it seems to me something useful for this social network. The social network Friendica has a calendar. I await your opinions.
Thanks

**Comment by svbergerem** [comment] 2017-02-17 13:22
Duplicate of #1359.

**Closed by svbergerem** 2017-02-17 13:22 UTC
