### ISSUE TITLE
Posts from current user shown in all aspects

### ISSUE THREAD

**Issue by gsantner** [diaspora/diaspora#7004] opened 2016-08-18 21:05 UTC
Happens on mobile and desktop view.
All posts from the current logged-in user are shown in all aspects.
E.g. if I want to show just the Aspect "Fun", I can e.g. goto <https://mypod.tld/aspects?a_ids[]=12345>, which should just show content from people inside this particular aspect.

Here is for example one of my posts shown in the aspect fun, where I expect just  content from people I added to the aspect Fun. Note that the post has no relation to a tag or aspect "Fun", nor it is liked or shared by anyone in the aspect.
<img width="30%" height="30%" src="https://cloud.githubusercontent.com/assets/6735650/17790452/cb906352-6596-11e6-9408-5bdb83abb41a.jpg" />

**Comment by Flaburgan** [comment] 2016-08-18 21:07
Did you post it in "Public", "All aspects" or the "Fun" aspect?

**Comment by gsantner** [comment] 2016-08-18 21:17
Good question, yeah maybe all aspects.
Tried it now,
All aspects, Public -> Visible in every aspect + Stream
Just for particular (Fun) -> Visible in Fun + Stream

I was just really suprised that, if I post multiple posts in a short time, the aspects with low activity did contain mostly just my posts on top.

The point is: For me personally it doesn't make sense to show posts from myself in the "Aspects" view. Currently Diaspora is designed to do so, but can this maybe be discussed?

**Comment by denschub** [comment] 2016-08-25 04:22
Yeah, this is not a bug. Discussions about such features can be made on Loomio, if you feel the need for it. Closing for now, will reopen if we actually decide something on Loomio, if there is a need!

**Closed by denschub** 2016-08-25 04:22 UTC
