### ISSUE TITLE
Cannot Unread notifications in /notifications?show=unread

### ISSUE THREAD

**Issue by paskalito** [diaspora/diaspora#7352] opened 2017-03-05 10:37 UTC
If i click on the eye sign nothing happens. also if i reload the page it is still listed.

tested with a privacy plugins loaded firefox and a completely standard chromium.
on GNU/Linux  / Code 0.6.99.0-p4928d2fb / nerdpol.ch

**Comment by SuperTux88** [comment] 2017-03-05 12:36
Thanks for reporting this, I was able to reproduce it. Some more informations:
* It is also in `/notifications`, not only for `/notifications?show=unread`
* The first 10 Notifications work, the rest doesn't work (if some of the last 10 are still unread, you can toggle them on `/notifications?show=unread`. So if you have already 3 read notification of the last 10, then you can only toggle 7 on `/notifications?show=unread`. If all last 10 notifications are already read, then on `/notifications?show=unread` nothing works.)
* When you open the notifications-dropdown and scroll down (load more notifications), more notifications work (So only notifications that are loaded in the dropdown work also on the page).

Error in Firefox:
```
TypeError: this.find(...) is undefined
	setRead http://localhost:3000/assets/app/collections/notifications.js:98:5
	toggleUnread http://localhost:3000/assets/app/views/notifications_view.js:25:7
	bound toggleUnread self-hosted:913:17
	dispatch http://localhost:3000/assets/jquery2.js:4737:16
	add/elemData.handle http://localhost:3000/assets/jquery2.js:4550:6
```

Error in Chromium:
```
Uncaught TypeError: Cannot read property 'setRead' of undefined
    at child.setRead (notifications.js?body=1:98)
    at child.toggleUnread (notifications_view.js?body=1:25)
    at HTMLDivElement.dispatch (jquery2.js?body=1:4738)
    at HTMLDivElement.elemData.handle (jquery2.js?body=1:4550)
```

**Comment by svbergerem** [comment] 2017-03-05 14:28
Duplicate of #7250. I changed the title over there.

**Closed by svbergerem** 2017-03-05 14:28 UTC
Labels: bug
