### ISSUE TITLE
Feature Request: Pin Posts to the top

### ISSUE THREAD

**Issue by koyuawsmbrtn** [diaspora/diaspora#6824] opened 2016-05-08 17:09 UTC
This should only apply to *public posts*, not private. There can be only one pinned post, that displays on top on the user profile. Twitter for example has this feature and this would be nice, if this feature will be implemented. I have lots of cool public posts and wish to have the ability to pin them on top, to inform people about something special, that they must read first....the sidebar is just too small for this, especially for long posts.

**Comment by denschub** [comment] 2016-05-08 22:54
Dupe of #6135.

**Closed by denschub** 2016-05-08 22:54 UTC
Labels: feature
