### ISSUE TITLE
Impossible to add + in a tag

### ISSUE THREAD

**Issue by InfoLibre** [diaspora/diaspora#8200] opened 2021-01-28 09:24 UTC
Example : in #canal+ , only #canal becomes a tag.
https://framasphere.org/posts/11155208

**Comment by ThorstenClaus** [comment] 2021-02-03 10:59
I don't think  a + is a valid character for hashtags at all.
 
The official hashtag for canal+ is #canalplus
See https://twitter.com/canalplus for reference.

**Comment by InfoLibre** [comment] 2021-02-03 11:01
The problem is not about Canal+ but about + in a hashtag (it could be Signal+, Vote+ or anything else).

**Comment by ThorstenClaus** [comment] 2021-02-03 11:11
I did understand this, but $, -, + & etc.. are no valid characters for Hashtags. e.g. Twitter stops 'hashing' on one of these characters.
Anyone with same or different opinion?

**Comment by InfoLibre** [comment] 2021-02-03 11:35
Can't features for diaspora* beeing better than Twitter rules ?

**Comment by tclaus** [comment] 2021-02-03 17:30
Can you ask this again in https://discourse.diasporafoundation.org again to get some more opinions?

**Comment by InfoLibre** [comment] 2021-02-03 20:48
Like this ?
https://discourse.diasporafoundation.org/t/feature-request-using-in-tag/3719

**Comment by denschub** [comment] 2021-02-03 21:53
Duplicate of the Discourse discussion linked above. Also, wontfix because of https://discourse.diasporafoundation.org/t/feature-request-using-in-tag/3719/4?u=denschub.

**Closed by denschub** 2021-02-03 21:53 UTC
