### ISSUE TITLE
Bookmarklet does not get adjusted after aspects are altered

### ISSUE THREAD

**Issue by hansw-nlo** [diaspora/diaspora#7897] opened 2018-10-16 07:34 UTC
Dear all, 

I used the bookmarklet (on joindiaspora) to post a few things. Works well but after adjusting the aspects (adding one) it does not show up. I removed it from my browser bar and recreated it but it still lacks the new aspect. Can this be a caching issue?

**Comment by hansw-nlo** [comment] 2018-10-16 07:46
It is a caching issue indeed. After deleting my history I was able to create a new bookmarklet with the new aspect.

**Comment by hansw-nlo** [comment] 2018-10-16 07:58
Adding the following to the bookmarklet page might resolve this issue:

Header set Expires "Thu, 19 Nov 1981 08:52:00 GM"
Header set Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
Header set Pragma "no-cache"

**Comment by hansw-nlo** [comment] 2018-10-16 08:01
response.set_header('HEADER NAME', 'HEADER VALUE') in Ruby I assume. Never wrote in that language.

Best regards,

Hans

**Comment by SuperTux88** [comment] 2018-10-23 23:58
Are you talking about `/bookmarklet` page itself? This already isn't cached: `cache-control:max-age=0, private, must-revalidate`. So unless your podmin overwrites/removes some headers, this shouldn't be cached. Can you please tell us the pod on which you have this problem?

**Comment by hansw-nlo** [comment] 2018-10-24 07:48
Yes, the bookmarklet page itself. I don't know why it keeps caching then.

**Comment by CSammy** [comment] 2018-10-24 16:39
> Can you please tell us the pod on which you have this problem?

@hansw-nlo This will help us track down the cause.

**Comment by hansw-nlo** [comment] 2018-10-24 16:41
CSammy, stated it in my original entry. Joindiaspora.com

**Comment by CSammy** [comment] 2018-10-24 17:54
> CSammy, stated it in my original entry. Joindiaspora.com

Sorry, we missed that.

**Comment by SuperTux88** [comment] 2018-10-24 20:16
Oh, I actually missed that. Anyway, I just checked joindiaspora and it sets the correct headers, for the /bookmarklet and for any other page. Maybe you have something in your browser that messes with caching? But then you probably would have more problems than only the bookmarklet.

Anyway, I'm closing this issue, because diaspora already sets the correct headers.

**Closed by SuperTux88** 2018-10-24 20:16 UTC
Labels: needs more info, weird
