### ISSUE TITLE
Missing comments on a reshared post

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora#7963] opened 2019-01-16 13:28 UTC
I don't know if this has already been noticed by federation masters, but it looks like a bug so I wanted to open an issue.

**STR:**
Users A1 and A2 on podA, user B on podB. User A2 is sharing with user B.
User A1 writes a public post and then comments on it (or any user comment on it).
A1 doesn't have any contacts on podB, so podA doesn't send the post on podB.
A2 reshares A1's post, making it arrives on podB.
User B can now find and read postA.

**Expected:**
Comments before and after the reshare are displayed on podB

**Actual:**
Only comments written after the reshare are displayed on podB

**Comment by SuperTux88** [comment] 2019-01-16 13:36
That's basically a duplicate of #3350. I already have a plan for how to fix this and parts are already implemented, and other parts I started working a few months ago, but didn't have the time to finish yet.

**Closed by SuperTux88** 2019-01-16 13:36 UTC
Labels: bug, federation
