### ISSUE TITLE
Like function

### ISSUE THREAD

**Issue by duyetpt** [diaspora/diaspora#6524] opened 2015-10-26 14:47 UTC
I use some sample as diaspora.openhosting.com, ... I must wait long time when I like some post to it response. Sometime, I can't like some post.

**Comment by jhass** [comment] 2015-10-26 14:50
Anybody knows the Github account of the podmin?

**Comment by jaywink** [comment] 2015-10-27 07:35
Ping @lazzarello

**Comment by lazzarello** [comment] 2015-10-28 22:51
OH HAI! what's up? I haven't noticed this.

**Comment by lazzarello** [comment] 2015-10-28 22:56
I'm not sure what the OP is looking for. My pod is in the eastern USA. I have a hunch he's coming from Asia, which is half way across the world. I do have some persistent (though infrequent) timeouts from the Ruby threads via Sidekiq and all I have to do is restart the worker process to get the queue processing jobs again. But that is probably not the issue. It sounds like a UI issue with network latency.

**Comment by jhass** [comment] 2015-10-29 11:14
@duyetpt so, any more info you can provide?

**Comment by svbergerem** [comment] 2016-02-08 01:20
No further info provided. This sounds like a duplicate of #3044.

**Closed by svbergerem** 2016-02-08 01:20 UTC
Labels: needs more info, setup issue
