### ISSUE TITLE
Hashtag and brackets

### ISSUE THREAD

**Issue by matthieu75** [diaspora/diaspora#5583] opened 2015-01-22 15:08 UTC
When a hashtag is just after the first bracket, it isn't transformed into a hashtag.
For example: ( #diaspora) works, but (#diaspora) doesn't.

**Comment by svbergerem** [comment] 2015-01-22 15:12
Hashtags need a whitespace in front of them. (on develop as well as on the master branch) I am not sure if we want to change that. There might be cases where that could break other stuff.

**Comment by jhass** [comment] 2015-01-22 15:13
The main conflict I would see is anchors in URLs, if the autolinking happens before the tag parsing, that should be no issue, right?

**Comment by ubuntu05** [comment] 2015-01-25 16:43
If it is going to cause too many conflicts, I don't think it should be changed.

**Comment by svbergerem** [comment] 2015-02-13 02:05
This is a duplicate of #4395.

**Closed by svbergerem** 2015-02-13 02:05 UTC
Labels: feature, post parsing
