### ISSUE TITLE
Discussion | Support i2p

### ISSUE THREAD

**Issue by oijkhg** [diaspora/diaspora#8032] opened 2019-06-19 05:10 UTC
**Objective**: Enable/Create Diaspora instance(s) hosted over I2p.
The end-goal is that the end-user will only need to connect to Diaspora using I2p.

**Description**: I noticed there weren't any Diaspora instances over i2p and wanted to discuss the possibility of Diaspora instances utilizing the .i2p TLD and any issues that may arise.

**Why?**: Many reasons, mainly to create better privacy and security but also to support decentralized web communications.

**The issue**: Most Diaspora sites are on the clearnet, how would an i2p instance communicate? Should a proxy (example: false.i2p) be used?
Or would the instance communicate with other instances over clearnet.

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/

https://git.pleroma.social/pleroma/pleroma/wikis/I2P-Federation

https://www.wikipedia.org/wiki/I2p

_____________

Want to support this issue? Post a [bounty on it](url)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=)]()

**Comment by SuperTux88** [comment] 2019-06-19 11:07
Duplicate of #2243 ... please stop spamming ...

**Closed by SuperTux88** 2019-06-19 11:07 UTC
