### ISSUE TITLE
can't run diaspora with ./script/server

### ISSUE THREAD

**Issue by fateme3** [diaspora/diaspora#8393] opened 2022-09-08 11:28 UTC
i got these when i run my diaspora server, can somebody help me?

`Starting Diaspora in development mode with job processing inside the request cycle.

I, [2022-09-08T15:57:54.063640 #3778]  INFO -- : [diaspora:__default__] call: 
I, [2022-09-08T15:57:54.063760 #3778]  INFO -- : [diaspora:__default__] schedule :monitor (load by user)
I, [2022-09-08T15:57:54.063957 #3778]  INFO -- : [diaspora:__default__] => monitor  (load by user)
I, [2022-09-08T15:57:54.064032 #3778]  INFO -- : [diaspora:__default__] starting async with 0.2s chain monitor 
I, [2022-09-08T15:57:54.064558 #3778]  INFO -- : [diaspora:web] schedule :monitor (monitor by user)
I, [2022-09-08T15:57:54.064768 #3778]  INFO -- : [diaspora:web] => monitor  (monitor by user)
I, [2022-09-08T15:57:54.065340 #3778]  INFO -- : [Eye] <= loading: ["/Users/fateme/Desktop/diaspora/config/eye.rb"]
I, [2022-09-08T15:57:54.117836 #3778]  INFO -- : [Eye] <= command: load /Users/fateme/Desktop/diaspora/config/eye.rb (2.139999s)
I, [2022-09-08T15:57:54.118055 #3778]  INFO -- : [diaspora:web] load_external_pid_file: pid_file found, but process <3564> not found
I, [2022-09-08T15:57:54.118845 #3778]  INFO -- : [diaspora:web] switch :starting [:unmonitored => :starting] monitor by user
I, [2022-09-08T15:57:54.066694 #3778]  INFO -- : [diaspora:__default__] <= monitor
I, [2022-09-08T15:57:54.127747 #3778]  INFO -- : [diaspora:web] daemonizing: `bin/bundle exec unicorn -c config/unicorn.rb` with start_grace: 2.5s, env: 'RAILS_ENV=development PORT=', <3909> (in /Users/fateme/Desktop/diaspora)
I, [2022-09-08T15:57:54.129454 #3778]  INFO -- : [diaspora:web] sleeping for :start_grace 2.5
I, [2022-09-08T15:57:56.633823 #3778]  INFO -- : [diaspora:web] switch :started [:starting => :up] monitor by user
I, [2022-09-08T15:57:56.645881 #3778]  INFO -- : [diaspora:web] <= monitor
W, [2022-09-08T15:58:01.636308 #3778]  WARN -- : [diaspora:web] check_alive: process <3909> not found
I, [2022-09-08T15:58:01.636756 #3778]  INFO -- : [diaspora:web] delete pid_file: /Users/fateme/Desktop/diaspora/tmp/pids/web.pid
I, [2022-09-08T15:58:01.637269 #3778]  INFO -- : [diaspora:web] switch :crashed [:up => :down] crashed
I, [2022-09-08T15:58:01.637920 #3778]  INFO -- : [diaspora:web] schedule :check_crash (crashed)
I, [2022-09-08T15:58:01.638235 #3778]  INFO -- : [diaspora:web] => check_crash  (crashed)
W, [2022-09-08T15:58:01.638325 #3778]  WARN -- : [diaspora:web] check crashed: process is down
I, [2022-09-08T15:58:01.638380 #3778]  INFO -- : [diaspora:web] schedule :restore (crashed)
I, [2022-09-08T15:58:01.638426 #3778]  INFO -- : [diaspora:web] <= check_crash
I, [2022-09-08T15:58:01.638466 #3778]  INFO -- : [diaspora:web] => restore  (crashed)
I, [2022-09-08T15:58:01.740642 #3778]  INFO -- : [diaspora:web] load_external_pid_file: pid_file not found
I, [2022-09-08T15:58:01.741084 #3778]  INFO -- : [diaspora:web] switch :starting [:down => :starting] crashed
I, [2022-09-08T15:58:01.749456 #3778]  INFO -- : [diaspora:web] daemonizing: `bin/bundle exec unicorn -c config/unicorn.rb` with start_grace: 2.5s, env: 'RAILS_ENV=development PORT=', <3912> (in /Users/fateme/Desktop/diaspora)
I, [2022-09-08T15:58:01.749792 #3778]  INFO -- : [diaspora:web] sleeping for :start_grace 2.5
I, [2022-09-08T15:58:04.253452 #3778]  INFO -- : [diaspora:web] switch :started [:starting => :up] crashed
I, [2022-09-08T15:58:04.265899 #3778]  INFO -- : [diaspora:web] <= restore
W, [2022-09-08T15:58:09.256037 #3778]  WARN -- : [diaspora:web] check_alive: process <3912> not found
I, [2022-09-08T15:58:09.256288 #3778]  INFO -- : [diaspora:web] delete pid_file: /Users/fateme/Desktop/diaspora/tmp/pids/web.pid
I, [2022-09-08T15:58:09.256791 #3778]  INFO -- : [diaspora:web] switch :crashed [:up => :down] crashed
I, [2022-09-08T15:58:09.257253 #3778]  INFO -- : [diaspora:web] schedule :check_crash (crashed)
I, [2022-09-08T15:58:09.257627 #3778]  INFO -- : [diaspora:web] => check_crash  (crashed)
W, [2022-09-08T15:58:09.257696 #3778]  WARN -- : [diaspora:web] check crashed: process is down
I, [2022-09-08T15:58:09.257746 #3778]  INFO -- : [diaspora:web] schedule :restore (crashed)
I, [2022-09-08T15:58:09.257793 #3778]  INFO -- : [diaspora:web] <= check_crash
I, [2022-09-08T15:58:09.257823 #3778]  INFO -- : [diaspora:web] => restore  (crashed)
I, [2022-09-08T15:58:09.361715 #3778]  INFO -- : [diaspora:web] load_external_pid_file: pid_file not found
I, [2022-09-08T15:58:09.362100 #3778]  INFO -- : [diaspora:web] swit`

**Comment by fateme3** [comment] 2022-09-08 11:29
`if`

**Comment by jhass** [comment] 2022-09-08 11:39
Please check `/Users/fateme/Desktop/diaspora/log/eye_processes_stderr.log`.

**Comment by fateme3** [comment] 2022-09-08 13:02
> Please check `/Users/fateme/Desktop/diaspora/log/eye_processes_stderr.log`.

this path contains these lines:
connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
 (ActiveRecord::ConnectionNotEstablished)
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/activerecord-6.1.6.1/lib/active_record/connection_handling.rb:283:in `connection'
config/unicorn.rb:19:in `block in reload'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:541:in `spawn_missing_workers'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:143:in `start'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/bin/unicorn:23:in `load'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/bin/unicorn:23:in `<main>'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/bin/ruby_executable_hooks:22:in `eval'
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/bin/ruby_executable_hooks:22:in `<main>'
I, [2022-09-08T15:09:25.891115 #1849]  INFO -- : Refreshing Gem list
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
/Users/fateme/.rvm/gems/ruby-2.7.2@diaspora/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35: warning: ⛔️ WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.
root  ............................................  *debug      -T
- <Appenders::Stdout name="stdout">
- <Appenders::RollingFile name="file">
  ActionView::Base  ..............................  *debug  +A  -T
  ActiveRecord::Base  ............................  *debug  +A  -T
  ActiveSupport::Cache::NullStore  ...............   debug  +A  -T
  ActiveSupport::Dependencies  ...................   debug  +A  -T
  DiasporaFederation  ............................   debug  +A  -T
    DiasporaFederation::Salmon::MagicEnvelope  ...   *info  +A  -T
  Logging  .......................................    *off  -A  -T
  Rails  .........................................   debug  +A  -T

**Comment by cmrd-senya** [comment] 2022-09-08 15:45
> connection to server at "127.0.0.1", port 5432 failed: Connection refused

This message indicates that your postgresql database is unavailable. Do you have it up? How do you run the DB service?

**Comment by SuperTux88** [comment] 2022-09-09 01:46
Since this is a local setup issue and not a bug, I'm closing this.

For the future, there is a support section on our discourse: https://discourse.diasporafoundation.org/c/support/developer-support/16, please use that when asking for support instead of using GitHub for that.

**Closed by SuperTux88** 2022-09-09 01:46 UTC
Labels: 🔧 setup issue
