### ISSUE TITLE
Long URL with hyphens (-) is truncated

### ISSUE THREAD

**Issue by vramdal** [diaspora/diaspora#7256] opened 2016-12-19 14:53 UTC
See https://joindiaspora.com/posts/8387207#c37225c0a8270134580d0242ac110007

Here's a rather long URL being shared (`https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-umulige-nordlys_bildet-1.13268025`). For some reason, only the part up to `umulige` is recognized as a URL. `umulige` is italicized. So the entire URL is displayed as:

[https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-](https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-)_umulige_-nordlys_bildet-1.13268025

Clicking the link leads to `https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-` which is a 404.

**Comment by SuperTux88** [comment] 2016-12-19 15:03
The url you posted in the post was `https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-_umulige_-nordlys_bildet-1.13268025` and not `https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-umulige-nordlys_bildet-1.13268025`. The problem is the `_` and not the `-` (which is a known problem). We decided here: https://github.com/diaspora/diaspora/issues/5563#issuecomment-122715825 that we won't fix that, because you can just write `<https://www.nrk.no/nordland/xl/brukte-to-uker-pa-a-ta-det-_umulige_-nordlys_bildet-1.13268025>` and it would be rendered correctly.

**Closed by SuperTux88** 2016-12-19 15:03 UTC
