### ISSUE TITLE
Mute notifications from ignored users

### ISSUE THREAD

**Issue by atari130xe** [diaspora/diaspora#6294] opened 2015-08-04 18:36 UTC
For some reason I am experiencing an annoying issue with "...is sharing with you" notifications, a user from @friendicared.de started to share with my profile on @diaspora.com.ar a couple of days ago, since that precise moment, I keep receiving along the whole day hundred of ".... is sharing with you" notifications each 3 or 5 minutes. I have ignored the user and I am still receiving a lot
![notisss](https://cloud.githubusercontent.com/assets/302876/9069229/6d49323c-3abe-11e5-830a-4913c190aabe.png)
 of notifications from the same user.

Thank you!
Jose Luis
my Diaspora username: atari130xe@diaspora.com.ar

**Comment by svbergerem** [comment] 2015-08-04 18:41
That might be an issue of friendica or a bot. Whatever the problem in this specific case is, I think when someone ignores another user that should also block notifications from that user.

**Comment by atari130xe** [comment] 2015-08-04 18:45
I agree, its really annoying because I get a lot of notifications along the day.

**Comment by Flaburgan** [comment] 2015-08-04 21:36
That's a long time I didn't see this bug, but we definitely already have an issue about it. I just can't find it...

**Comment by SansPseudoFix** [comment] 2015-08-04 21:53
@Flaburgan this one #2483?

**Comment by Flaburgan** [comment] 2015-08-04 22:00
Exactly. Which pod are you using @atari130xe and what's the server of your contact?

**Comment by SuperTux88** [comment] 2015-08-04 22:04
#2483 was a bug in diaspora (auto-follow-back) and is fixed now. This one is a new one caused by redmatrix and should be reported to them. the only thing we can do for this is blocking the notifications when the user ignores the other user (as @svbergerem  already said)

**Comment by atari130xe** [comment] 2015-08-04 22:20
Flaburgan: My pod is @diaspora.com.ar and the problem is with a @friendicared.de pod

**Comment by atari130xe** [comment] 2015-08-07 03:52
Flood of notifications has stopped, thank you!

**Comment by svbergerem** [comment] 2015-08-07 07:42
I still think that this is a valid feature request.

**Comment by jaywink** [comment] 2015-08-07 07:54
Yeah, the system should not allow flooding of notifications by a rogue server. Also the fact that ignore has happened makes this almost a bug..

**Comment by denschub** [comment] 2015-08-08 16:39
I've changed the title to make an actual feature request out of it...

**Comment by atari130xe** [comment] 2015-08-31 18:54
Uh Oh here you go once again now from friendicared.net, many "Is sharing with you" notifications since a couple of days...

**Comment by svbergerem** [comment] 2016-08-12 09:08
@SuperTux88 Has this been fixed in the federation rewrite?

**Comment by SuperTux88** [comment] 2016-08-12 09:11
No, I haven't changed anything here, but this should be easy to fix, I'll have a look at the weekend.

**Closed** 2016-08-14 16:28 UTC
Labels: feature
