### ISSUE TITLE
Missing landing page in mobile view

### ISSUE THREAD

**Issue by goobertron** [diaspora/diaspora#4518] opened 2013-09-12 17:49 UTC
I've just noticed that by going to a pod's landing page/root page when logged out, and then clicking 'toggle mobile', the page becomes blank (with just the mobile background), and the message

    put something in app/views/home/_show.html

is displayed.

I've checked this on a number of pods, running 0.2.0.0, 0.1.1.0 and development code, and all of those which have the 'toggle mobile' link at the bottom right suffer from this problem, with the exceptions (out of those I tried) of https://diasp.eu/ (which has a 'beta' design for mobile - 'A creative way to remix your world') and https://diapod.net (which has a bespoke page displaying stats).

When visiting the site root from a mobile device (my phone), I'm automatically redirected to the sign-in page (except for the two pods mentioned above which have their own landing pages in mobile view), so it seems that mobile users won't be hitting this problem. Even so, it would be good to tidy up this little loophole.

**Comment by svbergerem** [comment] 2015-05-03 10:06
I think we (somehow) solved this. On the standard landing page there is no toggle mobile anymore so I went to the sign in page, followed the toggle mobile link and then went back to the landing page.

The landing page is now the same for mobile and desktop users but the favicon is different. When following the sign in link you are again on the mobile sign in page.

Is there anything else we need to do to close this issue?

**Closed** 2015-05-04 23:50 UTC
Labels: bounty, bug, mobile

**Comment by RichKavanagh** [comment] 2015-05-05 09:49
Unless I've misunderstood something here, I can still replicate this issue?

Steps to reproduce:

1) Goto https://pod.omgsrsly.net/users/sign_in (or *pod.jpope.org* or *diaspora-fr.org*)
2) Click on toggle mobile
3) You are then returned to page: https://pod.omgsrsly.net/
4) You then see text: *put something in app/views/home/_show.html*
5) You are then stuck and cannot toggle back as there is nothing to click on

**Comment by Flaburgan** [comment] 2015-05-05 09:55
Did you run the last code, pulled tonight?

**Comment by RichKavanagh** [comment] 2015-05-05 10:03
No, they're not my pods :warning:  ;)

That's why I was wondering if I have misunderstood.

pod.jpope.org is claiming *'Code 0.5.99.0-pdae483bf'* and 0.5.99.0 is higher than the 0.5.1.0 milestone that jhass added to (above).

See my confusion? :)

So everything is ok, right?

**Comment by jhass** [comment] 2015-05-05 10:38
We switched version numbers there a bit, `x.y.99.0` is the development version for `x.y+1.0.0` (`0.6.0.0` in this case), `x.y.z.99` is the development version for `x.y.z+1.0` (`0.5.1.0` in this case).

`pxxxxx` remains to be the actual commit, `dae483bf`, if we follow that we find https://github.com/diaspora/diaspora/commit/dae483bf which was created 13 hours ago. https://github.com/diaspora/diaspora/commit/399fdb2c7d746d934cf85821e005c90a30294b44 is supposed to fix this which was committed 11 hours ago.

**Comment by svbergerem** [comment] 2015-05-05 11:12
@RichKavanagh try again on https://pod.omgsrsly.net. I just updated my pod. You are now redirected to the mobile sign in page because I don't have a custom mobile landing page.
