### ISSUE TITLE
Multiple comment box issues on slow networks

### ISSUE THREAD

**Issue by dimaursu** [diaspora/diaspora#5524] opened 2015-01-04 09:00 UTC
If the network is slow (I'm quite far from the access point), you can tap multiple times on the pencil icon, and spawn a bunch of comment boxes (9 is my record), because the guard is inside the body of the AJAX request: https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/mobile.js#L195

If the request takes a long time, and you manage to tap the pencil icon again, several AJAX requests will be fired at the same time, until one of the "sucess:" callback handlers will remove the "inactive" class.

**Comment by Flaburgan** [comment] 2015-01-04 11:06
Related to https://github.com/diaspora/diaspora/issues/5483

**Comment by dimaursu** [comment] 2015-01-04 16:02
@Flaburgan I though so, but I think this is a new issue. I have a fix for it, I've already tested it on two phones.

**Comment by dimaursu** [comment] 2015-01-04 16:03
You can still add 2 comment boxes on 2 different posts (If i'm understanding correctly #5483).

**Comment by dimaursu** [comment] 2015-01-04 20:47
https://github.com/dimaursu/diaspora/commit/5608ae01d3fc663349ccbbadebcb9b3d0df7bed9 
This is the solution I came up with.

**Comment by desyncr** [comment] 2015-01-07 20:54
@dimaursu With chrome dev tools you can emulate both mobile and network settings. I could reproduce it when the settings shown in the screenshot:

![screenshot from 2015-01-07 17 51 36](https://cloud.githubusercontent.com/assets/1857707/5653115/12477a1e-9696-11e4-85c9-8f30a4796372.png)

**Comment by dimaursu** [comment] 2015-01-08 03:21
@desyncr Can you please try my patch? I very simple, just 3 lines of code.

**Comment by Makailija** [comment] 2015-01-08 07:48
I believe this is basically a duplicate of #5479. See that there is also a PR addressing it: #5490.

And I don't think this is really related to #5483 (reported also by me): that one concerns faulty design that enables one to open two comment boxes for a single post by clicking the both pencil icon and the Comment button in ways that I explain on the bug report.

**Comment by desyncr** [comment] 2015-01-08 09:17
@Makailija It's the same behavior but not the same issue. Worth keeping them separated IMHO.
Definitely not related to https://github.com/diaspora/diaspora/issues/5483 .

@dimaursu I'll give it a try and come back with feedback as soon as I some time.

**Comment by dimaursu** [comment] 2015-02-08 01:09
So, is this issue solved? I can assume from the current code that the issue is still here - because the "inactive" class is not removed before firing the AJAX request.

**Comment by RichKavanagh** [comment] 2015-03-29 21:26
Any updates from anyone on this issue?

**Comment by desyncr** [comment] 2015-03-30 13:02
@RichKavanagh  I'll get back to it tonight or tomorrow.

**Comment by desyncr** [comment] 2015-03-31 02:53
@dimaursu You code works indeed.

Can you apply your changes to the lastest dev? [Here](https://gist.github.com/desyncr/a30c95b2129f4c6a3ae2) is a gist with the changes plus a fix that addresses #5483 (lines 11 and 14) (may be it should be handled in its own PR, though)

We'll need some regression tests, at least for #5483. Tell me if you need some help.

**Closed** 2015-08-29 15:03 UTC
Labels: bug, mobile
